/**
 * React Complete Course — Module 5: Patterns & Architecture, lesson 8
 * (final lesson of Module 5).
 *
 * Styling approaches at production scale: CSS Modules, Tailwind
 * (utility-first), and CSS-in-JS, contrasted against plain global CSS
 * with hand-written, unscoped class names. Broken example: two unrelated
 * components each define their own global .title class in their own
 * plain .css file; whichever stylesheet happens to load last silently
 * overrides the other, producing a real, hard-to-trace visual bug in a
 * completely unrelated part of the app, because plain CSS has no
 * built-in scoping mechanism at all. Fixed by contrasting three
 * production-proven approaches that each solve the scoping problem
 * differently — CSS Modules (build-tool-generated unique class names),
 * Tailwind (no custom CSS at all, composable utility classes), and
 * CSS-in-JS (component-scoped, prop-driven styles) — with an honest
 * accounting of each one's own real trade-offs rather than declaring
 * a single winner.
 *
 * NOTE for future editors: escape every inline-code backtick inside these
 * template literals, INCLUDING inside plain markdown paragraphs (the
 * `content`/`contentHi`/`simple`/`simpleHi` fields). Single-quoted string
 * fields (explain, why, q, a, task, keyTakeaways, etc.) do NOT need backticks
 * escaped — only escape apostrophes there as a SINGLE backslash (\'), never
 * doubled (\\'), which breaks the string. Run `npx tsc --noEmit -p .` after
 * writing this file, before wiring it into seed.ts — it is the only fully
 * reliable check for both mistakes.
 */

import type { CourseLesson } from './course-js-module1';

export const REACT_MODULE_5_PART8: CourseLesson[] = [
  {
    slug: 'styling-approaches-at-production-scale',
    title: 'Styling Approaches at Production Scale',
    titleHi: 'Production Scale Par Styling Approaches',
    description: 'A designer changes the color of a promotional banner\'s title, and three completely unrelated screens across the app silently change color too — because all four components happened to share a single, generic, global .title class, and CSS itself has no idea any of them were supposed to be separate.',
    descriptionHi: 'Ek designer ek promotional banner ke title ka color badalta hai, aur teen bilkul na-judi screens poori app ke aar-paar chupchaap color badal jaati hain — kyunki sab char components samyog se ek akela, generic, global \`.title\` class share karte the, aur CSS khud ko ye pata hi nahi ki unmein se koi bhi alag hone chahiye the.',
    difficulty: 'HARD',
    duration: 20,
    order: 8,

    analogy: {
      en: '**A shared apartment laundry room where every tenant\'s clothes go into the same communal baskets with nothing but a handwritten "Mine" tag that anyone could have written on any bag — versus a hotel laundry service that gives every single guest\'s bag its own unique, machine-printed barcode tied specifically to their room, so nothing from room 204 can ever end up mixed into room 305\'s bag purely by coincidence.** In the shared laundry room, if two tenants both happen to write "Mine" on a plain bag, there is nothing about the system itself preventing one tenant\'s clothes from being scooped into the wrong bag — the "Mine" label only works as long as everyone happens to choose a genuinely unique label, and nothing enforces that they will. In the hotel system, a barcode is generated by the hotel\'s own machine specifically for one guest\'s specific bag; it is not something a guest writes by hand, so there is no possibility of two guests\' bags accidentally sharing an identical label, since the system itself, not each guest\'s own memory or diligence, is what guarantees uniqueness. Plain, hand-written global CSS class names, like \`.title\` or \`.card\`, are the shared laundry room: nothing about CSS itself stops two unrelated components from choosing the exact same class name, and whichever stylesheet happens to load last simply overwrites the other\'s styling for that name, entirely by accident. CSS Modules, Tailwind, and CSS-in-JS are three different versions of the hotel\'s barcode system — each ensures, through its own distinct mechanism, that one component\'s styling can never accidentally collide with an unrelated component\'s styling, without relying on every developer remembering to hand-pick a genuinely unique name every single time.',
      hi: '**Ek shared apartment laundry room jahan har tenant ke kapde usi communal baskets mein jaate hain kuch nahi bas ek haath se likhi "Mera" tag ke saath jo koi bhi kisi bhi bag par likh sakta tha — versus ek hotel laundry service jo har akele guest ke bag ko apna khud ka unique, machine-printed barcode deti hai khaas taur par unke room se juda, taaki room 204 se kuch bhi kabhi room 305 ke bag mein samyog se mil na sake.** Shared laundry room mein, agar do tenants dono samyog se ek saadhe bag par "Mera" likhte hain, system mein khud kuch bhi nahi hai jo ek tenant ke kapdon ko galat bag mein uthaane se roke — "Mera" label sirf tab tak kaam karta hai jab tak har koi samyog se ek sach mein unique label chunta hai, aur kuch bhi ise lagu nahi karta ki wo aisa karenge. Hotel system mein, ek barcode hotel ki apni machine dwara khaas taur par ek guest ke khaas bag ke liye banaayi jaati hai; ye kuch nahi hai jo ek guest haath se likhta hai, isliye do guests ke bags ke samyog se ek jaisa label share karne ki koi sambhaavna nahi hai, kyunki system khud, har guest ki apni yaadaasht ya lagan nahi, wo hai jo uniqueness guarantee karta hai. Saadhe, haath-se-likhe global CSS class names, jaisa \`.title\` ya \`.card\`, shared laundry room hain: CSS mein khud kuch bhi do na-judi components ko bilkul wahi class naam chunne se nahi rokta, aur jo bhi stylesheet samyog se aakhri baar load hoti hai bas us naam ke liye doosre ki styling ko overwrite kar deti hai, poori tarah samyog se. CSS Modules, Tailwind, aur CSS-in-JS hotel ke barcode system ke teen alag versions hain — har ek, apne khud ke alag mechanism ke zariye, sunishchit karta hai ki ek component ki styling kabhi bhi galti se ek na-judi component ki styling se takraa nahi sakti, har developer ke har baar ek sach mein unique naam haath se chunne ko yaad rakhne par nirbhar hue bina.',
    },

    simple: `**Start broken.** Two unrelated components, each with their own plain, global CSS file, both defining .title:

\`\`\`css
/* PromoBanner.css */
.title {
  color: red;
  font-size: 32px;
}
\`\`\`

\`\`\`css
/* UserProfileCard.css */
.title {
  color: navy;
  font-size: 14px;
}
\`\`\`

\`\`\`jsx
import "./PromoBanner.css";
import "./UserProfileCard.css";

function PromoBanner() {
  return <h1 className="title">50% Off Today!</h1>;
}

function UserProfileCard() {
  return <h3 className="title">Jordan Lee</h3>;
}
\`\`\`

Both stylesheets define a rule for the exact same class name, \`.title\`, with no relationship to each other and no awareness that the other exists — CSS itself has no concept of "this \`.title\` belongs only to \`PromoBanner\`." Whichever of these two \`.css\` files happens to be imported, and therefore loaded into the page, LAST wins for every single element anywhere on the page carrying the \`title\` class, completely independent of which component that element actually belongs to. If \`UserProfileCard.css\` loads after \`PromoBanner.css\`, the promo banner\'s heading silently shrinks to 14px and turns navy, a bug whose actual cause — an entirely unrelated component\'s stylesheet, possibly in a completely different folder — is genuinely difficult to trace back to from just looking at \`PromoBanner\`\'s own code, since nothing in \`PromoBanner.jsx\` or \`PromoBanner.css\` themselves reveals that a collision is even possible.

**The fix: give each component\'s classes their own guaranteed-unique identity**

\`\`\`jsx
// CSS Modules — the build tool generates a unique class name per file
import styles from "./PromoBanner.module.css";

function PromoBanner() {
  return <h1 className={styles.title}>50% Off Today!</h1>;
  // compiles to something like className="PromoBanner_title__aB3dE"
}
\`\`\`

With CSS Modules, \`PromoBanner.module.css\`\'s own \`.title\` rule is compiled by the build tool into a class name that is unique to THIS file specifically, such as \`PromoBanner_title__aB3dE\` — \`UserProfileCard.module.css\`\'s own separate \`.title\` rule compiles to an entirely different generated name, such as \`UserProfileCard_title__f8k2L\`. Both files can keep writing the plain, readable name \`.title\` in their own source code, but the actual class name that ends up in the rendered HTML is guaranteed unique by the build process itself, not by developers remembering to invent ever-more-specific names like \`.promo-banner-title-v2\` by hand.`,

    simpleHi: `**Toote hue se shuru.** Do na-judi components, har ek apni khud ki saadhi, global CSS file ke saath, dono \`.title\` define karte hue:

\`\`\`css
/* PromoBanner.css */
.title {
  color: red;
  font-size: 32px;
}
\`\`\`

\`\`\`css
/* UserProfileCard.css */
.title {
  color: navy;
  font-size: 14px;
}
\`\`\`

\`\`\`jsx
import "./PromoBanner.css";
import "./UserProfileCard.css";

function PromoBanner() {
  return <h1 className="title">50% Off Today!</h1>;
}

function UserProfileCard() {
  return <h3 className="title">Jordan Lee</h3>;
}
\`\`\`

Dono stylesheets bilkul usi class naam, \`.title\`, ke liye ek rule define karte hain, ek doosre se koi rishta nahi aur ek doosre ke astitva ka koi gyaan nahi — CSS mein khud "ye \`.title\` sirf \`PromoBanner\` se belong karta hai" jaisa koi concept nahi hai. In do \`.css\` files mein se jo bhi samyog se import ho, aur isliye page mein AAKHRI load ho, poore page par kahin bhi \`title\` class rakhne waale har akele element ke liye jeet jaata hai, poori tarah is baat se azaad ki wo element asal mein kis component se belong karta hai. Agar \`UserProfileCard.css\` \`PromoBanner.css\` ke baad load hoti hai, promo banner ka heading chupchaap 14px tak simat jaata hai aur navy ho jaata hai, ek bug jiska asli kaaran — ek poori tarah na-judi component ki stylesheet, sambhaavit roop se ek bilkul alag folder mein — sirf \`PromoBanner\` ke apne code ko dekhkar sach mein trace karna mushkil hai, kyunki \`PromoBanner.jsx\` ya \`PromoBanner.css\` khud mein kuch bhi nahi darsata ki ek collision bhi mumkin hai.

**Fix: har component ki classes ko unki apni guaranteed-unique pehchaan do**

\`\`\`jsx
// CSS Modules — build tool prati-file ek unique class naam banaata hai
import styles from "./PromoBanner.module.css";

function PromoBanner() {
  return <h1 className={styles.title}>50% Off Today!</h1>;
  // kuch aisa compile hota hai className="PromoBanner_title__aB3dE"
}
\`\`\`

CSS Modules ke saath, \`PromoBanner.module.css\` ka apna \`.title\` rule build tool dwara ek class naam mein compile hota hai jo khaas taur par ISI file ke liye unique hai, jaisa \`PromoBanner_title__aB3dE\` — \`UserProfileCard.module.css\` ka apna alag \`.title\` rule ek bilkul alag banaaye gaye naam mein compile hota hai, jaisa \`UserProfileCard_title__f8k2L\`. Dono files apne khud ke source code mein saadha, padhne-yogya naam \`.title\` likhte reh sakti hain, par asli class naam jo rendered HTML mein aata hai build process khud dwara unique guarantee kiya jaata hai, developers ke haath se \`.promo-banner-title-v2\` jaisa har-baar-zyaada-khaas naam ijaad karna yaad rakhne se nahi.`,

    content: `## Three production-proven ways to solve the same scoping problem

CSS Modules is one solution to the collision problem this lesson opened with, but it is not the only one used in real production apps, and each of the three most common approaches makes a genuinely different trade-off.

### Tailwind: no custom CSS files at all

\`\`\`jsx
function PromoBanner() {
  return <h1 className="text-4xl font-bold text-red-600">50% Off Today!</h1>;
}

function UserProfileCard() {
  return <h3 className="text-sm font-semibold text-blue-900">Jordan Lee</h3>;
}
\`\`\`

Tailwind sidesteps the naming-collision problem in a completely different way: instead of writing any custom CSS rule at all, a component is styled by composing small, pre-defined, single-purpose utility classes (\`text-4xl\`, \`font-bold\`, \`text-red-600\`) directly in the JSX. Since there is no custom \`.title\` class being invented per component in the first place, there is nothing to collide — every class used is one of a small, shared, pre-defined vocabulary, and the exact visual result (font size, color, spacing) comes from a shared design-token configuration rather than from hand-written CSS values, which also means every component styled this way automatically stays visually consistent with the same underlying scale. The real cost is that a component\'s \`className\` string can become long and, to someone unfamiliar with Tailwind\'s naming conventions, harder to read at a glance than a single semantic class name like \`.title\` would be — and adopting it means a team commits to learning its utility vocabulary and its configuration file as the actual source of truth for spacing, color, and type scale, rather than plain CSS values.

### CSS-in-JS: styles co-located with, and driven by, the component itself

\`\`\`jsx
import styled from "styled-components";

const Title = styled.h1\`
  color: \${(props) => (props.urgent ? "red" : "navy")};
  font-size: 32px;
\`;

function PromoBanner({ isUrgent }) {
  return <Title urgent={isUrgent}>50% Off Today!</Title>;
}
\`\`\`

CSS-in-JS libraries such as styled-components or Emotion solve scoping the same way CSS Modules effectively does — by generating a unique class name per styled component behind the scenes — while additionally letting a style\'s actual values respond directly to a component\'s own props, without needing a separate mechanism (like conditionally choosing between multiple CSS-Module class names) to express that dynamic behavior. The historical cost specific to this approach is that some CSS-in-JS libraries compute and inject styles into the page AT RUNTIME, in the browser, which is genuine additional work the browser must do beyond what plain CSS or CSS Modules require, and can measurably affect performance on lower-end devices if not accounted for; several more recent CSS-in-JS libraries address this specifically by extracting styles at BUILD time instead, producing plain, static CSS files much like CSS Modules does, which avoids that particular runtime cost — whether a specific library does this is a genuine, current-state question worth checking before adopting one for a performance-sensitive app, rather than an assumption to make either way.

## No single answer — this is a genuine, current trade-off, not a solved debate

\`\`\`
CSS Modules   → plain CSS syntax teams already know, file-per-component, less built-in support for prop-driven dynamic styling
Tailwind      → no naming decisions at all, consistent design tokens, longer className strings, a vocabulary to learn
CSS-in-JS     → co-located + prop-driven styling, historical runtime cost (mitigated by some libraries' build-time extraction)
\`\`\`

A genuinely common mistake at the "pro" level is treating this as a solved question with one objectively correct answer, when in reality large, real production codebases successfully use all three approaches, and the right choice depends on a team\'s own priorities — how much a team already knows plain CSS, how much dynamic, prop-driven styling a given app actually needs, and how much weight is placed on a design system\'s visual consistency being enforced automatically versus by convention. What matters at a professional level is being able to articulate each approach\'s actual trade-offs accurately, as this lesson has, rather than treating any one of them as a default without being able to explain why.`,

    contentHi: `## Ek hi scoping samasya ko sulajhaane ke teen production-proven tarike

CSS Modules is lesson ne shuru mein jo collision samasya kholi uska ek solution hai, par ye asli production apps mein istemal hone waala akela nahi hai, aur teen sabse aam approaches mein se har ek sach mein alag trade-off banaata hai.

### Tailwind: koi custom CSS files bilkul nahi

\`\`\`jsx
function PromoBanner() {
  return <h1 className="text-4xl font-bold text-red-600">50% Off Today!</h1>;
}

function UserProfileCard() {
  return <h3 className="text-sm font-semibold text-blue-900">Jordan Lee</h3>;
}
\`\`\`

Tailwind naming-collision samasya ko ek bilkul alag tarike se taalta hai: koi bhi custom CSS rule bilkul likhne ke bajaye, ek component ko chhote, pehle-se-define-kiye-gaye, ek-maksad-wale utility classes (\`text-4xl\`, \`font-bold\`, \`text-red-600\`) compose karke seedhe JSX mein style kiya jaata hai. Kyunki koi custom \`.title\` class prati-component shuru mein hi ijaad nahi ho rahi, takraane ke liye kuch bhi nahi hai — istemal ki jaane waali har class ek chhoti, shared, pehle-se-define-ki-gayi vocabulary mein se ek hai, aur asli visual nateeja (font size, color, spacing) ek shared design-token configuration se aata hai haath-se-likhe CSS values ke bajaye, jiska matlab bhi hai ki is tarike se style kiya gaya har component automatically usi underlying scale ke saath visually consistent rehta hai. Asli keemat ye hai ki ek component ki \`className\` string lambi ban sakti hai aur, Tailwind ke naming conventions se ana-jaanwaale kisi ke liye, ek nazar mein padhna mushkil ho sakta hai \`.title\` jaise ek akele semantic class naam se — aur ise apnaane ka matlab hai ki ek team iski utility vocabulary aur iski configuration file ko asli sach ka source ki tarah seekhne ke liye committed hai spacing, color, aur type scale ke liye, saadhe CSS values ke bajaye.

### CSS-in-JS: styles component ke saath rakhi gayi, aur usi se chalaayi jaati hain

\`\`\`jsx
import styled from "styled-components";

const Title = styled.h1\`
  color: \${(props) => (props.urgent ? "red" : "navy")};
  font-size: 32px;
\`;

function PromoBanner({ isUrgent }) {
  return <Title urgent={isUrgent}>50% Off Today!</Title>;
}
\`\`\`

CSS-in-JS libraries jaisa styled-components ya Emotion scoping ko usi tarike se sulajhaate hain jaisa CSS Modules asar mein karta hai — parde ke peeche prati-styled-component ek unique class naam banaake — jabki atirikt roop se ek style ki asli values ko seedhe ek component ke apne props ka jawaab dene dete hue, us dynamic vyavahaar ko darsaane ke liye ek alag mechanism (jaisa kayi CSS-Module class names ke beech conditionally chunna) ki zaroorat ke bina. Is approach se khaas taur par judi historical keemat ye hai ki kuch CSS-in-JS libraries styles ko RUNTIME par ganti aur page mein inject karti hain, browser mein, jo asli atirikt kaam hai jo browser ko karna padta hai us se aage jo saadha CSS ya CSS Modules maangte hain, aur agar iska hisaab na rakha jaaye toh kam-shakti waali devices par performance ko maayne-yogya roop se prabhaavit kar sakta hai; kayi zyaada haaliya CSS-in-JS libraries ise khaas taur par styles ko BUILD time par nikaalkar sambodhit karti hain iske bajaye, saadhi, static CSS files banaate hue bahut kuch CSS Modules ki tarah, jo us khaas runtime keemat ko avoid karta hai — kya ek khaas library aisa karti hai ek asli, current-state sawaal hai jise ek performance-sensitive app ke liye ek chunne se pehle check karna vazan rakhta hai, kisi bhi disha mein ek dhaarna banaane ke bajaye.

## Koi akela jawaab nahi — ye ek asli, current trade-off hai, koi sulajhi hui behas nahi

\`\`\`
CSS Modules   → saadha CSS syntax jo teams pehle se jaanti hain, prati-component file, prop-driven dynamic styling ke liye kam built-in support
Tailwind      → koi naming faisle bilkul nahi, consistent design tokens, lambi className strings, seekhne ke liye ek vocabulary
CSS-in-JS     → saath-rakhi + prop-driven styling, historical runtime keemat (kuch libraries ki build-time extraction se kam ki gayi)
\`\`\`

"Pro" star par ek sach mein aam galti ise ek sulajhe hue sawaal ki tarah treat karna hai jiska ek objectively sahi jawaab hai, jabki asal mein bade, asli production codebases safaltapoorvak teeno approaches istemal karte hain, aur sahi chunaav ek team ki apni priorities par nirbhar karta hai — team pehle se saadha CSS kitna jaanti hai, ek diye gaye app ko asal mein kitni dynamic, prop-driven styling chahiye, aur ek design system ki visual consistency automatically lagu hone par kitna vazan rakha jaata hai convention se hone ke saapeksh. Professional star par jo maayne rakhta hai wo har approach ke asli trade-offs ko sahi tarike se bayaan kar sakna hai, jaisa is lesson ne kiya, unmein se kisi ek ko bina samjhaaye ki kyun ek default ki tarah treat karne ke bajaye.`,

    examples: [
      {
        title: 'Broken: two components collide on the same global .title class',
        titleHi: 'Toota: do components ek hi global \`.title\` class par takraate hain',
        code: `/* PromoBanner.css */ .title { color: red; font-size: 32px; }
/* UserProfileCard.css */ .title { color: navy; font-size: 14px; }
// whichever loads last wins, everywhere on the page`,
        codeJs: `import "./PromoBanner.css";
import "./UserProfileCard.css";

function PromoBanner() {
  return <h1 className="title">50% Off Today!</h1>;
}

function UserProfileCard() {
  return <h3 className="title">Jordan Lee</h3>;
}
// both elements' actual appearance depends on import order,
// not on which component they belong to`,
        codeTs: `function PromoBanner(): JSX.Element {
  return <h1 className="title">50% Off Today!</h1>;
}

function UserProfileCard(): JSX.Element {
  return <h3 className="title">Jordan Lee</h3>;
}
// fully valid TypeScript — the collision is a CSS scoping problem,
// entirely invisible to the type checker`,
        output: `Depending on import/load order, PromoBanner's heading may render
navy and 14px instead of its own intended red and 32px, with nothing
in PromoBanner's own files revealing why.`,
        explain: 'Plain CSS has no built-in scoping — two files defining the same class name for unrelated components silently collide, with whichever loads last winning everywhere on the page.',
        explainHi: 'Saadhe CSS mein koi built-in scoping nahi hai — do files jo na-judi components ke liye wahi class naam define karti hain chupchaap takraati hain, jo bhi aakhri load hoti hai wo poore page par jeette hue.',
      },
      {
        title: 'Fixed with CSS Modules: build-tool-guaranteed unique class names',
        titleHi: 'CSS Modules se theek: build-tool-guaranteed unique class names',
        code: `import styles from "./PromoBanner.module.css";
<h1 className={styles.title}>50% Off Today!</h1>
// compiles to a name unique to THIS file, e.g. PromoBanner_title__aB3dE`,
        codeJs: `// PromoBanner.module.css
.title { color: red; font-size: 32px; }

// PromoBanner.jsx
import styles from "./PromoBanner.module.css";

function PromoBanner() {
  return <h1 className={styles.title}>50% Off Today!</h1>;
}`,
        codeTs: `// PromoBanner.module.css
.title { color: red; font-size: 32px; }

// PromoBanner.tsx
import styles from "./PromoBanner.module.css";

function PromoBanner(): JSX.Element {
  return <h1 className={styles.title}>50% Off Today!</h1>;
}
// most build setups also generate a .d.ts file for the module,
// giving styles.title itself proper type-checking`,
        outputJs: `PromoBanner always renders red and 32px, entirely independent of
whether UserProfileCard.module.css is imported before or after it,
since the two compile to genuinely different class names.`,
        outputTs: `// Identical behaviour, plus compile-time checking that styles.title
// actually exists in PromoBanner.module.css.`,
        explain: 'The build tool generates a class name unique to this specific file, so an identically-named .title rule in a different file can never collide with it.',
        explainHi: 'Build tool ek class naam banaata hai jo is khaas file ke liye unique hai, isliye ek doosri file mein ek samaan-naam-wala \`.title\` rule ise kabhi takra nahi sakta.',
      },
      {
        title: 'Fixed with Tailwind: no custom class names to collide at all',
        titleHi: 'Tailwind se theek: takraane ke liye koi custom class names bilkul nahi',
        code: `<h1 className="text-4xl font-bold text-red-600">50% Off Today!</h1>
<h3 className="text-sm font-semibold text-blue-900">Jordan Lee</h3>
// both use the same shared utility vocabulary, nothing to collide`,
        codeJs: `function PromoBanner() {
  return <h1 className="text-4xl font-bold text-red-600">50% Off Today!</h1>;
}

function UserProfileCard() {
  return <h3 className="text-sm font-semibold text-blue-900">Jordan Lee</h3>;
}
// no custom .title class exists anywhere for these to collide over`,
        codeTs: `function PromoBanner(): JSX.Element {
  return <h1 className="text-4xl font-bold text-red-600">50% Off Today!</h1>;
}

function UserProfileCard(): JSX.Element {
  return <h3 className="text-sm font-semibold text-blue-900">Jordan Lee</h3>;
}
// fully valid TypeScript — Tailwind's utility classes are plain
// strings, requiring no additional type definitions to use`,
        outputJs: `Each component's appearance is determined entirely by its own
className string, composed from a small, shared utility vocabulary
— there is no per-component custom class name to accidentally reuse.`,
        outputTs: `// Identical behaviour. Editor tooling (the Tailwind IntelliSense
// extension) provides autocomplete and validation for these utility
// class strings even without custom TypeScript types.`,
        explain: 'Since no custom class name is invented per component, there is nothing for two components to accidentally share — the shared utility vocabulary is the same, intentional set for every component.',
        explainHi: 'Kyunki prati-component koi custom class naam ijaad nahi hota, do components ke pas galti se share karne ke liye kuch nahi hai — shared utility vocabulary har component ke liye wahi, jaan-boojhkar set hai.',
      },
    ],

    mistakes: [
      {
        wrong: `/* Component-A.css */ .title { ... }
/* Component-B.css */ .title { ... }
// two unrelated components, same plain global class name`,
        right: `import styles from "./ComponentA.module.css"; // or Tailwind, or CSS-in-JS
<h1 className={styles.title}>...</h1>`,
        why: 'Plain CSS has no built-in scoping mechanism — two files defining the same class name for unrelated components will silently collide, with load order determining which style wins.',
        whyHi: 'Saadhe CSS mein koi built-in scoping mechanism nahi hai — do files jo na-judi components ke liye wahi class naam define karti hain chupchaap takraayengi, load order tay karte hue ki kaunsi style jeetti hai.',
      },
      {
        wrong: `// adopting a CSS-in-JS library and assuming its runtime cost is negligible
// without checking whether it extracts styles at build time or runtime`,
        right: `// checking the specific library's current documentation for whether
// it performs build-time extraction before adopting it for a
// performance-sensitive app`,
        why: 'Some CSS-in-JS libraries genuinely compute and inject styles at runtime in the browser, which is real additional work that can measurably affect performance — this is a real, current-state question to verify, not a settled non-issue.',
        whyHi: 'Kuch CSS-in-JS libraries sach mein browser mein runtime par styles ganti aur inject karti hain, jo asli atirikt kaam hai jo performance ko maayne-yogya roop se prabhaavit kar sakta hai — ye ek asli, current-state sawaal hai verify karne ke liye, ek suljha hua non-issue nahi.',
      },
      {
        wrong: `// mixing CSS Modules, Tailwind, and CSS-in-JS across the same codebase
// with no stated convention for when to use which`,
        right: `// picking one primary approach as the team's stated default,
// with any exception genuinely justified`,
        why: 'Mixing multiple styling approaches inconsistently, without a stated convention, recreates a coordination problem similar to the one this lesson opened with — nobody can predict which approach governs a given piece of UI without checking.',
        whyHi: 'Ek hi codebase mein kayi styling approaches ko asangat tarike se milaana, bina kisi bataayi gayi convention ke, ek coordination samasya dobara banaata hai jo is lesson ne shuru mein kholi us jaisi — koi bhi bina check kiye predict nahi kar sakta ki UI ke ek diye gaye tukde ko kaunsa approach niyantrit karta hai.',
      },
    ],

    realWorld: [
      {
        en: '**CSS Modules, Tailwind, and CSS-in-JS libraries like styled-components and Emotion are all genuinely widely adopted in real production React codebases** — none of them is a niche or deprecated choice, and large companies use each of the three.',
        hi: '**CSS Modules, Tailwind, aur CSS-in-JS libraries jaisa styled-components aur Emotion sab sach mein asli production React codebases mein widely adopted hain** — inmein se koi bhi ek niche ya deprecated chunaav nahi hai, aur badi companies teeno mein se har ek istemal karti hain.',
      },
      {
        en: '**"Which styling approach would you pick for a new project, and why?" is a genuinely common frontend interview question specifically because it has no single correct answer** — interviewers are assessing whether a candidate can reason about the actual trade-offs.',
        hi: '**"Ek naye project ke liye tum kaunsa styling approach chunoge, aur kyun?" ek sach mein aam frontend interview sawaal hai khaas taur par kyunki iska koi ek sahi jawaab nahi hai** — interviewers ye assess kar rahe hain ki kya ek candidate asli trade-offs ke baare mein tark kar sakta hai.',
      },
      {
        en: '**Some CSS-in-JS libraries genuinely have moved toward build-time style extraction specifically to address the historical runtime-cost criticism**, confirming this is a real, evolving area rather than a settled weakness of the whole category.',
        hi: '**Kuch CSS-in-JS libraries sach mein build-time style extraction ki taraf badhi hain khaas taur par historical runtime-cost aalochana ko sambodhit karne ke liye**, ye confirm karte hue ki ye ek asli, badalti hui jagah hai poori category ki ek suljhi hui kamzori ke bajaye.',
      },
    ],

    interviewQA: [
      {
        q: 'Why does plain, hand-written global CSS become a genuine scaling problem in a large React app, and what do CSS Modules, Tailwind, and CSS-in-JS each do differently to solve it?',
        qHi: 'Saadha, haath-se-likha global CSS ek badi React app mein ek asli scaling samasya kyun ban jaata hai, aur CSS Modules, Tailwind, aur CSS-in-JS har ek ise sulajhaane ke liye alag kya karte hain?',
        a: 'CSS, as a language, has no built-in concept of a class name belonging exclusively to one specific component — a class selector like .title simply means "apply these rules to every single element on the page carrying the class title," regardless of which file, component, or feature that element happens to belong to, or which other files also happen to define rules for a class of the same name. In a small app with only a handful of components, this is rarely a practical problem, since developers can reasonably keep every class name in their head and simply avoid picking one that is already used elsewhere. As an app grows to have dozens or hundreds of components, often built by many different developers who cannot realistically know every class name every other developer has already used, the odds of two unrelated components independently choosing an identical, generic class name like .title, .card, or .button rise substantially, and when it happens, the resulting bug is a genuinely confusing one to track down, since nothing in either component\'s own code reveals that a collision occurred — the actual visual result silently depends on which stylesheet happened to be loaded onto the page last, an implementation detail unrelated to either component\'s own logic. CSS Modules solves this by having the build tool itself generate a class name that is guaranteed unique to the specific file it came from, so a developer can keep writing the same simple, readable .title in their own source file while the tool ensures the actual compiled class name can never collide with an identically-named class in a different file. Tailwind solves the same underlying problem from a different angle entirely: rather than inventing any new, custom class name per component in the first place, styling is expressed by composing a small, shared, pre-defined vocabulary of utility classes directly in markup, meaning there is no custom name for two components to accidentally choose identically, since neither one is choosing a custom name at all. CSS-in-JS libraries solve it in a manner closer to CSS Modules\' own approach, generating a unique, scoped class name specifically for each styled component defined in JavaScript, while additionally allowing that style\'s actual values to be computed dynamically from the component\'s own props, which CSS Modules does not directly support without additional conditional logic of its own.',
        aHi: 'CSS, ek bhaasha ki tarah, ek class naam ke sirf ek khaas component se belong karne ka koi built-in concept nahi rakhta — ek class selector jaisa \`.title\` bas iska matlab hai "in rules ko page par kahin bhi \`title\` class rakhne waale har akele element par lagu karo," chahe wo element kis file, component, ya feature se belong karta ho, ya kaunsi doosri files bhi samyog se usi naam ki class ke liye rules define karti hain. Ek chhoti app mein sirf mutthi-bhar components ke saath, ye shaayad hi kabhi ek vyaavahaarik samasya hai, kyunki developers vaajbi roop se har class naam apne dimaag mein rakh sakte hain aur bas ek aisa chunne se bach sakte hain jo kahin aur pehle se istemal ho raha hai. Jab ek app dozens ya sainkdon components rakhne ke liye badhti hai, aksar kayi alag developers dwara banaayi gayi jo asal mein har doosre developer ne pehle se kaunsi class naam istemal ki hai ye jaanna vyaavahaarik roop se nahi jaan sakte, do na-judi components ke azaadi se ek samaan, generic class naam jaisa \`.title\`, \`.card\`, ya \`.button\` chunne ki sambhaavna kaafi badh jaati hai, aur jab ye hota hai, nateeje wala bug sach mein pata lagaana ek confusing hai, kyunki kisi bhi component ke apne code mein kuch bhi ye nahi darsata ki ek collision hua. Asli visual nateeja chupchaap is baat par nirbhar karta hai ki kaunsi stylesheet samyog se page par aakhri load hui, ek implementation detail jo dono components ke apne logic se na-judi hai. CSS Modules ise sulajhata hai build tool khud ko ek class naam banaane dekar jo us khaas file ke liye guaranteed unique hai jahan se ye aayi, isliye ek developer apni source file mein wahi saadha, padhne-yogya \`.title\` likhte reh sakta hai jabki tool sunishchit karta hai ki asli compiled class naam kabhi ek doosri file mein samaan-naam-wali class se takra nahi sakta. Tailwind usi underlying samasya ko ek bilkul alag angle se sulajhaata hai: prati-component koi naya, custom class naam shuru mein hi ijaad karne ke bajaye, styling seedhe markup mein utility classes ki ek chhoti, shared, pehle-se-define-ki-gayi vocabulary compose karke darsaayi jaati hai, matlab do components ke liye samaan roop se chunne ke liye koi custom naam hai hi nahi, kyunki koi bhi bilkul ek custom naam nahi chun raha. CSS-in-JS libraries ise CSS Modules ke apne approach ke zyaada kareeb ek tarike se sulajhaati hain, JavaScript mein define kiye gaye har style kiye gaye component ke liye khaas taur par ek unique, scoped class naam banaate hue, jabki atirikt roop se us style ki asli values ko component ke apne props se dynamically ganne ki anumati bhi dete hue, jise CSS Modules seedhe support nahi karta bina apne atirikt conditional logic ke.',
      },
      {
        q: 'What is the specific, historical performance concern with CSS-in-JS libraries, and why is it not accurate to assume every CSS-in-JS library still has this cost today?',
        qHi: 'CSS-in-JS libraries ke saath khaas, historical performance chinta kya hai, aur ye maan lena sahi kyun nahi hai ki har CSS-in-JS library aaj bhi ye keemat rakhti hai?',
        a: 'Many early and widely-adopted CSS-in-JS libraries work by computing a component\'s actual CSS rules while the application is running in the browser, and then dynamically injecting those computed rules into the page\'s stylesheet at that same moment, specifically so that a style\'s value can depend on the component\'s own current props at render time. This runtime computation and injection is genuine, additional work that the browser must perform beyond what is required for either plain CSS or CSS Modules, both of which produce static CSS that a browser can parse and apply without any JavaScript needing to compute anything about the styles themselves first. On a sufficiently powerful device this additional runtime cost may be difficult to notice, but on lower-end hardware, or in a component that re-renders frequently with different prop-driven style values, this per-render styling computation can become a measurable, real performance cost specific to this approach, and this is the concern that has historically been raised against CSS-in-JS as a category. It is not accurate, however, to treat this as an immutable property of every library described as "CSS-in-JS," since several more recent libraries in this same category have specifically been built, or have evolved, to perform style extraction at BUILD time instead — analyzing a component\'s styles when the application is compiled, before it ever reaches a browser, and emitting plain, static CSS output much like CSS Modules produces, specifically to eliminate this runtime cost while keeping the same co-located, prop-aware authoring experience developers get from writing styles directly alongside their component\'s own JavaScript code. Because this is a genuine, current difference between specific libraries within the same broad category, and because the ecosystem in this area continues to evolve, whether a specific CSS-in-JS library currently performs runtime injection or build-time extraction is something worth checking directly in that library\'s own current documentation before adopting it for a performance-sensitive application, rather than assuming either answer based on the category name alone.',
        aHi: 'Kayi shuruaati aur widely-adopted CSS-in-JS libraries ek component ke asli CSS rules ganke kaam karti hain jabki application browser mein chal raha hota hai, aur phir un gane gaye rules ko usi pal page ki stylesheet mein dynamically inject karti hain, khaas taur par taaki ek style ki value component ke apne current props par render time par nirbhar kar sake. Ye runtime computation aur injection asli, atirikt kaam hai jo browser ko karna padta hai us se aage jo saadha CSS ya CSS Modules ke liye zaruri hai, dono jo static CSS banaate hain jise ek browser parse aur lagu kar sakta hai bina kisi JavaScript ko pehle styles ke baare mein kuch bhi ganne ki zaroorat ke. Ek kaafi shaktishaali device par ye atirikt runtime keemat notice karna mushkil ho sakta hai, par kam-shakti waale hardware par, ya ek component mein jo alag prop-driven style values ke saath baar-baar dobara render hota hai, ye prati-render styling computation is approach ke liye khaas ek maayne-yogya, asli performance keemat ban sakti hai, aur ye wo chinta hai jo historically CSS-in-JS ke khilaaf ek category ki tarah uthaayi gayi hai. Ye sahi nahi hai, halaanki, ise "CSS-in-JS" ki tarah describe ki gayi har library ki ek na-badalne-yogya property ki tarah treat karna, kyunki isi category mein kayi zyaada haaliya libraries khaas taur par banaayi gayi hain, ya vikasit hui hain, style extraction ko BUILD time par karne ke liye iske bajaye — component ke styles ka vishleshan karte hue jab application compile hota hai, isse pehle ki ye kabhi ek browser tak pahunche, aur saadha, static CSS output nikaalte hue bahut kuch CSS Modules ki tarah, khaas taur par is runtime keemat ko khatam karne ke liye us saath-rakhi, prop-aware authoring anubhav ko rakhte hue jo developers ko styles seedhe apne component ke JavaScript code ke saath likhne se milta hai. Kyunki ye isi vishaal category ke andar khaas libraries ke beech ek asli, current farak hai, aur kyunki is jagah mein ecosystem lagaataar vikasit hoti rehti hai, kya ek khaas CSS-in-JS library abhi runtime injection ya build-time extraction karti hai kuch hai jo us library ki apni current documentation mein seedhe check karne laayak hai ise ek performance-sensitive application ke liye apnaane se pehle, kisi bhi jawaab ko sirf category naam ke aadhaar par maanne ke bajaye.',
      },
    ],

    exercises: [
      {
        task: 'Build the broken example: two components, each with their own global .title class in a plain .css file. Import them in different orders and confirm the visual result changes depending on import order.',
        taskHi: 'Toota example banao: do components, har ek ka apna global \`.title\` class ek saadhi \`.css\` file mein. Unhe alag orders mein import karo aur confirm karo ki visual nateeja import order ke anusaar badalta hai.',
        hint: 'Simply swap the order of the two import statements and reload the page — no other code needs to change to observe the difference.',
        hintHi: 'Bas do import statements ka order badlo aur page reload karo — is farak ko dekhne ke liye kisi aur code ko badalne ki zaroorat nahi hai.',
      },
      {
        task: 'Fix the collision using CSS Modules, following this lesson\'s example. Inspect the actual rendered class names in devtools and confirm they are genuinely different between the two components.',
        taskHi: 'Is lesson ke example ka palan karte hue \`CSS Modules\` se collision theek karo. Devtools mein asli rendered class names inspect karo aur confirm karo ki wo dono components ke beech sach mein alag hain.',
        hint: 'Use the browser\'s Elements panel to look at the actual class attribute on each rendered element, comparing it against what you wrote in your own JSX.',
        hintHi: 'Har rendered element par asli class attribute dekhne ke liye browser ke Elements panel ka istemal karo, ise us se compare karte hue jo tumne apne JSX mein likha.',
      },
      {
        task: 'Rebuild the same two components using Tailwind\'s utility classes instead, with no custom CSS file at all. Compare the three approaches\' code side by side and write a sentence on which trade-off matters most for a project you have worked on.',
        taskHi: 'Wahi do components Tailwind ki utility classes se dobara banaao, koi custom CSS file bilkul bina. Teeno approaches ke code ki tulna ek saath karo aur ek vaakya likho ki ek project ke liye jispar tumne kaam kiya hai kaunsa trade-off sabse zyaada maayne rakhta hai.',
        hint: 'Focus specifically on how the className strings compare in length and readability between the Tailwind version and the CSS Modules version.',
        hintHi: 'Khaas taur par is baat par focus karo ki Tailwind version aur CSS Modules version ke beech \`className\` strings lambaayi aur padhne-yogyata mein kaise tulna karti hain.',
      },
    ],

    keyTakeaways: [
      'Plain CSS has no built-in scoping — two unrelated components defining the same global class name silently collide, with whichever stylesheet loads last winning everywhere on the page.',
      'CSS Modules solve this by having the build tool generate a class name guaranteed unique to the specific file it came from, while developers keep writing plain, readable class names in their own source.',
      'Tailwind avoids the collision problem from a different angle entirely: no custom class name is invented per component, so there is nothing for two components to accidentally share.',
      'CSS-in-JS libraries generate scoped class names similarly to CSS Modules while also letting a style\'s values respond directly to a component\'s own props, without extra conditional logic.',
      'Some CSS-in-JS libraries historically compute and inject styles at runtime, a real performance cost on lower-end devices — but several more recent libraries extract styles at build time instead, avoiding that cost.',
      'No single approach is objectively correct — large production codebases successfully use CSS Modules, Tailwind, and CSS-in-JS, and the right choice depends on a team\'s own priorities and constraints.',
    ],
    keyTakeawaysHi: [
      'Saadhe CSS mein koi built-in scoping nahi hai — do na-judi components jo wahi global class naam define karte hain chupchaap takraate hain, jo bhi stylesheet aakhri load hoti hai wo poore page par jeette hue.',
      'CSS Modules ise sulajhaate hain build tool ko ek class naam banaane dekar jo us khaas file ke liye guaranteed unique hai jahan se ye aayi, jabki developers apne source mein saadhe, padhne-yogya class names likhte rehte hain.',
      'Tailwind collision samasya ko ek bilkul alag angle se taalta hai: prati-component koi custom class naam ijaad nahi hota, isliye do components ke pas galti se share karne ke liye kuch nahi hai.',
      'CSS-in-JS libraries CSS Modules ki tarah scoped class names banaati hain jabki ek style ki values ko seedhe component ke apne props ka jawaab dene bhi deti hain, bina atirikt conditional logic ke.',
      'Kuch CSS-in-JS libraries historically runtime par styles ganti aur inject karti hain, kam-shakti waali devices par ek asli performance keemat — par kayi zyaada haaliya libraries iske bajaye build time par styles nikaalti hain, us keemat ko avoid karte hue.',
      'Koi ek approach objectively sahi nahi hai — bade production codebases safaltapoorvak CSS Modules, Tailwind, aur CSS-in-JS istemal karte hain, aur sahi chunaav ek team ki apni priorities aur limitations par nirbhar karta hai.',
    ],
  },
];
