import type { SeedQuestion } from './questions';

/**
 * Three.js and React Three Fiber interview questions.
 *
 * Weighted toward the answers that reveal production experience: draw calls
 * over triangle counts, manual GPU memory, delta time, and the accessibility
 * obligation that most 3D work simply does not meet.
 */
export const threejsQuestions: SeedQuestion[] = [
  {
    slug: 'three-q-what-is-threejs',
    category: 'Three.js',
    question: 'What is Three.js, and what does it give you over raw WebGL?',
    shortAnswer: 'A rendering library over WebGL. Raw WebGL needs hundreds of lines and two shader programs to draw one triangle; Three.js gives you scenes, cameras, materials and loaders.',
    shortAnswerHi: 'WebGL ke upar ek rendering library. Kacche WebGL mein ek triangle banane ke liye sau se zyada line aur do shader program lagte hain; Three.js scenes, cameras, materials aur loaders deta hai.',
    detailedAnswer: 'WebGL is the browser API for talking to the GPU, and it is deliberately low level — drawing a single triangle means writing and compiling two GLSL shaders, creating buffers, describing your vertex memory layout and issuing a draw call, and you still have no camera or lighting. Three.js provides the concepts you actually think in and compiles down to those WebGL calls. The important framing is what it is not: it is a rendering library, not a game engine, so there is no physics, audio, editor or asset pipeline — those are separate libraries you assemble, and knowing that in advance answers most "why does Three.js not have X" questions. The other shift worth naming is the mental model. A normal web app responds to events and sits idle between them; a 3D app runs a loop roughly sixty times a second where every frame has about sixteen milliseconds to do everything. Performance stops being "is the page fast" and becomes "did this frame finish in time", and missing that budget shows up as stutter, which people notice far more readily than slowness.',
    detailedAnswerHi: 'WebGL browser ka wo API hai jo GPU se baat karta hai, aur wo jaan-boojh kar neeche ke darje ka hai — ek triangle banane ka matlab hai do GLSL shaders likhna aur compile karna, buffers banana, vertex memory ka layout batana aur ek draw call bhejna, aur uske baad bhi na camera hai na lighting. Three.js wo vichaar deta hai jinme aap sach mein sochte ho aur neeche jaakar wahi WebGL calls banata hai. Zaroori baat ye hai ki ye kya nahi hai: ye rendering library hai, game engine nahi, isliye na physics hai na audio, editor ya asset pipeline — wo alag libraries hain jo aap jodte ho, aur ye pehle se jaanna "Three.js mein X kyun nahi" wale zyadatar sawaal hal kar deta hai. Doosra badlav ginane layak soch ka hai. Aam web app events par jawab deta hai aur beech mein chup baithta hai; 3D app ek loop chalata hai jo ek second mein lagbhag saath baar chalta hai aur har frame ke paas sab kuch karne ko lagbhag solah milliseconds hain. Performance "page tez hai kya" nahi rehti aur "ye frame waqt par khatam hua kya" ban jati hai, aur budget chookna hakla-hat ban kar dikhta hai, jo logon ko dheemepan se kahin jaldi dikhti hai.',
    followUps: ['Is Three.js a game engine?', 'Why is 16ms the number that matters?', 'What is WebGPU?'],
    difficulty: 'EASY',
    tags: ['threejs', '3d', 'must-know'],
  },
  {
    slug: 'three-q-nothing-renders',
    category: 'Three.js',
    question: 'Nothing appears on screen. How do you debug it?',
    shortAnswer: 'Run a checklist: did you call render, is the object inside near/far, is the camera pointing at it, is there a light, and is it behind or on top of the camera.',
    shortAnswerHi: 'Ek suchi chalao: render bulaya tha, object near/far ke andar hai, camera uski taraf hai, koi light hai, aur wo camera ke peeche ya us par to nahi.',
    detailedAnswer: 'Five checks catch almost every case. First, was render actually called — with setAnimationLoop or otherwise. Second, is the object inside the camera\'s near and far planes; anything closer than near or further than far is not drawn at all, and this is the single most common cause of an invisible object. Third, is the camera pointing at it, remembering that a camera looks down negative Z by default. Fourth, is there a light in the scene, because MeshStandardMaterial renders pure black with nothing shining on it and people routinely conclude the model failed to load. Fifth, is the object behind the camera or at exactly the same position. A sixth worth adding is material side: a plane viewed from behind is invisible unless you set DoubleSide. Running that list is consistently faster than reading the code, because each item is a yes-or-no check rather than a hypothesis. A related trap is setting near to something like 0.0001 and far to a million; depth precision is spread across that range, so an extreme ratio produces z-fighting, where surfaces flicker because the renderer cannot resolve which is in front.',
    detailedAnswerHi: 'Paanch jaanch lagbhag har case pakad leti hain. Pehla, render sach mein bulaya gaya tha — setAnimationLoop se ya kisi aur tareeke se. Doosra, object camera ke near aur far planes ke andar hai; near se paas ya far se door ki cheez banti hi nahi, aur adrishya object ki sabse aam wajah yahi hai. Teesra, camera uski taraf dekh raha hai, ye yaad rakhte hue ki camera default mein negative Z ki taraf dekhta hai. Chautha, scene mein koi light hai, kyunki MeshStandardMaterial par kuch chamak na rahe to wo poora kaala banta hai aur log aksar maan lete hain ki model load hi nahi hua. Paanchva, object camera ke peeche ya theek usi jagah to nahi. Chhatha jodne layak hai material ka side: plane peeche se dekhne par tab tak adrishya hai jab tak DoubleSide na lagao. Ye suchi chalana code padhne se lagatar tez hai, kyunki har cheez haan-ya-na wali jaanch hai, koi anuman nahi. Isse judi ek trap hai near ko 0.0001 aur far ko das lakh karna; depth ki precision us range par phailti hai, isliye bahut bada anupaat z-fighting deta hai, jisme satahein jhilmilaati hain kyunki renderer tay nahi kar pata ki aage kaun hai.',
    followUps: ['What causes z-fighting?', 'Why is a MeshStandardMaterial object black?', 'What does DoubleSide cost?'],
    difficulty: 'EASY',
    tags: ['threejs', '3d', 'debugging', 'must-know'],
  },
  {
    slug: 'three-q-draw-calls',
    category: 'Three.js',
    question: 'A scene is running slowly. Why is "reduce the polygon count" often the wrong advice?',
    shortAnswer: 'Draw calls usually matter more than triangles. One 100k-triangle mesh often renders faster than a thousand 100-triangle meshes, because each unique geometry+material pair is a separate instruction with CPU overhead.',
    shortAnswerHi: 'Triangles se zyada aksar draw calls matter karte hain. Ek 1 lakh triangle wala mesh aksar hazaar 100-triangle wale meshes se tez banta hai, kyunki geometry+material ka har alag jodda alag nirdesh hai jiska CPU kharch hai.',
    detailedAnswer: 'Every unique combination of geometry and material is one instruction to the GPU, and each carries CPU-side overhead, so a thousand separate cubes is a thousand draw calls while a thousand instanced cubes is one. That is why the polygon count is frequently the wrong number to look at. The highest-value fixes, in order, are instancing for repeated geometry, merging static geometry that never moves independently, sharing materials so meshes can batch, and level of detail for distant objects. Before any of that, though, measure: check renderer.info.render.calls rather than guessing, and work out whether you are CPU-bound with too many draw calls and heavy per-frame JavaScript, or GPU-bound with too many pixels and expensive shaders. Reducing triangles when you are fill-rate limited changes nothing at all, and that is a very common wasted afternoon. The other half of performance work is memory, which surprises people from ordinary web development: GPU resources are not garbage collected, so removing a mesh from the scene frees nothing and you must dispose geometries, materials and textures explicitly. Watching renderer.info.memory climb steadily is how you spot the leak, and in a single-page app with several 3D views it ends with the tab crashing.',
    detailedAnswerHi: 'Geometry aur material ka har alag mel GPU ko ek nirdesh hai, aur har ek par CPU ki taraf kharch hai, isliye hazaar alag cube hazaar draw calls hain jabki hazaar instanced cube ek. Isiliye polygon ki ginti aksar galat number hoti hai dekhne ke liye. Sabse keemti hal, kram mein, hain dohrayi gayi geometry ke liye instancing, aisi sthir geometry jodna jo alag se kabhi nahi hilti, materials saanjhe karna taaki meshes batch ho sakein, aur door ke objects ke liye level of detail. Par in sab se pehle naapo: andaza lagane ki jagah renderer.info.render.calls dekho, aur tay karo ki aap CPU-bound ho jisme bahut draw calls aur har frame bhaari JavaScript hai, ya GPU-bound jisme bahut pixels aur mehnge shaders hain. Fill-rate ki seema par triangles kam karne se kuch nahi badalta, aur ye bahut aam barbaad dopahar hai. Performance kaam ka doosra aadha memory hai, jo aam web development se aane walon ko chaunkata hai: GPU ke saadhan garbage collect nahi hote, isliye scene se mesh hataane se kuch khaali nahi hota aur aapko geometries, materials aur textures saaf-saaf dispose karne padte hain. renderer.info.memory ka lagatar badhna hi leak pakadne ka tareeka hai, aur kai 3D views wale single-page app mein iska ant tab ke crash hone se hota hai.',
    codeExample: `// 1000 objects, ONE draw call
const mesh = new THREE.InstancedMesh(geometry, material, 1000);
console.log(renderer.info.render.calls);       // measure, do not guess
console.log(renderer.info.memory.geometries);  // only climbing? that is the leak`,
    followUps: ['What is instancing?', 'Why is GPU memory not garbage collected?', 'How do you tell CPU-bound from GPU-bound?'],
    difficulty: 'HARD',
    tags: ['threejs', '3d', 'performance', 'must-know'],
  },
  {
    slug: 'three-q-delta-time',
    category: 'Three.js',
    question: 'Why must animation be multiplied by delta time?',
    shortAnswer: 'Otherwise speed depends on the monitor. A 144Hz display runs the same code 2.4x faster than a 60Hz one — and you never see it, because your own screen is fine.',
    shortAnswerHi: 'Warna raftaar monitor par nirbhar ho jati hai. 144Hz display wahi code 60Hz se 2.4 guna tez chalati hai — aur aapko kabhi dikhta nahi, kyunki aapki apni screen theek hai.',
    detailedAnswer: 'Writing rotation.y += 0.01 means "advance this much per frame", and the number of frames per second varies by display, so the same code runs more than twice as fast on a 144Hz monitor as on a 60Hz one. Writing rotation.y += 1.5 * delta means "advance this much per second" and behaves identically everywhere. This is the most common animation bug in the field, and the reason it ships so reliably is that it is invisible on the developer\'s own machine. The companion rule is to clamp delta: when a user switches tabs the loop pauses, and on return the elapsed time could be thirty seconds, so anything integrating over it teleports across the scene or explodes — capping at around 0.1 prevents that. Two more points belong to the loop. Order matters: update the camera before rendering, not after, or you are permanently displaying where the camera was last frame, which is a small persistent lag that is maddening to diagnose. And consistency matters more than peak frame rate: a steady 30fps feels better than a 60 that regularly drops to 45, which is why adaptive quality that lowers resolution under load works so well in practice.',
    detailedAnswerHi: 'rotation.y += 0.01 likhne ka matlab hai "har frame itna aage badho", aur ek second mein kitne frame hain ye display par nirbhar hai, isliye wahi code 144Hz monitor par 60Hz se do guna se zyada tez chalta hai. rotation.y += 1.5 * delta likhne ka matlab hai "ek second mein itna aage badho" aur ye har jagah ek jaisa chalta hai. Maidan mein sabse aam animation bug yahi hai, aur ye itni bharose se ship isliye hota hai kyunki developer ki apni machine par ye dikhta hi nahi. Saathi niyam delta ko baandhna hai: user tab badle to loop rukta hai, aur laut ne par beeta samay tees second ho sakta hai, isliye us par jodne wali har cheez scene ke paar kood jati hai ya phat jati hai — lagbhag 0.1 par baandhna ise rokta hai. Do aur baatein loop se judi hain. Kram matter karta hai: camera ko render se pehle update karo, baad mein nahi, warna aap hamesha ye dikha rahe ho ki camera pichhle frame kahan tha, jo ek chhota tikta hua lag hai aur pakadna pagal kar deta hai. Aur sabse ooncha frame rate se zyada ek-jaisapan matter karta hai: sthir 30fps us 60 se behtar lagta hai jo baar-baar 45 par girta ho, aur isiliye load par resolution girane wali adaptive quality asal mein itni achhi chalti hai.',
    followUps: ['Why clamp delta?', 'Why update the camera before rendering?', 'Why does steady 30fps beat unstable 60?'],
    difficulty: 'MEDIUM',
    tags: ['threejs', '3d', 'animation', 'must-know'],
  },
  {
    slug: 'three-q-r3f-state',
    category: 'Three.js',
    question: 'In React Three Fiber, why must per-frame animation avoid React state?',
    shortAnswer: 'Setting state 60 times a second runs React\'s full reconciliation every frame. useFrame runs outside React, so mutating a ref there costs nothing.',
    shortAnswerHi: 'Ek second mein 60 baar state set karna har frame React ki poori reconciliation chalata hai. useFrame React ke bahar chalta hai, isliye wahan ref badalna kuch nahi leta.',
    detailedAnswer: 'R3F is a React renderer for Three.js, so a mesh element creates a real THREE.Mesh and there is no performance penalty for the abstraction itself. The penalty comes from misusing React. Calling setState inside useFrame triggers the entire reconciliation pipeline sixty times a second, and that machinery is designed for occasional user-driven updates rather than a continuous loop. Because useFrame runs outside React\'s render cycle, mutating a ref inside it — ref.current.rotation.y += delta — costs nothing and React never finds out. The useful mental split is that React state is for things that change occasionally, such as which model is loaded or whether a panel is open, while refs and direct mutation are for things that change every frame. This is the single most common R3F performance mistake. Two related points worth mentioning: R3F automatically disposes geometries and materials it created when a component unmounts, which removes the most common Three.js memory leak, though not for objects you created imperatively; and Canvas creates its own React root, so context from outside does not automatically cross into it and providers often need repeating inside, which surprises people the first time state comes back undefined.',
    detailedAnswerHi: 'R3F Three.js ke liye React renderer hai, isliye mesh element asli THREE.Mesh banata hai aur khud is abstraction ka koi performance nuksaan nahi. Nuksaan React ke galat istemal se aata hai. useFrame ke andar setState bulana ek second mein saath baar poori reconciliation chalata hai, aur wo machinery kabhi-kabhi hone wale user ke badlavon ke liye bani hai, lagatar chalte loop ke liye nahi. useFrame React ke render cycle ke bahar chalta hai, isliye uske andar ref badalna — ref.current.rotation.y += delta — kuch nahi leta aur React ko pata hi nahi chalta. Kaam ka batwara ye hai ki React state un cheezon ke liye hai jo kabhi-kabhi badalti hain, jaise kaunsa model load hai ya panel khula hai, jabki refs aur seedha badlav un cheezon ke liye hain jo har frame badalti hain. R3F ki sabse aam performance galti yahi hai. Do judi baatein: R3F apne banaye geometries aur materials component unmount hone par apne aap dispose karta hai, jo Three.js ka sabse aam memory leak hata deta hai, halanki us cheez ke liye nahi jo aapne imperative tareeke se banayi; aur Canvas apna React root banata hai, isliye bahar ka context apne aap andar nahi jata aur providers ko aksar andar dohrana padta hai, jo pehli baar state undefined aane par chaunkata hai.',
    codeExample: `useFrame(() => setY(v => v + 1));                  // ❌ 60 re-renders/sec
useFrame((_, d) => { ref.current.rotation.y += d; }); // ✅ no re-render`,
    followUps: ['Is R3F slower than plain Three.js?', 'What does R3F dispose automatically?', 'Why does context not cross the Canvas boundary?'],
    difficulty: 'MEDIUM',
    tags: ['threejs', 'r3f', 'react', 'must-know'],
  },
  {
    slug: 'three-q-accessibility',
    category: 'Three.js',
    question: 'What accessibility problem does a 3D canvas create, and how do you solve it?',
    shortAnswer: 'A canvas is invisible to screen readers and unreachable by keyboard — not poorly described, absent. Every meaningful interaction must be mirrored in real DOM.',
    shortAnswerHi: 'Screen reader ke liye canvas adrishya hai aur keyboard ki pahunch se bahar — bura bataya gaya nahi, hai hi nahi. Har matlab wale interaction ko asli DOM mein bhi rakhna hoga.',
    detailedAnswer: 'Everything inside a canvas is a single opaque element as far as assistive technology is concerned, so objects in the scene do not exist for a screen reader and nothing inside can be reached with a keyboard. The consequence is concrete: if a product specification is only visible by rotating a model, or a hotspot is only clickable in 3D, then for some users that information does not exist at all. The fix is not clever — provide the same information and the same actions in ordinary DOM. drei\'s Html component renders real DOM positioned in 3D space, which is often the cleanest approach, and controls outside the canvas work equally well. Two related obligations belong here. Respect prefers-reduced-motion, because continuous camera movement genuinely causes nausea for some people, which makes it a health matter rather than a preference. And always have a fallback: some devices have no WebGL, some GPUs are blocklisted, and contexts get lost on driver updates or mobile app switching, so listen for webglcontextlost and show a static image with an explanation, because a blank grey rectangle is the worst available outcome. The judgement underneath all of it is worth stating: ask whether the 3D serves the user or serves the demo, because a configurator earns its cost while a rotating logo costs fifteen megabytes and helps nobody.',
    detailedAnswerHi: 'Sahayak technology ke liye canvas ke andar ka sab kuch ek band element hai, isliye scene ke objects screen reader ke liye hain hi nahi aur uske andar kuch bhi keyboard se nahi chhua ja sakta. Natija thos hai: agar product ki tafseel sirf model ghuma kar dikhti hai, ya koi hotspot sirf 3D mein click hota hai, to kuch users ke liye wo jaankari hai hi nahi. Hal chalak nahi hai — wahi jaankari aur wahi kaam aam DOM mein bhi do. drei ka Html component 3D jagah mein rakha asli DOM banata hai, jo aksar sabse saaf tareeka hai, aur canvas ke bahar rakhe controls bhi utne hi achhe chalte hain. Do judi zimmedariyan yahin hain. prefers-reduced-motion ka maan rakho, kyunki lagatar camera hilna kuch logon ko sach mein matli laata hai, aur isse ye pasand nahi balki sehat ki baat ban jati hai. Aur fallback hamesha rakho: kuch devices mein WebGL nahi hai, kuch GPU rok diye gaye hain, aur driver update ya mobile par app badalne par context kho jate hain, isliye webglcontextlost suno aur safai ke saath sthir image dikhao, kyunki khaali slate rang ka chaukor sabse bura uplabdh natija hai. In sabke neeche ka faisla kehne layak hai: poochho ki 3D user ke kaam aa raha hai ya demo ke, kyunki configurator apni keemat kamata hai jabki ghoomta logo pandrah megabyte leta hai aur kisi ke kaam nahi aata.',
    followUps: ['What does drei\'s Html component solve?', 'Why is prefers-reduced-motion a health matter?', 'How do you handle a lost WebGL context?'],
    difficulty: 'HARD',
    tags: ['threejs', '3d', 'accessibility', 'must-know'],
  },
  {
    slug: 'three-q-assets',
    category: 'Three.js',
    question: 'What makes 3D pages slow to load, and what would you do about it?',
    shortAnswer: 'Assets. A 3D page is often twenty times heavier than a normal one. Compress every model, use GPU-compressed textures, lazy load, and show real progress.',
    shortAnswerHi: 'Assets. 3D page aksar aam page se bees guna bhaari hota hai. Har model compress karo, GPU-compressed textures use karo, lazy load karo, aur asli pragati dikhao.',
    detailedAnswer: 'An uncompressed glTF model is easily fifty megabytes where the compressed version is two, so running everything through gltf-transform or gltfpack with Draco or Meshopt is a build step rather than an optimisation, and skipping it is the difference between loading in one second and twelve. Textures deserve separate attention because the format matters differently for download size and for memory: a JPEG is small on the wire and decompresses to full size on the GPU, whereas KTX2 stays compressed in GPU memory, and a single 4K texture is roughly sixty-four megabytes there for one map on one object when 1K is usually indistinguishable. Beyond size, the loading experience is the actual product problem, because a blank screen while assets download is the most common reason people leave: show a real progress bar rather than a spinner, since a bar sets an expectation, render something immediately such as a placeholder image, and load the hero object before decoration. Two practices make this stick — lazy load the scene so nothing downloads until the user scrolls to it, and set an asset size budget enforced in CI, because asset weight otherwise creeps up quietly with every addition. Finally, remember that removing a model from the scene frees no GPU memory; traverse and dispose geometries, materials and textures, or navigating between 3D views slowly fills the card until the tab dies.',
    detailedAnswerHi: 'Bina compress ka glTF model aaram se pachas megabyte hota hai jabki compress kiya do, isliye sab kuch gltf-transform ya gltfpack se Draco ya Meshopt ke saath guzarna optimisation nahi build ka kadam hai, aur ise chhodna ek second aur baarah second mein load hone ka farak hai. Textures ko alag dhyan chahiye kyunki format download ke size aur memory ke liye alag matter karta hai: JPEG taar par chhota hai aur GPU par poore size mein khul jata hai, jabki KTX2 GPU memory mein bhi compressed rehta hai, aur ek 4K texture wahan ek object ke ek map ke liye lagbhag chausath megabyte hai jabki 1K mein aksar farak dikhta hi nahi. Size ke alawa, loading ka anubhav hi asli product samasya hai, kyunki assets ke download ke dauran khaali screen logon ke chale jaane ki sabse aam wajah hai: spinner ki jagah asli progress bar dikhao, kyunki bar ek ummeed banati hai, turant kuch dikhao jaise placeholder image, aur sajawat se pehle mukhya object load karo. Do abhyas ise pakka karte hain — scene ko lazy load karo taaki user ke scroll karne tak kuch download na ho, aur CI mein lagu hone wala asset size ka budget rakho, kyunki warna asset ka wazan har jodne ke saath chupchaap badhta rehta hai. Aakhir mein yaad rakho ki scene se model hataane se GPU memory khaali nahi hoti; traverse karke geometries, materials aur textures dispose karo, warna 3D views ke beech ghoomna dheere-dheere card bhar deta hai jab tak tab mar na jaye.',
    followUps: ['Why does KTX2 matter differently from JPEG?', 'Why a progress bar rather than a spinner?', 'Why does removing a model not free memory?'],
    difficulty: 'MEDIUM',
    tags: ['threejs', '3d', 'assets', 'performance'],
  },
  {
    slug: 'three-q-materials-lighting',
    category: 'Three.js',
    question: 'A MeshStandardMaterial object renders pure black. Why, and what else affects how a scene looks?',
    shortAnswer: 'There is no light — black is what unlit looks like. And for PBR materials an environment map usually does more than any number of lights.',
    shortAnswerHi: 'Koi light nahi hai — bina light ke aisa hi dikhta hai. Aur PBR materials ke liye environment map aksar kitni bhi lights se zyada karta hai.',
    detailedAnswer: 'MeshStandardMaterial is physically based, so with nothing shining on it the correct result is black, and almost everyone concludes the model failed to load the first time. Beyond adding a light, the single biggest improvement available is usually an environment map: metals and glossy surfaces reflect their surroundings, so without an environment they look flat no matter how many lights you add, and loading an HDR into scene.environment often makes a scene look dramatically better with fewer lights rather than more. On materials themselves, PBR describes surfaces by roughness and metalness, and metalness is nearly always zero or one because real materials are metal or they are not, with intermediate values usually a mistake. Two more practical points: sharing one geometry and one material across many meshes matters because each unique material generally means another draw call, so creating a new material per mesh is a common and expensive habit; and transparency is genuinely awkward because setting transparent true moves objects into a separately sorted pass where overlapping surfaces can sort incorrectly, so for hard cutouts like a leaf or a fence, alphaTest keeps the object in the opaque pass and avoids the problem entirely. Finally, tone mapping and correct colour space are easy to skip and leave everything looking washed out in a way that is hard to name.',
    detailedAnswerHi: 'MeshStandardMaterial physically based hai, isliye us par kuch chamak na rahe to sahi natija kaala hai, aur pehli baar lagbhag har koi maan leta hai ki model load hi nahi hua. Light jodne ke alawa, aam taur par uplabdh sabse bada sudhaar environment map hai: metals aur chamakdaar satahein apne aas-paas ko darshati hain, isliye bina environment ke wo chapti dikhti hain chahe kitni bhi lights jodo, aur scene.environment mein HDR load karna aksar scene ko kam lights ke saath kahin behtar bana deta hai, zyada ke saath nahi. Khud materials par, PBR satah ko roughness aur metalness se batata hai, aur metalness lagbhag hamesha zero ya ek hota hai kyunki asli materials ya metal hain ya nahi, aur beech ki values aksar galti hoti hain. Do aur practical baatein: ek geometry aur ek material kai meshes mein saanjha karna matter karta hai kyunki har alag material aam taur par ek aur draw call hai, isliye har mesh ke liye naya material banana aam aur mehngi aadat hai; aur transparency sach mein ajeeb hai kyunki transparent true karne se objects alag sorted pass mein chale jate hain jahan ek doosre par chadhti satahein galat sort ho sakti hain, isliye patte ya baad jaise sakht cutout ke liye alphaTest object ko opaque pass mein rakhta hai aur samasya poori tarah bacha leta hai. Aakhir mein, tone mapping aur sahi colour space aasani se chhoot jate hain aur sab kuch aise dhula-dhula chhod dete hain jise naam dena mushkil hai.',
    followUps: ['Why does an environment map matter more than extra lights?', 'When would you use alphaTest instead of transparent?', 'Why is metalness almost always 0 or 1?'],
    difficulty: 'MEDIUM',
    tags: ['threejs', '3d', 'materials', 'lighting'],
  },
];
