import type { Diff } from './topics-shared';

export interface SeedQuestion {
  slug: string;
  category: string;
  question: string;
  shortAnswer: string;
  shortAnswerHi: string;
  detailedAnswer: string;
  detailedAnswerHi: string;
  codeExample?: string;
  followUps: string[];
  difficulty: Diff;
  tags: string[];
}

/** Rapid-fire bank used by the Interview Questions page and the mock interview. */
export const interviewQuestions: SeedQuestion[] = [
  /* --------------------------------- JavaScript --------------------------------- */
  {
    slug: 'js-var-let-const',
    category: 'JavaScript',
    question: 'What is the difference between var, let and const?',
    shortAnswer: 'var is function-scoped and hoisted as undefined; let and const are block-scoped and sit in the temporal dead zone until declared. const blocks reassignment, not mutation.',
    shortAnswerHi: 'var function-scoped hai aur undefined ke saath hoist hota hai; let aur const block-scoped hain aur declare hone tak temporal dead zone mein rehte hain. const reassignment rokta hai, mutation nahi.',
    detailedAnswer: 'var ignores block boundaries, so a var inside an if or for leaks to the whole function, and reading it early gives undefined. let and const are limited to the nearest block and throw a ReferenceError if read before their declaration line — the temporal dead zone. const only freezes the binding: const arr = [] still allows arr.push(1). In practice: default to const, use let when reassignment is genuinely needed, avoid var in new code.',
    detailedAnswerHi: 'var block boundaries ko ginta hi nahi, isliye if ya for ke andar ka var poore function mein leak ho jata hai, aur pehle padho to undefined milta hai. let aur const sirf apne nazdeeki block tak hain aur declaration line se pehle padhne par ReferenceError dete hain — yahi temporal dead zone hai. const sirf binding freeze karta hai: const arr = [] ke baad bhi arr.push(1) chalta hai. Practically: default const, zaroorat par let, naye code mein var nahi.',
    codeExample: `for (var i = 0; i < 3; i++) setTimeout(() => console.log(i));  // 3 3 3
for (let j = 0; j < 3; j++) setTimeout(() => console.log(j));  // 0 1 2`,
    followUps: ['What is the temporal dead zone?', 'Does const make an object immutable?', 'Why does the var loop print 3 three times?'],
    difficulty: 'EASY',
    tags: ['scope', 'basics'],
  },
  {
    slug: 'js-closure-definition',
    category: 'JavaScript',
    question: 'What is a closure? Give a practical use.',
    shortAnswer: 'A function bundled with the lexical environment it was defined in, so outer variables stay alive after the outer function returns. Used for private state, factories and memoisation.',
    shortAnswerHi: 'Function plus wo lexical environment jisme wo define hua tha — outer function return hone ke baad bhi outer variables zinda rehte hain. Private state, factories aur memoisation mein use hota hai.',
    detailedAnswer: 'When an inner function references a variable from an enclosing scope, the engine keeps that scope alive as long as the inner function is reachable. Each call to the outer function creates an independent environment, which is why two counters made by the same factory do not share state. Practical uses: private variables (there is no other way pre-#fields), memoisation caches, once() wrappers, and every React hook callback — which is also where "stale closure" bugs come from, when a callback captures an old render value.',
    detailedAnswerHi: 'Jab inner function bahar ke scope ka variable use karta hai, engine us scope ko tab tak zinda rakhta hai jab tak inner function pahunch mein hai. Outer function ka har call ek alag environment banata hai, isliye ek hi factory se bane do counters state share nahi karte. Practical use: private variables, memoisation cache, once() wrapper, aur har React hook callback — aur wahin se "stale closure" bugs aate hain jab callback purane render ki value pakad leta hai.',
    codeExample: `function once(fn) {
  let called = false, result;
  return (...args) => (called ? result : ((called = true), (result = fn(...args))));
}`,
    followUps: ['How do closures cause memory leaks?', 'What is a stale closure in React?', 'Implement memoise using a closure.'],
    difficulty: 'MEDIUM',
    tags: ['closures', 'must-know'],
  },
  {
    slug: 'js-event-loop-order',
    category: 'JavaScript',
    question: 'Explain the event loop. What is the output order of sync code, setTimeout and Promise.then?',
    shortAnswer: 'Sync first, then all microtasks (promises), then macrotasks (setTimeout). Microtasks drain completely between every macrotask.',
    shortAnswerHi: 'Pehle sync, phir saare microtasks (promises), phir macrotasks (setTimeout). Har macrotask ke beech microtasks poori tarah khaali hote hain.',
    detailedAnswer: 'JavaScript has one call stack. The current script runs to completion first. Then the entire microtask queue drains — promise continuations, queueMicrotask, and in Node process.nextTick ahead of them. Only then does one macrotask run (a timer or I/O callback), after which microtasks drain again. That is why a promise resolved after a setTimeout(…, 0) still logs first. A microtask that schedules another microtask can starve the loop and block rendering entirely.',
    detailedAnswerHi: 'JavaScript mein ek hi call stack hai. Pehle current script poora chalta hai. Phir poori microtask queue khaali hoti hai — promise continuations, queueMicrotask, aur Node mein unse pehle process.nextTick. Uske baad hi ek macrotask chalta hai (timer ya I/O callback), aur phir se microtasks khaali hote hain. Isiliye setTimeout(…, 0) ke baad resolve hua promise bhi pehle log hota hai. Agar microtask aur microtask schedule karta rahe to loop bhookhi reh jati hai aur rendering ruk jati hai.',
    codeExample: `console.log(1);
setTimeout(() => console.log(4));
Promise.resolve().then(() => console.log(3));
console.log(2);   // → 1 2 3 4`,
    followUps: ['What is microtask starvation?', 'How do Node phases differ from the browser?', 'Where does process.nextTick fit?'],
    difficulty: 'HARD',
    tags: ['event-loop', 'async', 'must-know'],
  },
  {
    slug: 'js-this-binding',
    category: 'JavaScript',
    question: 'How is `this` determined? Why do arrow functions behave differently?',
    shortAnswer: 'For regular functions `this` is set at call time (new > bind/call/apply > obj.method() > default). Arrow functions have no own `this` and inherit it from the defining scope.',
    shortAnswerHi: 'Normal functions mein `this` call ke waqt tay hota hai (new > bind/call/apply > obj.method() > default). Arrow functions ka apna `this` nahi hota, wo define hone wale scope se lete hain.',
    detailedAnswer: 'The four binding rules apply in priority order: new binding, explicit binding via call/apply/bind, implicit binding through a receiver object, and the default (undefined in strict mode, globalThis otherwise). Because it is decided at the call site, extracting a method (const f = obj.method) loses the receiver. Arrow functions close over the surrounding this lexically, which is why they fix callbacks in setTimeout and array methods — and also why they must never be used as object methods or constructors.',
    detailedAnswerHi: 'Chaar binding rules priority order mein lagte hain: new binding, call/apply/bind se explicit binding, receiver object se implicit binding, aur default (strict mode mein undefined, warna globalThis). Kyunki ye call site par tay hota hai, method nikaal lene par (const f = obj.method) receiver kho jata hai. Arrow functions aas-paas ke this ko lexically pakad lete hain, isliye setTimeout aur array methods ke callbacks theek ho jaate hain — aur isi wajah se unhe object method ya constructor kabhi nahi banana chahiye.',
    followUps: ['Difference between call, apply and bind?', 'Implement Function.prototype.bind.', 'Why can an arrow function not be a constructor?'],
    difficulty: 'MEDIUM',
    tags: ['this', 'must-know'],
  },
  {
    slug: 'js-promise-combinators',
    category: 'JavaScript',
    question: 'Difference between Promise.all, allSettled, race and any?',
    shortAnswer: 'all: fails fast on the first rejection. allSettled: waits for everything and reports each outcome. race: first to settle either way. any: first success, rejects only if all fail.',
    shortAnswerHi: 'all: pehli rejection par turant fail. allSettled: sabka wait karke har result batata hai. race: jo pehle settle ho (success ya failure). any: pehla success, sab fail hone par hi reject.',
    detailedAnswer: 'Promise.all resolves with an array in input order but rejects the moment any input rejects — the other results are discarded, so use it only when partial results are worthless. allSettled never rejects; it gives {status, value|reason} per entry, which is what you want for a dashboard where one failing widget should not blank the page. race is useful for timeouts. any ignores failures until every input has failed, then rejects with an AggregateError.',
    detailedAnswerHi: 'Promise.all input order mein array deta hai par koi bhi input reject hote hi reject ho jata hai — baaki results phenk diye jaate hain, isliye ise tabhi use karo jab adhoore results bekaar hon. allSettled kabhi reject nahi karta; har entry ke liye {status, value|reason} deta hai — dashboard ke liye yahi sahi hai jahan ek widget fail hone par poora page blank nahi hona chahiye. race timeouts ke liye kaam ka hai. any tab tak failures ignore karta hai jab tak sab fail na ho jayein, phir AggregateError ke saath reject karta hai.',
    followUps: ['Implement Promise.all yourself.', 'How do you add a timeout to a promise?', 'What is an unhandled rejection?'],
    difficulty: 'MEDIUM',
    tags: ['promise', 'async'],
  },
  {
    slug: 'js-shallow-deep-copy',
    category: 'JavaScript',
    question: 'Shallow vs deep copy — how do you deep clone an object?',
    shortAnswer: 'Spread and Object.assign copy one level; nested objects stay shared. Use structuredClone for a real deep copy.',
    shortAnswerHi: 'Spread aur Object.assign sirf ek level copy karte hain; nested objects share hi rehte hain. Asli deep copy ke liye structuredClone use karo.',
    detailedAnswer: 'A shallow copy duplicates top-level properties but copies references for nested values, so mutating a nested object affects both copies. structuredClone handles nested structures, Dates, Maps, Sets and cycles. JSON.parse(JSON.stringify(x)) is the old trick but silently loses undefined, functions, Symbols, and converts Dates to strings — and throws on circular references. In React this matters because mutating nested state that was "copied" with spread still mutates the original, so the component may not re-render.',
    detailedAnswerHi: 'Shallow copy top-level properties duplicate karti hai par nested values ki reference hi copy hoti hai, isliye nested object badalne par dono copies badal jaati hain. structuredClone nested structures, Dates, Maps, Sets aur cycles sambhal leta hai. JSON.parse(JSON.stringify(x)) purana jugaad hai par ye undefined, functions, Symbols chupchaap kho deta hai aur Dates ko string bana deta hai — aur circular reference par error deta hai. React mein ye isliye matter karta hai kyunki spread se "copy" ki gayi nested state ko mutate karna asal mein original ko hi mutate karta hai, aur component re-render nahi hota.',
    followUps: ['What does JSON.stringify lose?', 'How do you clone a Map?', 'Why does React not re-render after a nested mutation?'],
    difficulty: 'EASY',
    tags: ['objects', 'copy'],
  },
  {
    slug: 'js-debounce-throttle',
    category: 'JavaScript',
    question: 'Debounce vs throttle?',
    shortAnswer: 'Debounce waits until activity stops before firing once. Throttle fires at most once per interval during continuous activity.',
    shortAnswerHi: 'Debounce activity rukne ka intezar karke ek baar chalta hai. Throttle lagatar activity ke dauraan har interval mein zyada se zyada ek baar chalta hai.',
    detailedAnswer: 'Debounce resets its timer on every event, so the callback runs only after a quiet period — right for search-as-you-type, autosave and resize-complete. Throttle guarantees a steady rate regardless of how many events arrive — right for scroll handlers, mousemove and analytics pings, where you want regular updates rather than one final one. Choosing wrong is visible: a throttled search box fires needless requests mid-typing; a debounced scroll handler updates nothing until the user stops scrolling.',
    detailedAnswerHi: 'Debounce har event par apna timer reset karta hai, isliye callback tabhi chalta hai jab thodi der shaanti ho — search-as-you-type, autosave aur resize-complete ke liye sahi. Throttle ek steady rate deta hai chahe kitne bhi events aayein — scroll handlers, mousemove aur analytics pings ke liye sahi, jahan regular updates chahiye, sirf aakhri nahi. Galat chunne par farq dikhta hai: throttled search box typing ke beech bekaar requests bhejta hai; debounced scroll handler tab tak kuch update nahi karta jab tak user scroll rok na de.',
    codeExample: `const debounce = (fn, ms) => { let t; return (...a) => { clearTimeout(t); t = setTimeout(() => fn(...a), ms); }; };
const throttle = (fn, ms) => { let last = 0; return (...a) => { const now = Date.now(); if (now - last >= ms) { last = now; fn(...a); } }; };`,
    followUps: ['Implement debounce with a leading edge option.', 'Which would you use for an autocomplete?', 'How do you cancel a pending debounce?'],
    difficulty: 'MEDIUM',
    tags: ['performance', 'functions'],
  },
  {
    slug: 'js-null-undefined',
    category: 'JavaScript',
    question: 'Difference between null, undefined and ==, ===?',
    shortAnswer: 'undefined means never assigned; null is an explicit "no value". === compares type and value; == coerces, and null == undefined is true.',
    shortAnswerHi: 'undefined matlab kabhi assign hi nahi hua; null ek jaan-boojh kar rakha gaya "koi value nahi" hai. === type aur value dono compare karta hai; == coerce karta hai, aur null == undefined true hota hai.',
    detailedAnswer: 'undefined is what the engine gives you for missing variables, missing parameters and missing properties. null is something a developer assigns deliberately. Use === everywhere; the only defensible use of == is x == null as a shorthand for "null or undefined". typeof null returning "object" is a famous language bug that has never been fixed for backwards-compatibility reasons.',
    detailedAnswerHi: 'undefined wo hai jo engine deta hai — missing variable, missing parameter, missing property par. null developer khud jaan-boojh kar set karta hai. Har jagah === use karo; == ka ekmatra sahi use hai x == null, jo "null ya undefined" ka shorthand hai. typeof null ka "object" aana ek mashhoor language bug hai jo backwards-compatibility ki wajah se aaj tak theek nahi kiya gaya.',
    followUps: ['Why is typeof null "object"?', 'When is == acceptable?', 'Difference between || and ???'],
    difficulty: 'EASY',
    tags: ['basics', 'equality'],
  },

  /* ------------------------------------ React ----------------------------------- */
  {
    slug: 'react-virtual-dom',
    category: 'React',
    question: 'What is the virtual DOM and how does reconciliation work?',
    shortAnswer: 'React builds a lightweight tree of element objects, diffs it against the previous tree, and applies the minimal set of real DOM changes.',
    shortAnswerHi: 'React element objects ka ek halka tree banata hai, use pichhle tree se compare karta hai, aur sirf zaroori asli DOM changes lagata hai.',
    detailedAnswer: 'Direct DOM manipulation is expensive, so React renders to plain objects first. Reconciliation uses two heuristics to stay O(n): if the element type changes, the whole subtree is destroyed and rebuilt (losing its state); if the type is the same, props are updated in place and children are compared. Keys identify siblings across renders. The practical consequences: conditionally swapping element types wipes user input, and defining a component inside another creates a new type every render, remounting its children.',
    detailedAnswerHi: 'Seedha DOM chhoona mehenga hai, isliye React pehle plain objects mein render karta hai. Reconciliation do heuristics se O(n) rehta hai: element type badal gaya to poora subtree destroy karke dobara banta hai (uski state chali jaati hai); type same hai to props jagah par update hote hain aur children compare hote hain. Keys siblings ko renders ke beech pehchanti hain. Practical natije: element type conditionally badalne se user ka input mit jata hai, aur ek component ke andar doosra component define karne se har render par naya type banta hai aur children remount ho jaate hain.',
    followUps: ['Why does defining a component inside another cause remounts?', 'Does a re-render always update the DOM?', 'What is React Fiber?'],
    difficulty: 'MEDIUM',
    tags: ['virtual-dom', 'reconciliation'],
  },
  {
    slug: 'react-keys',
    category: 'React',
    question: 'Why should you not use the array index as a key?',
    shortAnswer: 'Indexes stay stable while the items behind them move, so React matches the wrong elements and component state sticks to the wrong row.',
    shortAnswerHi: 'Index wahi rehte hain jabki unke peeche ke items badal jaate hain, isliye React galat elements match karta hai aur component state galat row par chipak jati hai.',
    detailedAnswer: 'Keys tell React which new element corresponds to which old one. With index keys, deleting the first item shifts every subsequent item down one index, so React thinks each element kept its identity but changed its content. Anything React stores per element — input values, focus, scroll position, animation state — stays with the index instead of moving with the data. Index keys are only safe for a static list that is never reordered, filtered or inserted into.',
    detailedAnswerHi: 'Keys React ko batati hain ki naya element purane kis element se milta hai. Index keys ke saath pehla item delete karne par baaki sab ek index neeche khisak jaate hain, aur React samajhta hai ki har element ki identity wahi rahi bas content badla. React jo bhi per-element rakhta hai — input value, focus, scroll position, animation state — wo index ke saath hi ruk jata hai, data ke saath nahi jata. Index keys sirf us static list ke liye safe hain jo kabhi reorder, filter ya insert na ho.',
    followUps: ['What happens with duplicate keys?', 'Why is Math.random() a bad key?', 'When is an index key acceptable?'],
    difficulty: 'EASY',
    tags: ['keys', 'lists', 'must-know'],
  },
  {
    slug: 'react-useeffect-deps',
    category: 'React',
    question: 'What does the useEffect dependency array do, and what goes wrong when it is incomplete?',
    shortAnswer: 'It decides when the effect re-runs. Omitting a dependency freezes the effect around stale values from an old render.',
    shortAnswerHi: 'Ye tay karta hai ki effect kab dobara chalega. Koi dependency chhoot jaye to effect purane render ki stale values par atak jata hai.',
    detailedAnswer: 'No array means run after every render; [] means once after mount; [a, b] means re-run whenever a or b changes by Object.is. The effect body is a closure over the render it was created in, so if you leave a value out of the array to stop the effect re-running, the effect keeps reading that value from the first render forever — a stale closure. The correct fixes are to include the dependency and use a functional state update, move the value into a ref, or restructure so the effect is not needed at all. The other half of the problem is missing cleanup: subscriptions, timers and in-flight requests must be torn down or you get leaks and races.',
    detailedAnswerHi: 'Array na ho to har render ke baad; [] ho to sirf mount par ek baar; [a, b] ho to jab bhi a ya b Object.is ke hisaab se badle. Effect ki body us render par closure hoti hai jisme wo bani thi, isliye agar effect ko dobara chalne se rokne ke liye aap koi value array se hata dete ho, to effect hamesha pehle render ki hi value padhta rahega — yahi stale closure hai. Sahi fix: dependency shaamil karo aur functional state update use karo, ya value ko ref mein daalo, ya structure aisa banao ki effect ki zarurat hi na rahe. Doosra aadha problem missing cleanup hai: subscriptions, timers aur chalti hui requests band karni padti hain warna leaks aur races milte hain.',
    codeExample: `useEffect(() => {
  const id = setInterval(() => setCount(c => c + 1), 1000);  // functional update
  return () => clearInterval(id);                             // cleanup
}, []);`,
    followUps: ['What is a stale closure?', 'Why does an effect run twice in StrictMode?', 'How do you cancel a fetch on unmount?'],
    difficulty: 'MEDIUM',
    tags: ['useeffect', 'hooks', 'must-know'],
  },
  {
    slug: 'react-memo-usage',
    category: 'React',
    question: 'When should you use React.memo, useMemo and useCallback?',
    shortAnswer: 'Only when the computation is genuinely expensive, or when a value or function is passed to a memoised child or used as an effect dependency.',
    shortAnswerHi: 'Sirf tab jab computation sach mein mehengi ho, ya value/function kisi memoised child ko ja rahi ho ya effect dependency ho.',
    detailedAnswer: 'React.memo skips a re-render when props are shallow-equal. useMemo caches a computed value, useCallback caches a function identity. They are not free: each adds an allocation, a dependency array to maintain, and a comparison on every render. Memoising something cheap is a net loss. They also compose badly if you miss one — wrapping a callback in useCallback but still passing a fresh inline object as another prop means React.memo bails out anyway. Profile first; the usual real fix is rendering fewer things, not caching more.',
    detailedAnswerHi: 'React.memo tab re-render skip karta hai jab props shallow-equal hon. useMemo computed value cache karta hai, useCallback function identity. Ye muft nahi hain: har ek allocation, maintain karne wala dependency array aur har render par ek comparison jodta hai. Sasti cheez memoise karna ulta nuksaan hai. Aur agar ek jagah chhoot gayi to poora fayda chala jata hai — callback ko useCallback mein lapet kar bhi doosra prop inline object bhej diya to React.memo phir bhi re-render karega. Pehle profile karo; asli fix aksar kam cheezein render karna hota hai, zyada cache karna nahi.',
    followUps: ['Why might React.memo still re-render?', 'Is useMemo a guarantee?', 'How do you profile a React app?'],
    difficulty: 'MEDIUM',
    tags: ['performance', 'hooks'],
  },
  {
    slug: 'react-controlled-uncontrolled',
    category: 'React',
    question: 'Controlled vs uncontrolled components?',
    shortAnswer: 'Controlled inputs get their value from React state; uncontrolled ones keep it in the DOM and are read via a ref.',
    shortAnswerHi: 'Controlled inputs apni value React state se lete hain; uncontrolled DOM mein rakhte hain aur ref se padhe jaate hain.',
    detailedAnswer: 'A controlled input passes value and onChange, so React state is the single source of truth — that enables live validation, formatting and conditional disabling, at the cost of a re-render per keystroke. An uncontrolled input uses defaultValue and a ref, which is cheaper and closer to plain HTML, and is what libraries like react-hook-form use to avoid re-rendering large forms. The common bug is switching a component from uncontrolled to controlled mid-life by passing value={undefined} initially, which React warns about.',
    detailedAnswerHi: 'Controlled input value aur onChange leta hai, isliye React state hi sach ka ek source hoti hai — isse live validation, formatting aur conditional disabling milta hai, par har keystroke par re-render hota hai. Uncontrolled input defaultValue aur ref use karta hai, jo sasta hai aur plain HTML ke kareeb — react-hook-form jaisi libraries isi se badi forms ke re-renders bachati hain. Common bug hai component ko beech mein uncontrolled se controlled bana dena, jab shuru mein value={undefined} pass ho jata hai — React iski warning deta hai.',
    followUps: ['How do you validate a large form without re-rendering on every keystroke?', 'Why does React warn about switching to a controlled input?'],
    difficulty: 'EASY',
    tags: ['forms', 'state'],
  },
  {
    slug: 'react-context-vs-redux',
    category: 'React',
    question: 'Context vs Redux — when would you use each?',
    shortAnswer: 'Context solves prop drilling for rarely-changing values. Redux (or Zustand) is for frequently-changing shared state that needs structure, devtools and selectors.',
    shortAnswerHi: 'Context kam badalne wali values ke liye prop drilling ka hal hai. Redux (ya Zustand) us shared state ke liye hai jo baar-baar badalti hai aur jise structure, devtools aur selectors chahiye.',
    detailedAnswer: 'Context is a transport mechanism, not a state manager: it has no selectors, so every consumer re-renders whenever the provider value identity changes. That is fine for theme, locale or the current user, and painful for high-frequency state. A store gives you selector-based subscriptions (only components reading the changed slice re-render), middleware, and time-travel debugging. In practice many apps need neither — server state belongs in a data-fetching cache like React Query, and what remains is often just local component state.',
    detailedAnswerHi: 'Context ek transport mechanism hai, state manager nahi: usmein selectors nahi hain, isliye provider value ki identity badalte hi har consumer re-render hota hai. Theme, locale ya current user ke liye ye theek hai, par jaldi badalti state ke liye takleef deh. Store selector-based subscriptions deta hai (sirf wahi components re-render hote hain jo badla hua slice padh rahe hain), middleware deta hai, aur time-travel debugging. Sach ye hai ki kai apps ko dono nahi chahiye — server state React Query jaise data-fetching cache mein rehni chahiye, aur jo bacha wo aksar local component state hi hota hai.',
    followUps: ['Why do all consumers re-render on a context change?', 'Where does server state belong?', 'How do you split contexts to reduce re-renders?'],
    difficulty: 'MEDIUM',
    tags: ['context', 'state-management'],
  },

  /* ------------------------------------ Node ------------------------------------ */
  {
    slug: 'node-single-threaded',
    category: 'Node.js',
    question: 'Is Node.js single-threaded? How does it handle concurrency?',
    shortAnswer: 'Your JavaScript runs on one thread, but libuv handles I/O asynchronously and uses a thread pool for file, DNS and crypto work.',
    shortAnswerHi: 'Aapka JavaScript ek thread par chalta hai, par libuv I/O asynchronously sambhalta hai aur file, DNS aur crypto ke liye thread pool use karta hai.',
    detailedAnswer: 'One thread executes JS, so a CPU-heavy loop blocks every request. Concurrency comes from non-blocking I/O: the event loop hands operations to the OS and continues, running callbacks when they complete. Network I/O is event-driven (epoll/kqueue); file system, DNS and crypto go to a 4-thread libuv pool. For genuinely CPU-bound work you need worker_threads, a child process, or a separate service — exactly the reason this app pushes code execution into an isolated service with its own queue rather than running it inline.',
    detailedAnswerHi: 'Ek thread JS chalata hai, isliye CPU-heavy loop har request rok deta hai. Concurrency non-blocking I/O se aati hai: event loop operations OS ko de kar aage badh jata hai, aur poora hone par callbacks chalata hai. Network I/O event-driven hai (epoll/kqueue); file system, DNS aur crypto 4-thread libuv pool par jaate hain. Sach much CPU-bound kaam ke liye worker_threads, child process, ya alag service chahiye — isi wajah se ye app code execution ko inline chalane ki jagah apni queue wali isolated service par bhejta hai.',
    followUps: ['What goes to the thread pool?', 'How do you handle CPU-bound work?', 'What happens if you block the event loop?'],
    difficulty: 'MEDIUM',
    tags: ['event-loop', 'concurrency', 'must-know'],
  },
  {
    slug: 'node-middleware-order',
    category: 'Node.js',
    question: 'How does Express know a function is error-handling middleware?',
    shortAnswer: 'By its arity — it must declare four parameters (err, req, res, next) and be registered after all routes.',
    shortAnswerHi: 'Uske parameters ki ginti se — usme chaar parameters (err, req, res, next) hone chahiye aur wo saare routes ke baad register hona chahiye.',
    detailedAnswer: 'Express inspects fn.length. Four parameters means error handler; anything else is normal middleware. Removing the unused next because a linter flagged it silently converts it back into ordinary middleware and errors stop being caught — a genuinely common production bug. It must also be registered last, since middleware runs in registration order. In Express 4 an error thrown inside an async handler is not forwarded automatically, so you wrap handlers (this app uses asyncHandler) or move to Express 5.',
    detailedAnswerHi: 'Express fn.length dekhta hai. Chaar parameters matlab error handler; baaki sab normal middleware. Linter ke kehne par bekaar lagne wala next hata dena use chupchaap wapas normal middleware bana deta hai aur errors pakde jaana band ho jaate hain — production mein ye sach mein common bug hai. Aur ise sabse aakhir mein register karna hota hai, kyunki middleware registration order mein chalta hai. Express 4 mein async handler ke andar thrown error apne aap aage nahi jata, isliye handlers wrap karo (ye app asyncHandler use karta hai) ya Express 5 par jao.',
    followUps: ['What happens if you never call next()?', 'How do you catch async errors?', 'Why does middleware order matter?'],
    difficulty: 'EASY',
    tags: ['express', 'middleware'],
  },
  {
    slug: 'node-streams-why',
    category: 'Node.js',
    question: 'Why use streams instead of reading a whole file?',
    shortAnswer: 'Streams process data in chunks with backpressure, so memory usage stays constant no matter how large the input is.',
    shortAnswerHi: 'Streams data ko chunks mein backpressure ke saath process karte hain, isliye input kitna bhi bada ho memory constant rehti hai.',
    detailedAnswer: 'readFile on a 2 GB file allocates 2 GB and can exhaust the heap; a stream reads roughly 64 KB at a time. Backpressure is the real mechanism: write() returns false when the destination cannot keep up, telling the source to pause, which prevents an unbounded buffer from forming. pipeline() applies backpressure, propagates errors and destroys every stream in the chain, which .pipe() does not — using .pipe() is how you end up leaking file descriptors on failure.',
    detailedAnswerHi: '2 GB file par readFile 2 GB allocate karta hai aur heap khatam kar sakta hai; stream ek baar mein lagbhag 64 KB padhta hai. Asli mechanism backpressure hai: jab destination saath nahi de paata to write() false return karta hai, matlab source ruk jaye — isse bina limit ka buffer nahi banta. pipeline() backpressure lagata hai, errors aage bhejta hai aur chain ke saare streams destroy karta hai, jo .pipe() nahi karta — .pipe() use karne par hi failure par file descriptors leak hote hain.',
    followUps: ['What is backpressure?', 'pipe vs pipeline?', 'How would you stream a large CSV upload?'],
    difficulty: 'MEDIUM',
    tags: ['streams', 'performance'],
  },
  {
    slug: 'node-cluster-scaling',
    category: 'Node.js',
    question: 'How do you use all CPU cores in Node?',
    shortAnswer: 'Run one process per core with cluster or a process manager like PM2, and keep the app stateless so any process can serve any request.',
    shortAnswerHi: 'Har core par ek process chalao — cluster ya PM2 jaise process manager se — aur app stateless rakho taaki koi bhi process koi bhi request handle kar sake.',
    detailedAnswer: 'A single Node process uses one core for JS. cluster forks N workers sharing a listening socket, and the OS distributes connections. In containerised deployments the equivalent is running N replicas behind a load balancer, which is usually simpler to operate. Either way the app must hold no local state: sessions go to Redis, uploads to object storage, and any in-process cache must be treated as a per-worker optimisation, never as a source of truth. For CPU-bound work inside one request, use worker_threads instead.',
    detailedAnswerHi: 'Ek Node process JS ke liye ek hi core use karta hai. cluster N workers fork karta hai jo ek hi listening socket share karte hain, aur OS connections baant deta hai. Containerised deployment mein iska barabar hai load balancer ke peeche N replicas chalana, jo aksar chalane mein aasan hota hai. Dono mein shart ek hi hai: app par koi local state na ho — sessions Redis mein, uploads object storage mein, aur in-process cache ko per-worker optimisation maano, sach ka source kabhi nahi. Ek request ke andar CPU-bound kaam ke liye worker_threads use karo.',
    followUps: ['cluster vs worker_threads?', 'Where do sessions live when you scale out?', 'What breaks if you keep an in-memory cache?'],
    difficulty: 'MEDIUM',
    tags: ['scaling', 'cluster'],
  },

  /* ------------------------------------- SQL ------------------------------------ */
  {
    slug: 'sql-join-types',
    category: 'SQL',
    question: 'Explain INNER, LEFT, RIGHT and FULL OUTER JOIN.',
    shortAnswer: 'INNER keeps only matching rows; LEFT keeps all left rows; RIGHT keeps all right rows; FULL keeps everything from both sides.',
    shortAnswerHi: 'INNER sirf matching rows rakhta hai; LEFT saari left rows; RIGHT saari right rows; FULL dono taraf ka sab kuch.',
    detailedAnswer: 'Unmatched columns come back as NULL in outer joins. The trap that gets asked: adding a WHERE condition on the right table after a LEFT JOIN removes the unmatched rows, because NULL fails the comparison — the query becomes an INNER JOIN. Put that condition in the ON clause instead. To find rows with no match, LEFT JOIN and then filter WHERE right.id IS NULL, which is the anti-join pattern.',
    detailedAnswerHi: 'Outer joins mein match na hone par columns NULL aate hain. Jo trap poocha jata hai: LEFT JOIN ke baad right table par WHERE condition lagane se unmatched rows hat jaati hain, kyunki NULL comparison fail karta hai — query INNER JOIN ban jaati hai. Wo condition ON clause mein daalo. Jinka match nahi hai unhe dhoondhne ke liye LEFT JOIN karke WHERE right.id IS NULL lagao — yahi anti-join pattern hai.',
    codeExample: `SELECT u.name FROM users u
LEFT JOIN orders o ON o.user_id = u.id
WHERE o.id IS NULL;   -- users who never ordered`,
    followUps: ['Why did my LEFT JOIN act like an INNER JOIN?', 'What is a self join?', 'How do you find rows with no match?'],
    difficulty: 'MEDIUM',
    tags: ['joins', 'must-know'],
  },
  {
    slug: 'sql-index-tradeoffs',
    category: 'SQL',
    question: 'How do indexes work and when do they hurt?',
    shortAnswer: 'A B-tree index turns a scan into a lookup for reads, but every write must maintain it, and the wrong column order makes it unusable.',
    shortAnswerHi: 'B-tree index reads ke liye scan ko lookup bana deta hai, par har write ko use maintain karna padta hai, aur galat column order use bekaar bana deta hai.',
    detailedAnswer: 'Indexes cost storage and slow down INSERT/UPDATE/DELETE. A composite index follows the leftmost-prefix rule: an index on (user_id, created_at) serves queries filtering on user_id, or on user_id and created_at, but not created_at alone. Indexes are also silently bypassed when you wrap the column in a function, use a leading wildcard in LIKE, or force an implicit type cast. Always confirm with EXPLAIN ANALYZE rather than assuming — a sequential scan on a large hot table is the signal to investigate.',
    detailedAnswerHi: 'Indexes storage lete hain aur INSERT/UPDATE/DELETE dheeme karte hain. Composite index leftmost-prefix rule follow karta hai: (user_id, created_at) par index user_id wali, ya user_id aur created_at wali queries mein chalega, par akele created_at mein nahi. Index chupchaap tab bhi skip ho jata hai jab aap column ko function mein lapet do, LIKE mein shuru mein wildcard lagao, ya implicit type cast ho jaye. Andaaza lagane ki jagah EXPLAIN ANALYZE se confirm karo — badi hot table par sequential scan hi jaanch ka signal hai.',
    followUps: ['What is the leftmost prefix rule?', 'What is a covering index?', 'Does a foreign key create an index in Postgres?'],
    difficulty: 'HARD',
    tags: ['indexes', 'performance', 'must-know'],
  },
  {
    slug: 'sql-nplus1',
    category: 'SQL',
    question: 'What is the N+1 query problem and how do you fix it?',
    shortAnswer: 'One query fetches N rows and then each row triggers another query. Fix it by eager-loading the relation in a single query.',
    shortAnswerHi: 'Ek query N rows laati hai aur phir har row ek aur query chalati hai. Fix ye hai ki relation ko ek hi query mein eager-load karo.',
    detailedAnswer: 'It appears whenever an ORM lazy-loads a relation inside a loop: fetching 100 posts and reading post.author fires 101 queries. Each is fast in isolation, so it hides in development and collapses under production latency. The fix depends on the ORM — Prisma include/select, Django select_related for forward FK/OneToOne and prefetch_related for many-to-many and reverse FK, SQLAlchemy joinedload. Detect it by counting queries per request, not by reading the code.',
    detailedAnswerHi: 'Ye tab aata hai jab ORM loop ke andar relation lazy-load karta hai: 100 posts laakar post.author padhna 101 queries chalata hai. Har query alag se tez hai, isliye development mein chhupa rehta hai aur production latency mein bikhar jata hai. Fix ORM par nirbhar hai — Prisma mein include/select, Django mein forward FK/OneToOne ke liye select_related aur many-to-many/reverse FK ke liye prefetch_related, SQLAlchemy mein joinedload. Ise pakadne ke liye code padhne ki jagah per-request query count naapo.',
    followUps: ['select_related vs prefetch_related?', 'How do you detect N+1 in production?', 'Can eager loading ever be worse?'],
    difficulty: 'MEDIUM',
    tags: ['orm', 'performance', 'must-know'],
  },
  {
    slug: 'sql-acid',
    category: 'SQL',
    question: 'What does ACID mean?',
    shortAnswer: 'Atomicity (all or nothing), Consistency (constraints hold), Isolation (concurrent transactions do not corrupt each other), Durability (committed data survives a crash).',
    shortAnswerHi: 'Atomicity (sab ya kuch nahi), Consistency (constraints bane rahein), Isolation (saath chalti transactions ek doosre ko kharab na karein), Durability (commit hua data crash ke baad bhi rahe).',
    detailedAnswer: 'Isolation is the one with real trade-offs, because full serialisability costs concurrency. Postgres defaults to READ COMMITTED, which prevents dirty reads but still allows non-repeatable reads and phantoms. That matters for read-modify-write logic: two concurrent requests can both read stock = 10 and both write 9, losing an update. The fixes are SELECT ... FOR UPDATE to lock the row, an atomic UPDATE ... SET stock = stock - 1 WHERE stock > 0, or a higher isolation level with retry-on-conflict.',
    detailedAnswerHi: 'Asli trade-off Isolation mein hai, kyunki poori serialisability concurrency ki keemat par aati hai. Postgres ka default READ COMMITTED hai, jo dirty reads rokta hai par non-repeatable reads aur phantoms ab bhi hone deta hai. Read-modify-write logic mein ye matter karta hai: do concurrent requests dono stock = 10 padh sakti hain aur dono 9 likh dengi, ek update kho jayega. Fix: row lock karne ke liye SELECT ... FOR UPDATE, ya atomic UPDATE ... SET stock = stock - 1 WHERE stock > 0, ya zyada isolation level ke saath conflict par retry.',
    followUps: ['What are dirty, non-repeatable and phantom reads?', 'How would you decrement inventory safely?', 'What causes a deadlock?'],
    difficulty: 'HARD',
    tags: ['transactions', 'acid'],
  },
  {
    slug: 'sql-vs-nosql',
    category: 'Database',
    question: 'SQL vs NoSQL — how do you choose?',
    shortAnswer: 'Relational when data is structured and relationships and transactions matter. Document/key-value when the access pattern is known, the shape varies, and you need horizontal scale.',
    shortAnswerHi: 'Relational tab jab data structured ho aur relationships aur transactions matter karein. Document/key-value tab jab access pattern pata ho, shape badalti ho, aur horizontal scale chahiye.',
    detailedAnswer: 'Relational databases give you joins, multi-row ACID transactions, and constraints the database itself enforces — you cannot write inconsistent data even by accident. Document stores give flexible schemas and easy sharding, at the price of doing joins in application code and often being limited to per-document atomicity. The honest answer names the access pattern first: model relational data relationally, and reach for a document store when documents genuinely are the unit of read and write. Postgres also has JSONB, so "I need flexible fields" is rarely by itself a reason to leave SQL.',
    detailedAnswerHi: 'Relational databases joins, multi-row ACID transactions, aur khud database ke enforce kiye constraints dete hain — galti se bhi inconsistent data nahi likh sakte. Document stores flexible schema aur aasan sharding dete hain, iski keemat ye hai ki joins application code mein karne padte hain aur atomicity aksar sirf ek document tak hoti hai. Imaandar jawab pehle access pattern batata hai: relational data ko relational hi model karo, aur document store tab lo jab sach mein document hi padhne-likhne ki ikai ho. Postgres mein JSONB bhi hai, isliye sirf "flexible fields chahiye" SQL chhodne ki wajah nahi hoti.',
    followUps: ['What is CAP theorem?', 'When would you use both together?', 'What does JSONB give you in Postgres?'],
    difficulty: 'MEDIUM',
    tags: ['database', 'nosql', 'architecture'],
  },

  /* -------------------------------- Auth & Security ----------------------------- */
  {
    slug: 'auth-jwt-storage',
    category: 'Authentication',
    question: 'Where should you store a JWT in the browser, and why?',
    shortAnswer: 'Refresh token in an httpOnly Secure SameSite cookie; keep the short-lived access token in memory. localStorage is readable by any XSS.',
    shortAnswerHi: 'Refresh token httpOnly Secure SameSite cookie mein; short-lived access token memory mein. localStorage ko koi bhi XSS padh sakta hai.',
    detailedAnswer: 'localStorage is accessible to any JavaScript on the page, so a single XSS exfiltrates the token. An httpOnly cookie is invisible to JS, which removes that path — but cookies are attached automatically, so you reintroduce CSRF and need SameSite=Lax/Strict or an anti-CSRF token. The standard shape is a short-lived access token (~15 minutes) held in memory and a long-lived refresh token in an httpOnly cookie, rotated on every use so a stolen token is detectable on reuse. Nothing secret ever goes in the payload: a JWT is signed, not encrypted, and anyone can base64-decode it.',
    detailedAnswerHi: 'localStorage page ke kisi bhi JavaScript ko dikhta hai, isliye ek XSS hi token le udta hai. httpOnly cookie JS ko dikhti hi nahi, jisse wo raasta band ho jata hai — par cookies apne aap lagti hain, isliye CSRF wapas aa jata hai aur SameSite=Lax/Strict ya anti-CSRF token chahiye. Standard shape hai: short-lived access token (~15 minute) memory mein aur long-lived refresh token httpOnly cookie mein, har use par rotate — taaki churaya hua token dobara use hone par pakda jaye. Payload mein kabhi kuch secret nahi: JWT signed hai, encrypted nahi, koi bhi base64-decode kar sakta hai.',
    followUps: ['How do you revoke a JWT?', 'What is refresh token rotation?', 'What is the alg:none attack?'],
    difficulty: 'MEDIUM',
    tags: ['jwt', 'security', 'must-know'],
  },
  {
    slug: 'auth-hashing',
    category: 'Authentication',
    question: 'Why hash passwords with bcrypt instead of SHA-256?',
    shortAnswer: 'bcrypt is deliberately slow and salted, so brute forcing a leaked hash is expensive. SHA-256 is fast, which helps the attacker.',
    shortAnswerHi: 'bcrypt jaan-boojh kar dheema aur salted hai, isliye leak hue hash ko brute force karna mehenga padta hai. SHA-256 tez hai, jiska fayda attacker ko milta hai.',
    detailedAnswer: 'A GPU computes billions of SHA-256 hashes per second, so a leaked table of fast hashes is cracked quickly. bcrypt (or argon2id) has a tunable work factor, turning that into a handful per second per core — raise the cost as hardware improves. The salt, which bcrypt embeds in the output, defeats rainbow tables and ensures two users with the same password get different hashes. Encryption is the wrong tool entirely: it is reversible, so leaking the key leaks every password at once.',
    detailedAnswerHi: 'GPU ek second mein arbon SHA-256 hashes nikal leta hai, isliye tez hashes ki leak hui table jaldi crack ho jaati hai. bcrypt (ya argon2id) mein tunable work factor hota hai, jo ise per core kuch hi hashes per second bana deta hai — hardware behtar ho to cost badha do. Salt, jo bcrypt output mein hi rakh deta hai, rainbow tables bekaar karta hai aur ye pakka karta hai ki same password wale do users ke hash alag hon. Encryption to bilkul galat tool hai: wo reversible hai, isliye key leak hote hi saare passwords ek saath khul jaate hain.',
    followUps: ['What is a salt?', 'What cost factor would you pick?', 'How do you prevent account enumeration?'],
    difficulty: 'MEDIUM',
    tags: ['password', 'security', 'must-know'],
  },
  {
    slug: 'auth-401-403',
    category: 'Authentication',
    question: 'Difference between authentication and authorisation (401 vs 403)?',
    shortAnswer: 'Authentication is who you are (401 when unknown). Authorisation is what you may do (403 when known but not permitted).',
    shortAnswerHi: 'Authentication matlab aap kaun ho (pata na ho to 401). Authorisation matlab aap kya kar sakte ho (pata ho par ijazat na ho to 403).',
    detailedAnswer: 'A valid login proves identity; it says nothing about permission. The mistake that shows up in audits is checking only authentication: requireAuth confirms a valid token, but the handler then loads record 42 without confirming the caller owns it, so any logged-in user can read anyone else\'s data by changing the id. Ownership and role checks belong in the service layer, next to the data, not scattered in routes — and returning 404 instead of 403 for objects the user may not even know exist avoids leaking their existence.',
    detailedAnswerHi: 'Valid login sirf identity sabit karta hai; permission ke baare mein kuch nahi kehta. Audits mein jo galti milti hai wo yahi hai ki sirf authentication check hota hai: requireAuth valid token confirm karta hai, par handler record 42 bina ye dekhe load kar leta hai ki wo caller ka hai ya nahi — isliye koi bhi logged-in user id badal kar doosre ka data padh leta hai. Ownership aur role checks service layer mein, data ke paas hone chahiye, routes mein bikhre hue nahi — aur jin objects ke hone ka bhi user ko pata nahi hona chahiye unke liye 403 ki jagah 404 dena unke astitva ko leak hone se bachata hai.',
    followUps: ['Where should ownership checks live?', 'When would you return 404 instead of 403?', 'What is RBAC?'],
    difficulty: 'EASY',
    tags: ['auth', 'http', 'security'],
  },
  {
    slug: 'security-xss-csrf',
    category: 'Authentication',
    question: 'XSS vs CSRF — what is the difference and how do you defend against each?',
    shortAnswer: 'XSS runs attacker JavaScript in your page (defend with output escaping and CSP). CSRF makes the browser send an authenticated request from another site (defend with SameSite cookies and CSRF tokens).',
    shortAnswerHi: 'XSS aapke page par attacker ka JavaScript chalata hai (bachav: output escaping aur CSP). CSRF browser se doosri site ke through authenticated request bhijwata hai (bachav: SameSite cookies aur CSRF tokens).',
    detailedAnswer: 'XSS is a code-execution problem: if user content is rendered as HTML, the attacker gets everything JavaScript can reach, including localStorage tokens. React escapes by default, so the usual hole is dangerouslySetInnerHTML or an unsanitised markdown renderer. CSRF is a confused-deputy problem: the browser attaches cookies automatically, so a form on another site can trigger a state-changing request. SameSite=Lax blocks most of it, tokens cover the rest. The two interact: moving tokens into httpOnly cookies defeats XSS theft but reintroduces CSRF, which is why you need both defences rather than choosing one.',
    detailedAnswerHi: 'XSS code-execution ki samasya hai: agar user content HTML ki tarah render ho jaye to attacker ko wo sab mil jata hai jahan JavaScript pahunch sakta hai, localStorage ke tokens samet. React by default escape karta hai, isliye aam chhed dangerouslySetInnerHTML ya bina sanitise kiya markdown renderer hota hai. CSRF confused-deputy ki samasya hai: browser cookies apne aap laga deta hai, isliye doosri site ka form state-changing request chala sakta hai. SameSite=Lax iska zyadatar hissa rokta hai, tokens baaki. Dono jude hue hain: tokens ko httpOnly cookies mein le jaane se XSS wali chori rukti hai par CSRF wapas aa jata hai — isiliye dono bachav chahiye, ek chunna kaafi nahi.',
    followUps: ['Does CORS protect your API?', 'How does SameSite work?', 'What is a Content-Security-Policy?'],
    difficulty: 'HARD',
    tags: ['xss', 'csrf', 'security', 'must-know'],
  },

  /* ------------------------------- System Design -------------------------------- */
  {
    slug: 'sd-scale-app',
    category: 'System Design',
    question: 'An endpoint is slow under load. Walk me through how you would fix it.',
    shortAnswer: 'Measure first, then fix the query, then cache, then add replicas or a queue. Scaling hardware before finding the bottleneck usually just costs money.',
    shortAnswerHi: 'Pehle measure karo, phir query theek karo, phir cache lagao, phir replicas ya queue jodo. Bottleneck dhoondhe bina hardware badhana aksar sirf paisa kharch karta hai.',
    detailedAnswer: 'Start with data: p95 latency, query counts per request, and where time is actually spent. Most "we need to scale" turns out to be one missing index or an N+1. Then look at whether the work belongs in the request at all — emails, reports and third-party calls go to a queue with a 202 response. Then cache hot reads with a defined invalidation strategy. Only after that do read replicas, more app instances or sharding make sense, and each brings its own consistency cost. Saying what you would measure at each step is what makes this answer credible.',
    detailedAnswerHi: 'Data se shuru karo: p95 latency, per request query count, aur time asal mein kahan ja raha hai. "Scale chahiye" aksar ek missing index ya N+1 nikalta hai. Phir dekho ki wo kaam request mein hona bhi chahiye ya nahi — emails, reports aur third-party calls queue par jaayein aur 202 return ho. Uske baad hot reads cache karo, ek tay invalidation strategy ke saath. Iske baad hi read replicas, zyada app instances ya sharding samajh mein aate hain, aur har ek apni consistency ki keemat laata hai. Har step par "main ye naapunga" bolna hi is jawab ko bharosemand banata hai.',
    followUps: ['How do you find the bottleneck?', 'What would you cache and how would you invalidate it?', 'When is sharding justified?'],
    difficulty: 'HARD',
    tags: ['scaling', 'performance'],
  },
  {
    slug: 'sd-idempotency',
    category: 'System Design',
    question: 'How do you make a payment endpoint safe to retry?',
    shortAnswer: 'Accept an Idempotency-Key, store the key with its response, and return the stored response instead of charging again.',
    shortAnswerHi: 'Idempotency-Key lo, key ke saath uska response store karo, aur dobara aane par dobara charge karne ki jagah wahi stored response wapas do.',
    detailedAnswer: 'Networks fail after the server has already acted, so the client cannot tell a lost response from a failed request and will retry. The server therefore has to make duplicate requests harmless. The client generates a unique key per logical operation and sends it as a header; the server stores it with the resulting response inside the same transaction as the charge, so the key and the effect commit together. A repeat returns the stored response verbatim. The same reasoning applies to queue consumers, where at-least-once delivery guarantees jobs run twice.',
    detailedAnswerHi: 'Network tab bhi fail hota hai jab server kaam kar chuka hota hai, isliye client ko pata hi nahi chalta ki response khoya ya request fail hui — wo retry karega. Isliye server ko duplicate requests ko harmless banana padta hai. Client har logical operation ke liye ek unique key banata hai aur header mein bhejta hai; server us key aur uske response ko charge wali usi transaction mein store karta hai, taaki key aur effect saath commit hon. Dobara aane par wahi stored response jyon ka tyon milta hai. Yahi soch queue consumers par bhi lagti hai, jahan at-least-once delivery ka matlab hai jobs do baar chalenge hi.',
    followUps: ['Which HTTP methods are idempotent by spec?', 'How long do you keep idempotency keys?', 'How does this apply to queue consumers?'],
    difficulty: 'MEDIUM',
    tags: ['idempotency', 'reliability'],
  },

  /* ---------------------------------- Git/Docker -------------------------------- */
  {
    slug: 'git-merge-rebase',
    category: 'Git',
    question: 'Merge vs rebase — when do you use each?',
    shortAnswer: 'Rebase local unpushed work to keep history linear. Merge anything already shared, because rebase rewrites commit hashes.',
    shortAnswerHi: 'Local, bina push kiya kaam rebase karo taaki history seedhi rahe. Jo pehle se shared hai use merge karo, kyunki rebase commit hashes badal deta hai.',
    detailedAnswer: 'Merge records history as it happened, including the branch topology, at the cost of a noisier graph. Rebase replays commits onto a new base, producing a linear history that is far easier to read and bisect — but the replayed commits are new objects with new hashes. If someone else has already pulled those commits, their history and yours diverge and reconciling it is painful. Hence the rule: rebase before you share, merge after. To undo a commit that is already public, use git revert, which adds a new commit rather than rewriting the old one.',
    detailedAnswerHi: 'Merge history ko waise hi record karta hai jaise wo hui, branch topology samet — keemat ye ki graph bhara-bhara ho jata hai. Rebase commits ko naye base par dobara chalata hai aur linear history deta hai jo padhne aur bisect karne mein kaafi aasan hai — par wo commits naye objects hain naye hashes ke saath. Agar kisi ne wo commits pehle hi pull kar li hain to uski aur aapki history alag ho jaati hai aur milana takleef deh hota hai. Isliye rule: share karne se pehle rebase, baad mein merge. Jo commit public ho chuki hai use undo karne ke liye git revert use karo, jo purani ko badalne ki jagah nayi commit jodta hai.',
    followUps: ['How do you undo a pushed commit?', 'What does git reflog do?', 'What is an interactive rebase used for?'],
    difficulty: 'EASY',
    tags: ['git', 'workflow'],
  },
  {
    slug: 'docker-image-container',
    category: 'Docker',
    question: 'Difference between an image and a container, and why use multi-stage builds?',
    shortAnswer: 'An image is an immutable template; a container is a running instance with a writable layer. Multi-stage builds keep build tools out of the final image.',
    shortAnswerHi: 'Image ek immutable template hai; container uska chalta hua instance writable layer ke saath. Multi-stage builds build tools ko final image se bahar rakhte hain.',
    detailedAnswer: 'An image is a stack of read-only layers plus metadata; a container adds a writable layer and a process, and its filesystem dies when it is removed — persistence needs a volume. A multi-stage build compiles in one stage and copies only the artefacts into a slim runtime stage, so compilers, dev dependencies and source never ship. That cuts image size dramatically and removes attack surface: this project\'s Python runner deletes pip and the Node runner deletes npm, so submitted code cannot install anything even if the network policy were ever relaxed. Layer ordering matters too — copy the manifest and install dependencies before copying source, or every code change busts the dependency cache.',
    detailedAnswerHi: 'Image read-only layers ka stack plus metadata hai; container usme writable layer aur ek process jodta hai, aur hataate hi uska filesystem khatam — persistence ke liye volume chahiye. Multi-stage build ek stage mein compile karta hai aur sirf artefacts slim runtime stage mein copy karta hai, isliye compilers, dev dependencies aur source kabhi ship nahi hote. Isse image size bahut ghat jata hai aur attack surface hat jata hai: is project ka Python runner pip hata deta hai aur Node runner npm, taaki submitted code kuch install kar hi na sake, chahe network policy kabhi dheeli bhi ho jaye. Layer ordering bhi matter karta hai — manifest copy karke dependencies pehle install karo, source baad mein, warna har code change dependency cache tod dega.',
    followUps: ['How does layer caching work?', 'How do you persist data?', 'How would you sandbox untrusted code in a container?'],
    difficulty: 'MEDIUM',
    tags: ['docker', 'devops'],
  },
  {
    slug: 'testing-what-to-mock',
    category: 'Testing',
    question: 'What should you mock in tests, and what should you not?',
    shortAnswer: 'Mock at the boundary — network, clock, filesystem, third-party APIs. Do not mock the thing you are actually testing, or your own internal collaborators.',
    shortAnswerHi: 'Boundary par mock karo — network, clock, filesystem, third-party APIs. Jise test kar rahe ho use ya apne internal collaborators ko mock mat karo.',
    detailedAnswer: 'Mocking internals couples the test to the implementation: it breaks on every refactor while catching no real bugs, and it can pass while the code is broken. Mock what is slow, non-deterministic or outside your control — a payment provider, the current time, an SMTP server. For database code, prefer a real database in an integration test (a container or a test schema) over a mocked ORM, because the query itself is the thing most likely to be wrong. A useful test asserts on the outcome the caller observes, not on which internal functions were called.',
    detailedAnswerHi: 'Internals mock karne se test implementation se chipak jata hai: har refactor par tootta hai par asli bug ek bhi nahi pakadta, aur code toota hone par bhi pass ho sakta hai. Wo mock karo jo dheema hai, non-deterministic hai, ya aapke control se bahar hai — payment provider, current time, SMTP server. Database code ke liye mocked ORM se behtar hai integration test mein asli database (container ya test schema), kyunki galat hone ki sabse zyada sambhavna query mein hi hoti hai. Achha test us result par assert karta hai jo caller ko dikhta hai, is par nahi ki andar kaunse functions call hue.',
    followUps: ['What is the testing pyramid?', 'How do you test time-dependent code?', 'Is 100% coverage a good goal?'],
    difficulty: 'MEDIUM',
    tags: ['testing', 'quality'],
  },
  /* ---------------------------------- MongoDB ---------------------------------- */
  {
    slug: 'mongo-embed-vs-reference',
    category: 'MongoDB',
    question: 'When do you embed data and when do you reference it?',
    shortAnswer: 'Embed what you always read together and that stays bounded. Reference what is shared, unbounded, or changes independently.',
    shortAnswerHi: 'Jo hamesha saath padha jata hai aur bounded rehta hai use embed karo. Jo shared hai, bina limit badhta hai, ya alag se badalta hai use reference karo.',
    detailedAnswer: 'The decision follows the access pattern, not the relationship. Embed when the child has no life without the parent and the array is bounded — order items are the classic case, and embedding makes the whole order one atomic write. Reference when many parents share the data (a product in 10,000 orders), when it grows without limit (an activity log), or when the document would approach the 16 MB cap. That cap is the detail that matters most: an unbounded embedded array works fine in development and fails in production. Duplication is often correct here — storing the price inside an order item is a historical record of what the customer actually paid, not a normalisation bug.',
    detailedAnswerHi: 'Faisla access pattern se hota hai, relation se nahi. Embed tab jab child parent ke bina exist na kare aur array bounded ho — order items classic case hai, aur embed karne se poora order ek atomic write ban jata hai. Reference tab jab kai parents wahi data share karein (ek product 10,000 orders mein), jab wo bina limit badhe (activity log), ya jab document 16 MB cap ke paas pahunche. Wahi cap sabse important detail hai: bina limit ka embedded array development mein theek chalta hai aur production mein fail hota hai. Yahan duplication aksar sahi hai — order item mein price rakhna historical record hai ki customer ne kya diya, normalisation ka bug nahi.',
    codeExample: `// embed: bounded + read together + price is historical
{ _id, userId: ObjectId("..."), items: [{ productId, name, price, qty }], total }

// ❌ unbounded — will hit 16 MB
{ _id: userId, activityLog: [ /* forever */ ] }`,
    followUps: ['What is the maximum document size?', 'Is duplicating data ever right?', 'How would you model millions of activity events?'],
    difficulty: 'HARD',
    tags: ['mongodb', 'schema-design', 'must-know'],
  },
  {
    slug: 'mongo-aggregation-match-first',
    category: 'MongoDB',
    question: 'What is the aggregation pipeline, and why should $match come first?',
    shortAnswer: 'A sequence of stages, each transforming documents and passing them on. $match first because only a leading $match can use an index, and every later stage then handles fewer documents.',
    shortAnswerHi: 'Stages ka ek sequence, har stage documents ko badal kar aage bhejta hai. $match pehle isliye kyunki index sirf shuru wale $match mein chalta hai, aur aage ke har stage ko phir kam documents milte hain.',
    detailedAnswer: 'Stages run in order: $match filters, $group aggregates, $sort orders, $project shapes, $lookup joins, $unwind expands an array into one document per element. Because they are sequential, filtering early is both an index win and a volume win — a $match after $group is Mongo\'s HAVING and is genuinely more expensive. $unwind deserves care: it multiplies your document count, so filter before it, never after. And $lookup is not a real join — without an index on the foreign field it becomes a query per input document, which is usually a sign the data should have been embedded.',
    detailedAnswerHi: 'Stages order mein chalte hain: $match filter, $group aggregate, $sort order, $project shape, $lookup join, $unwind array ko har element ke alag document mein todta hai. Sequential hone ki wajah se jaldi filter karna index ka bhi fayda hai aur volume ka bhi — $group ke baad ka $match Mongo ka HAVING hai aur sach mein mehenga hai. $unwind par dhyan chahiye: ye document count badha deta hai, isliye usse pehle filter karo, baad mein nahi. Aur $lookup asli join nahi hai — foreign field par index na ho to har input document ke liye ek query ban jata hai, jo aksar signal hai ki data embed karna chahiye tha.',
    followUps: ['What does $unwind do?', 'Is $lookup the same as JOIN?', 'How do you do HAVING?'],
    difficulty: 'HARD',
    tags: ['mongodb', 'aggregation'],
  },
  {
    slug: 'mongo-update-without-set',
    category: 'MongoDB',
    question: 'What happens if you call updateOne without $set?',
    shortAnswer: 'The entire document is replaced by the object you passed. Every other field is deleted.',
    shortAnswerHi: 'Poora document us object se replace ho jata hai jo aapne bheja. Baaki saare fields delete ho jaate hain.',
    detailedAnswer: 'updateOne({_id}, { price: 449 }) does not mean "set price to 449" — it means "make this document be exactly { price: 449 }". Name, stock, tags, timestamps all vanish. Modern drivers throw when the update object has no operator, but replaceOne still behaves this way by design and older code does too. The related trap is doing read-modify-write in application code: read stock 10, subtract in JS, write 9 — two concurrent requests both write 9 and one order is lost. $inc is atomic on the server, so { $inc: { stock: -1 } } with a { stock: { $gt: 0 } } filter is the correct version.',
    detailedAnswerHi: 'updateOne({_id}, { price: 449 }) ka matlab "price 449 kar do" nahi hai — matlab hai "is document ko exactly { price: 449 } bana do". Name, stock, tags, timestamps sab gayab. Naye drivers operator na hone par error dete hain, par replaceOne jaan-boojh kar aise hi chalta hai aur purana code bhi. Isse juda trap hai app code mein read-modify-write: stock 10 padho, JS mein ghatao, 9 likho — do concurrent requests dono 9 likh dengi aur ek order kho jayega. $inc server par atomic hai, isliye { stock: { $gt: 0 } } filter ke saath { $inc: { stock: -1 } } sahi version hai.',
    codeExample: `await products.updateOne({ _id: id }, { $set: { price: 449 } });   // ✅
await products.updateOne({ _id: id, stock: { $gt: 0 } }, { $inc: { stock: -1 } }); // atomic`,
    followUps: ['How do you decrement stock safely?', 'updateOne vs replaceOne?', 'Why is $inc better than read-then-write?'],
    difficulty: 'MEDIUM',
    tags: ['mongodb', 'crud', 'must-know'],
  },
  {
    slug: 'mongo-transactions-q',
    category: 'MongoDB',
    question: 'Does MongoDB support ACID transactions?',
    shortAnswer: 'Yes. Single-document writes are always atomic, and multi-document ACID transactions exist since 4.0 — but they need a replica set and cost performance.',
    shortAnswerHi: 'Haan. Single-document writes hamesha atomic hain, aur 4.0 se multi-document ACID transactions bhi hain — par unke liye replica set chahiye aur performance ki keemat lagti hai.',
    detailedAnswer: 'The important half is that a single document update is atomic no matter how deeply nested it is. That is a design lever: model whatever must change together as one document and you never need a transaction at all. Multi-document transactions do exist, but they require a replica set (a standalone mongod cannot run them, though Atlas always can), they are measurably slower, and they have a 60-second default limit. Reaching for one is often a hint the schema should have embedded instead. Related: write concern w:"majority" is what makes an acknowledged write survive a failover — w:1 can be lost when the primary dies.',
    detailedAnswerHi: 'Zyada important baat ye hai ki ek document ka update kitna bhi nested ho, atomic hi hota hai. Ye ek design lever hai: jo saath badalna chahiye use ek document mein model karo, transaction ki zarurat hi nahi padegi. Multi-document transactions hain, par unke liye replica set chahiye (akela mongod nahi chala sakta, Atlas hamesha chala sakta hai), wo naapne layak dheeme hain, aur 60-second ki default limit hai. Inki zarurat padna aksar ishara hai ki schema mein embed karna chahiye tha. Isse juda: w:"majority" write concern hi acknowledged write ko failover mein bachata hai — w:1 primary marne par kho sakta hai.',
    followUps: ['When do you actually need one?', 'w:1 vs w:"majority"?', 'What is a replica set?'],
    difficulty: 'HARD',
    tags: ['mongodb', 'transactions', 'acid'],
  },
  {
    slug: 'mongo-esr-index',
    category: 'MongoDB',
    question: 'How do you choose the field order in a compound MongoDB index?',
    shortAnswer: 'ESR — Equality fields first, then Sort fields, then Range fields.',
    shortAnswerHi: 'ESR — pehle Equality fields, phir Sort fields, phir Range fields.',
    detailedAnswer: 'For find({ userId: id, price: { $gt: 100 } }).sort({ createdAt: -1 }), the index should be { userId: 1, createdAt: -1, price: 1 }: equality narrows first, the sort field then lets Mongo walk the index in order rather than sorting in memory, and the range comes last because it can only be applied as a scan. Like SQL, Mongo follows the leftmost prefix, so { a, b, c } serves a, a+b and a+b+c but not b alone. Verify with explain("executionStats") and compare docsExamined against nReturned — examining 100,000 documents to return 20 means the index is missing or ordered wrongly. Mongo creates an index only for _id; nothing else is automatic.',
    detailedAnswerHi: 'find({ userId: id, price: { $gt: 100 } }).sort({ createdAt: -1 }) ke liye index { userId: 1, createdAt: -1, price: 1 } hona chahiye: equality pehle daayra chhota karta hai, phir sort field Mongo ko index par order mein chalne deta hai (memory mein sort nahi karna padta), aur range aakhir mein kyunki wo sirf scan ki tarah lag sakta hai. SQL ki tarah Mongo bhi leftmost prefix follow karta hai, isliye { a, b, c } a, a+b aur a+b+c mein chalega par akele b mein nahi. explain("executionStats") se check karo aur docsExamined ko nReturned se compare karo — 20 return karne ke liye 1,00,000 documents padhna matlab index nahi hai ya galat order mein hai. Mongo sirf _id ka index khud banata hai, baaki kuch automatic nahi.',
    followUps: ['How do you know a query used an index?', 'What is a TTL index for?', 'Does Mongo index foreign references automatically?'],
    difficulty: 'HARD',
    tags: ['mongodb', 'indexes', 'performance'],
  },
  {
    slug: 'mongo-mongoose-populate',
    category: 'MongoDB',
    question: 'What does Mongoose populate() do, and what should you watch out for?',
    shortAnswer: 'It follows a reference and swaps the ObjectId for the real document — via a second query. Inside a loop it becomes the N+1 problem.',
    shortAnswerHi: 'Ye reference follow karke ObjectId ki jagah asli document le aata hai — ek doosri query se. Loop ke andar ye N+1 problem ban jata hai.',
    detailedAnswer: 'populate is a $lookup in Mongoose clothing: convenient, but it is an extra round trip, and calling it per item in a loop is exactly the N+1 pattern people complain about in SQL ORMs. Two other Mongoose traps are worth knowing. findOneAndUpdate skips save middleware and validators by default, so a pre("save") password-hashing hook silently does not run on the update path — pass runValidators or route writes through save(). And .lean() returns plain objects instead of full Mongoose documents, which is significantly faster for read-only endpoints where you never call .save().',
    detailedAnswerHi: 'populate asal mein Mongoose ke bhes mein $lookup hai: convenient, par ek extra round trip, aur loop mein har item par call karna wahi N+1 pattern hai jiski SQL ORMs mein shikayat hoti hai. Do aur Mongoose traps jaanna zaroori hai. findOneAndUpdate by default save middleware aur validators skip karta hai, isliye pre("save") wala password-hashing hook update path par chupchaap nahi chalta — runValidators do ya writes save() se karao. Aur .lean() poore Mongoose documents ki jagah plain objects deta hai, jo read-only endpoints ke liye kaafi tez hai jahan .save() kabhi call nahi hota.',
    followUps: ['Why use Mongoose at all if Mongo is schemaless?', 'Why might your password hook not run?', 'What does .lean() change?'],
    difficulty: 'MEDIUM',
    tags: ['mongodb', 'mongoose', 'nodejs'],
  },
  {
    slug: 'mongo-vs-postgres-q',
    category: 'MongoDB',
    question: 'MongoDB or PostgreSQL — how do you decide?',
    shortAnswer: 'Start from the access pattern. Relational for related data with integrity rules and multi-row transactions; document when documents are the unit of read and write and shapes vary.',
    shortAnswerHi: 'Access pattern se shuru karo. Jude hue data, integrity rules aur multi-row transactions ke liye relational; jab document hi padhne-likhne ki ikai ho aur shapes badalte hon tab document DB.',
    detailedAnswer: 'Postgres enforces correctness in the database — foreign keys, constraints, multi-row transactions — which you cannot reliably reproduce in application code. That makes it the right default for orders, payments and inventory. Mongo is strong when you know the access pattern up front, documents are read and written whole, and records genuinely differ in shape; sharding is also built in rather than a project. Two things make the answer less binary than people expect: Postgres has JSONB, so "I need flexible fields" alone is rarely a reason to leave SQL, and Mongo has had ACID transactions since 4.0. Plenty of real systems run both — Postgres for money, Mongo for the catalog.',
    detailedAnswerHi: 'Postgres correctness database mein enforce karta hai — foreign keys, constraints, multi-row transactions — jo application code mein bharose se dobara nahi bana sakte. Isliye orders, payments aur inventory ke liye yahi sahi default hai. Mongo tab strong hai jab access pattern pehle se pata ho, documents poore padhe aur likhe jaate hon, aur records ke shapes sach mein alag hon; sharding bhi built-in hai, alag project nahi. Do baatein iss jawab ko binary hone se rokti hain: Postgres mein JSONB hai, isliye sirf "flexible fields chahiye" SQL chhodne ki wajah nahi; aur Mongo mein 4.0 se ACID transactions hain. Kai asli systems dono chalate hain — paise ke liye Postgres, catalog ke liye Mongo.',
    followUps: ['What is CAP theorem?', 'When is a document DB the wrong choice?', 'What does JSONB change?'],
    difficulty: 'MEDIUM',
    tags: ['mongodb', 'database', 'architecture'],
  },
  {
    slug: 'python-mutable-default-q',
    category: 'Python',
    question: 'What is wrong with def f(item, acc=[])?',
    shortAnswer: 'The default list is created once at definition time and shared by every call, so results accumulate across calls.',
    shortAnswerHi: 'Wo default list sirf ek baar, definition ke waqt banti hai aur har call use share karti hai, isliye results ek call se doosri mein jud jaate hain.',
    detailedAnswer: 'Python evaluates default arguments when the def statement executes, not on each call, so a mutable default becomes shared state on the function object. Two independent calls that omit the argument will see each other\'s data. The fix is acc=None with a None check inside. The same trap applies to {} and set(), and to datetime.now() as a default, which freezes to import time. You can see the bound default on f.__defaults__.',
    detailedAnswerHi: 'Python default arguments ko def statement chalte waqt evaluate karta hai, har call par nahi — isliye mutable default function object par shared state ban jata hai. Do alag calls jo wo argument nahi bhejtin, ek doosre ka data dekh lengi. Fix hai acc=None aur andar None check. Yahi trap {} aur set() par bhi hai, aur default mein datetime.now() par bhi, jo import ke waqt hi freeze ho jata hai. Bound default f.__defaults__ mein dikh jata hai.',
    codeExample: `def bad(x, acc=[]): acc.append(x); return acc
print(bad(1), bad(2))     # [1] [1, 2]`,
    followUps: ['When are default arguments evaluated?', 'How do you give a fresh mutable default?', 'What is wrong with datetime.now() as a default?'],
    difficulty: 'MEDIUM',
    tags: ['python', 'gotcha', 'must-know'],
  },
  {
    slug: 'python-gil-q',
    category: 'Python',
    question: 'What is the GIL and when does it matter?',
    shortAnswer: 'Only one thread executes Python bytecode at a time, so threads help I/O-bound work but not CPU-bound work — use multiprocessing for that.',
    shortAnswerHi: 'Ek waqt par sirf ek thread Python bytecode chalata hai, isliye threads I/O-bound kaam mein madad karte hain, CPU-bound mein nahi — uske liye multiprocessing use karo.',
    detailedAnswer: 'The Global Interpreter Lock serialises bytecode execution in CPython. It is released during blocking I/O, so threads and asyncio give real concurrency for network and disk work. For CPU-bound work threads give you nothing, because only one runs at a time — use multiprocessing, a native extension that releases the GIL, or a different runtime. The related production trap is calling a blocking function (time.sleep, requests.get, a synchronous ORM) inside an async def, which stalls the entire event loop rather than just that coroutine.',
    detailedAnswerHi: 'Global Interpreter Lock CPython mein bytecode execution ko ek-ek karke chalata hai. Blocking I/O ke dauraan ye chhod diya jata hai, isliye threads aur asyncio network aur disk ke kaam mein asli concurrency dete hain. CPU-bound kaam mein threads se kuch nahi milta, kyunki ek hi chalta hai — multiprocessing, GIL chhodne wala native extension, ya doosra runtime use karo. Isi se juda production trap hai async def ke andar blocking function call karna (time.sleep, requests.get, synchronous ORM), jo sirf us coroutine ko nahi balki poori event loop ko rok deta hai.',
    followUps: ['asyncio vs threading vs multiprocessing?', 'What happens if you block inside an async function?', 'What is the Python equivalent of Promise.all?'],
    difficulty: 'HARD',
    tags: ['python', 'gil', 'concurrency'],
  },
];
