import type { SeedQuestion } from './questions';

/**
 * The on-ramp.
 *
 * The main bank assumes you already know what an API is. These do not. Every
 * answer here starts from zero and uses something from real life before it uses
 * a technical word — someone on day one should be able to read straight through.
 */
export const basicQuestions: SeedQuestion[] = [
  /* ───────────────────────── How the web works ─────────────────────────── */
  {
    slug: 'basic-what-is-server',
    category: 'Web Basics',
    question: 'What is a server, and what is a client?',
    shortAnswer: 'The client asks, the server answers. Your browser is the client; the computer that sends back the website is the server.',
    shortAnswerHi: 'Client maangta hai, server deta hai. Aapka browser client hai; jo computer website bhejta hai wo server hai.',
    detailedAnswer: 'Think of a restaurant. You are the client — you ask for food. The kitchen is the server — it prepares and hands it over. A server is just a computer that sits somewhere, always switched on, waiting to be asked for things. When you type a website address, your browser sends a request across the internet, the server does whatever work is needed, and sends a reply back. The same computer can be a server for one job and a client for another — your backend is a server to the browser, but a client to the database.',
    detailedAnswerHi: 'Restaurant socho. Aap client ho — aap khana maangte ho. Kitchen server hai — wo banata hai aur de deta hai. Server bas ek computer hai jo kahin rakha hai, hamesha on rehta hai, aur maangne ka intezar karta hai. Aap website ka address type karte ho, browser internet se request bhejta hai, server jo kaam chahiye wo karta hai, aur jawab wapas bhej deta hai. Ek hi computer ek kaam mein server aur doosre mein client ho sakta hai — aapka backend browser ke liye server hai, par database ke liye client.',
    followUps: ['What is localhost?', 'What is an IP address?', 'Can one computer be both?'],
    difficulty: 'EASY',
    tags: ['basics', 'web', 'beginner'],
  },
  {
    slug: 'basic-what-is-api',
    category: 'Web Basics',
    question: 'What is an API?',
    shortAnswer: 'A menu of things one program will do for another. You order from the menu; you never enter the kitchen.',
    shortAnswerHi: 'Ek menu jo batata hai ki ek program doosre ke liye kya kar sakta hai. Aap menu se order karte ho; kitchen mein kabhi nahi jaate.',
    detailedAnswer: 'API stands for Application Programming Interface, but the name explains nothing. Think of a restaurant menu. It lists exactly what you can order and what you will get. You do not walk into the kitchen and cook — you place an order through the waiter. An API is that menu for programs: it lists the things you can ask for ("give me user 5", "create an order"), and hides how they actually happen. That hiding is the point. The kitchen can change its stove, its recipe, its staff — as long as the menu stays the same, your order still works.',
    detailedAnswerHi: 'API ka matlab hai Application Programming Interface, par is naam se kuch samajh nahi aata. Restaurant ka menu socho. Usme likha hai aap kya order kar sakte ho aur kya milega. Aap kitchen mein ghus kar khud nahi pakate — waiter ke through order dete ho. API programs ke liye wahi menu hai: usme likha hai aap kya maang sakte ho ("user 5 do", "order banao"), aur ye chhupa hota hai ki wo hota kaise hai. Chhupana hi asli maksad hai. Kitchen apna chulha, recipe, staff badal sakti hai — jab tak menu same hai, aapka order chalta rahega.',
    followUps: ['What is a REST API?', 'What is an endpoint?', 'Why not let the client touch the database directly?'],
    difficulty: 'EASY',
    tags: ['basics', 'api', 'beginner'],
  },
  {
    slug: 'basic-what-is-http',
    category: 'Web Basics',
    question: 'What is HTTP, and what does HTTPS add?',
    shortAnswer: 'HTTP is the language browsers and servers use to talk. HTTPS is the same language, but scrambled so nobody in between can read it.',
    shortAnswerHi: 'HTTP wo bhasha hai jisme browser aur server baat karte hain. HTTPS wahi bhasha hai, par aise scramble ki beech wala koi padh na sake.',
    detailedAnswer: 'Every time you open a website, your browser sends a message in a fixed format: what it wants, from where, and some extra notes. The server replies in the same format. That agreed format is HTTP. Plain HTTP is like sending a postcard — anyone handling it on the way can read it, and the wifi you are on counts as "on the way". HTTPS puts the postcard inside a sealed, scrambled envelope. Only your browser and that server can read it. That is why login pages must be HTTPS: on plain HTTP your password travels readable.',
    detailedAnswerHi: 'Jab bhi aap website kholte ho, browser ek tay format mein message bhejta hai: use kya chahiye, kahan se, aur kuch extra notes. Server usi format mein jawab deta hai. Wahi tay format HTTP hai. Plain HTTP postcard bhejne jaisa hai — raste mein jo bhi use chhue wo padh sakta hai, aur aapka wifi bhi "raste" mein hi hai. HTTPS us postcard ko seal kiye hue scramble lifafe mein daal deta hai. Sirf aapka browser aur wo server padh sakte hain. Isiliye login pages HTTPS hone chahiye: plain HTTP par aapka password padhne layak jata hai.',
    followUps: ['What is in a request?', 'What is a header?', 'What breaks if a login page is HTTP?'],
    difficulty: 'EASY',
    tags: ['basics', 'http', 'beginner'],
  },
  {
    slug: 'basic-what-is-json',
    category: 'Web Basics',
    question: 'What is JSON and why is it used everywhere?',
    shortAnswer: 'A simple text format for data that both humans and every programming language can read.',
    shortAnswerHi: 'Data likhne ka simple text format jise insaan bhi padh sakta hai aur har programming language bhi.',
    detailedAnswer: 'Computers need an agreed way to write down data so another computer can read it back. JSON is that format, and it won because it is just text with a few rules: curly braces for a thing, square brackets for a list, quotes around names. Your Node app can send JSON to a Python app to a mobile app and all three understand it. It looks like a JavaScript object because that is where it came from, but every language can read it now.',
    detailedAnswerHi: 'Computers ko data likhne ka ek tay tareeka chahiye taaki doosra computer use padh sake. JSON wahi format hai, aur ye isliye jeeta kyunki ye bas text hai kuch rules ke saath: ek cheez ke liye curly braces, list ke liye square brackets, naam ke aas-paas quotes. Aapka Node app JSON bhej sakta hai Python app ko, wo mobile app ko, aur teeno samajh lete hain. Ye JavaScript object jaisa dikhta hai kyunki wahin se aaya hai, par ab har language ise padh leti hai.',
    codeExample: `{
  "name": "Jay",
  "age": 24,
  "skills": ["JavaScript", "SQL"],
  "active": true
}`,
    followUps: ['JSON vs a JavaScript object?', 'What does JSON.stringify do?', 'What cannot go into JSON?'],
    difficulty: 'EASY',
    tags: ['basics', 'json', 'beginner'],
  },
  {
    slug: 'basic-frontend-backend',
    category: 'Web Basics',
    question: 'What is the difference between frontend and backend?',
    shortAnswer: 'Frontend is what you see and click. Backend is what stores the data and does the real work, out of sight.',
    shortAnswerHi: 'Frontend wo hai jo aap dekhte aur click karte ho. Backend wo hai jo data rakhta hai aur asli kaam karta hai, nazar ke peeche.',
    detailedAnswer: 'A shop has a counter and a storeroom. The counter is the frontend — displays, buttons, the person you talk to. The storeroom is the backend — where stock actually lives and where records are kept. Customers never go into the storeroom. In an app: the frontend runs in your browser (HTML, CSS, JavaScript, React) and the backend runs on a server (Node, Python, a database). Full stack simply means you can work on both. The important consequence: anything in the frontend can be seen and changed by the user, so passwords, secret keys and real permission checks must live in the backend.',
    detailedAnswerHi: 'Dukaan mein ek counter hota hai aur ek store room. Counter frontend hai — display, buttons, jisse aap baat karte ho. Store room backend hai — jahan asli saamaan aur record rehta hai. Customers store room mein nahi jaate. App mein: frontend aapke browser mein chalta hai (HTML, CSS, JavaScript, React) aur backend server par (Node, Python, database). Full stack ka matlab bas ye hai ki aap dono par kaam kar sakte ho. Zaroori natija: frontend ka sab kuch user dekh aur badal sakta hai, isliye passwords, secret keys aur asli permission checks backend mein hi hone chahiye.',
    followUps: ['Why can the frontend never be trusted?', 'Where do secret keys belong?', 'What is full stack?'],
    difficulty: 'EASY',
    tags: ['basics', 'beginner'],
  },
  {
    slug: 'basic-localhost-port',
    category: 'Web Basics',
    question: 'What is localhost, and what is a port?',
    shortAnswer: 'localhost means "this computer". A port is a numbered door on it, so several programs can accept visitors at once.',
    shortAnswerHi: 'localhost matlab "yahi computer". Port us par ek numbered darwaza hai, taaki kai programs ek saath visitors le sakein.',
    detailedAnswer: 'localhost always means the machine you are sitting at — nothing goes out to the internet. It is how you test before anyone else can see your work. A port is a door number on that machine. Your computer has one address, but many programs may want to receive traffic, so each takes a different door: your API on 4000, your website on 5173, your database on 5433. That is why "port already in use" happens — two programs tried to stand at the same door. Either stop the first one or move the second to another number.',
    detailedAnswerHi: 'localhost hamesha wahi machine hai jispar aap baithe ho — kuch bhi internet par nahi jata. Yahi tareeka hai kaam test karne ka, kisi aur ke dekhne se pehle. Port us machine par darwaze ka number hai. Computer ka ek hi address hai, par kai programs traffic lena chahte hain, isliye har ek alag darwaza leta hai: API 4000 par, website 5173 par, database 5433 par. Isiliye "port already in use" aata hai — do programs ek hi darwaze par khade ho gaye. Ya pehle ko band karo ya doosre ka number badlo.',
    followUps: ['How do you find what is using a port?', 'Why does 127.0.0.1 mean the same thing?'],
    difficulty: 'EASY',
    tags: ['basics', 'beginner'],
  },

  /* ─────────────────────── JavaScript, from zero ────────────────────────── */
  {
    slug: 'basic-js-variables',
    category: 'JavaScript',
    question: 'What is a variable, and should I use let or const?',
    shortAnswer: 'A named box holding a value. Use const by default; use let only when you need to put something different in the box later.',
    shortAnswerHi: 'Ek naam wala dabba jisme value rakhi hai. Default const use karo; let tabhi jab baad mein dabbe mein kuch aur rakhna ho.',
    detailedAnswer: 'A variable gives a name to a value so you can use it later. const means you cannot swap the box for a different box. let means you can. Start with const everywhere — when a reader sees const they know that name will never point at something else, which is one less thing to track. One point that confuses beginners: const stops you replacing the box, not changing what is inside it. const arr = [] still allows arr.push(1), because the box is still the same box.',
    detailedAnswerHi: 'Variable ek value ko naam de deta hai taaki baad mein use kar sako. const ka matlab hai dabba badal nahi sakte. let ka matlab hai badal sakte ho. Har jagah const se shuru karo — const dekhte hi padhne wale ko pata chal jata hai ki ye naam kabhi kisi aur cheez par nahi jayega, ek cheez kam yaad rakhni padi. Ek baat jo beginners ko confuse karti hai: const dabba badalne se rokta hai, andar ki cheez badalne se nahi. const arr = [] ke baad bhi arr.push(1) chalta hai, kyunki dabba wahi hai.',
    codeExample: `const name = "Jay";     // never points anywhere else
let score = 0;          // will change
score = 10;             // fine
const list = [];
list.push(1);           // fine — same box, new contents`,
    followUps: ['Why avoid var?', 'Does const make an array immutable?'],
    difficulty: 'EASY',
    tags: ['basics', 'javascript', 'beginner'],
  },
  {
    slug: 'basic-js-equality',
    category: 'JavaScript',
    question: 'What is the difference between == and ===?',
    shortAnswer: '=== compares value and type. == converts types first, which produces surprises. Always use ===.',
    shortAnswerHi: '=== value aur type dono compare karta hai. == pehle type badal deta hai, jisse ajeeb results aate hain. Hamesha === use karo.',
    detailedAnswer: 'Think of comparing the number 5 with the text "5". === says "one is a number, one is text — not equal". == says "let me convert them first" and then calls them equal. That helpfulness is the problem: the conversion rules are complicated and produce results nobody expects, like "" == 0 being true. Use === everywhere. The one place == is genuinely useful is x == null, which is a neat shorthand for "null or undefined".',
    detailedAnswerHi: 'Number 5 aur text "5" compare karna socho. === kehta hai "ek number hai, ek text — barabar nahi". == kehta hai "pehle main convert kar deta hoon" aur phir barabar bata deta hai. Yahi madad problem hai: conversion ke rules complicated hain aur aise results dete hain jinki koi umeed nahi karta, jaise "" == 0 ka true hona. Har jagah === use karo. == sirf ek jagah sach mein kaam ka hai — x == null, jo "null ya undefined" ka achha shortcut hai.',
    codeExample: `5 === "5"    // false — different types ✅
5 ==  "5"    // true  — converted first ⚠️
"" == 0      // true  ⚠️ surprising
null == undefined   // true — the one useful case`,
    followUps: ['What is type coercion?', 'null vs undefined?'],
    difficulty: 'EASY',
    tags: ['basics', 'javascript', 'beginner'],
  },
  {
    slug: 'basic-js-function',
    category: 'JavaScript',
    question: 'What is a function, and what is an arrow function?',
    shortAnswer: 'A reusable block of code with a name. An arrow function is a shorter way to write one.',
    shortAnswerHi: 'Dobara use hone wala code ka block, jiska naam hota hai. Arrow function use likhne ka chhota tareeka hai.',
    detailedAnswer: 'A function is a recipe: you write the steps once and follow them whenever you need. It can take ingredients (parameters) and hand back a result (return). Without functions you would copy the same lines everywhere, and fixing a bug would mean fixing it in ten places. Arrow functions are the same idea in fewer characters, and they are the usual choice for small one-line helpers passed into things like map and filter. The one real difference — arrows handle `this` differently — matters later, not on day one.',
    detailedAnswerHi: 'Function ek recipe hai: steps ek baar likho aur jab chahiye tab follow karo. Ye saamaan le sakta hai (parameters) aur result wapas de sakta hai (return). Functions ke bina wahi lines har jagah copy karni padti, aur ek bug theek karne ka matlab hota das jagah theek karna. Arrow functions wahi cheez kam characters mein hain, aur chhote one-line helpers ke liye normal choice hain jo map aur filter mein diye jaate hain. Ek asli farq — arrows `this` ko alag handle karte hain — baad mein matter karta hai, pehle din nahi.',
    codeExample: `function add(a, b) { return a + b; }   // normal
const add = (a, b) => a + b;           // arrow, same thing
[1, 2, 3].map(n => n * 2);             // where arrows shine`,
    followUps: ['What is a parameter vs an argument?', 'When does the arrow function difference matter?'],
    difficulty: 'EASY',
    tags: ['basics', 'javascript', 'beginner'],
  },
  {
    slug: 'basic-js-array-object',
    category: 'JavaScript',
    question: 'What is the difference between an array and an object?',
    shortAnswer: 'An array is a numbered list. An object is a set of labelled fields.',
    shortAnswerHi: 'Array ek numbered list hai. Object labelled fields ka set hai.',
    detailedAnswer: 'Use an array when you have many of the same kind of thing and order matters — a list of students, a list of products. You reach items by position: students[0]. Use an object when you have one thing with several named details — a student who has a name, an age and a city. You reach values by label: student.name. They combine constantly in real code: a list of students is an array of objects, and that is the shape almost every API returns.',
    detailedAnswerHi: 'Array tab use karo jab ek hi tarah ki bahut cheezein hon aur order matter kare — students ki list, products ki list. Items position se milte hain: students[0]. Object tab jab ek cheez ho jiski kai named details hon — ek student jiska naam, umar aur city hai. Values label se milti hain: student.name. Asli code mein ye lagatar saath aate hain: students ki list matlab objects ka array, aur lagbhag har API yahi shape lautata hai.',
    codeExample: `const scores = [90, 85, 70];              // array — by position
const student = { name: "Jay", age: 24 }; // object — by label

const students = [                        // both together
  { name: "Jay", age: 24 },
  { name: "Riya", age: 28 },
];`,
    followUps: ['How do you loop over each?', 'What is an array of objects?'],
    difficulty: 'EASY',
    tags: ['basics', 'javascript', 'beginner'],
  },
  {
    slug: 'basic-js-null-undefined',
    category: 'JavaScript',
    question: 'What is the difference between null and undefined?',
    shortAnswer: 'undefined means nobody has put anything there yet. null means somebody deliberately put "nothing" there.',
    shortAnswerHi: 'undefined matlab abhi tak kisi ne kuch rakha hi nahi. null matlab kisi ne jaan-boojh kar "kuch nahi" rakha hai.',
    detailedAnswer: 'undefined is what JavaScript gives you by default: a variable you declared but never assigned, a function parameter nobody passed, a property that does not exist on an object. It means "this was never filled in". null is what a developer writes on purpose to say "this is intentionally empty" — for example, a user with no profile picture. The practical difference in interviews: undefined usually means you forgot something, null usually means you decided something.',
    detailedAnswerHi: 'undefined wo hai jo JavaScript by default deta hai: aisa variable jo declare kiya par value nahi di, aisa parameter jo kisi ne bheja hi nahi, aisi property jo object mein hai hi nahi. Matlab "ye kabhi bhara hi nahi gaya". null wo hai jo developer jaan-boojh kar likhta hai — "ye khaali rakha gaya hai" — jaise bina profile picture wala user. Interview mein practical farq: undefined ka matlab aksar aap kuch bhool gaye, null ka matlab aapne kuch tay kiya.',
    followUps: ['Why is typeof null "object"?', 'How do you check for both at once?'],
    difficulty: 'EASY',
    tags: ['basics', 'javascript', 'beginner'],
  },
  {
    slug: 'basic-js-loop-array',
    category: 'JavaScript',
    question: 'How do you go through every item in an array?',
    shortAnswer: 'for...of to just visit each one, map to build a changed copy, filter to keep some, find to get the first match.',
    shortAnswerHi: 'Sirf dekhna ho to for...of, badla hua copy banana ho to map, kuch rakhne ho to filter, pehla match chahiye to find.',
    detailedAnswer: 'Pick the one that matches your intention, because the name then documents the code. for...of when you just want to do something with each item. map when you want a new array of the same length with each item transformed. filter when you want a shorter array containing only some items. find when you want one item and can stop looking. The most common beginner mistake is using map when nothing is being built — that creates an array you throw away, and misleads the next reader into looking for a result.',
    detailedAnswerHi: 'Wahi chuno jo aapke iraade se milta ho, kyunki phir naam hi code samjha deta hai. for...of jab bas har item ke saath kuch karna ho. map jab utni hi lambi nayi array chahiye jisme har item badla ho. filter jab chhoti array chahiye jisme kuch hi items hon. find jab ek item chahiye aur wahin ruk jana ho. Beginners ki sabse common galti hai map use karna jab kuch bana hi nahi rahe — isse ek array banti hai jo phenk di jaati hai, aur agla padhne wala result dhoondhta reh jata hai.',
    codeExample: `const nums = [1, 2, 3, 4];
for (const n of nums) console.log(n);   // just visit
nums.map(n => n * 2);                   // [2, 4, 6, 8]
nums.filter(n => n % 2 === 0);          // [2, 4]
nums.find(n => n > 2);                  // 3`,
    followUps: ['forEach vs map?', 'What does reduce do?'],
    difficulty: 'EASY',
    tags: ['basics', 'javascript', 'arrays', 'beginner'],
  },

  /* ─────────────────────────── Node, from zero ─────────────────────────── */
  {
    slug: 'basic-what-is-node',
    category: 'Node.js',
    question: 'What is Node.js?',
    shortAnswer: 'JavaScript running outside the browser, on your computer or a server — so it can read files, use a database and be a backend.',
    shortAnswerHi: 'Browser ke bahar chalta JavaScript, aapke computer ya server par — isliye wo files padh sakta hai, database use kar sakta hai, aur backend ban sakta hai.',
    detailedAnswer: 'JavaScript was originally trapped inside web pages. It could change what you see on a page and nothing more — no reading files, no talking to a database. Node took the engine out of the browser and let it run directly on a computer, adding the abilities the browser deliberately withheld. The practical result is that you can write your frontend and your backend in the same language, so what you learn on one side transfers to the other.',
    detailedAnswerHi: 'JavaScript pehle web pages ke andar hi kaid tha. Wo page par dikhne wali cheezein badal sakta tha, bas — na files padh sakta tha, na database se baat kar sakta tha. Node ne engine ko browser se bahar nikaal kar seedha computer par chalaya, aur wo abilities di jo browser jaan-boojh kar nahi deta. Practical natija ye hai ki aap frontend aur backend dono ek hi language mein likh sakte ho, isliye ek taraf seekha hua doosri taraf kaam aata hai.',
    followUps: ['Is Node a language or a framework?', 'What can Node do that browser JS cannot?'],
    difficulty: 'EASY',
    tags: ['basics', 'nodejs', 'beginner'],
  },
  {
    slug: 'basic-npm-package-json',
    category: 'Node.js',
    question: 'What are npm, package.json and node_modules?',
    shortAnswer: 'npm downloads code other people wrote. package.json is your shopping list. node_modules is the cupboard where it all lands.',
    shortAnswerHi: 'npm doosron ka likha code download karta hai. package.json aapki shopping list hai. node_modules wo almari hai jahan sab aa kar girta hai.',
    detailedAnswer: 'You do not write everything yourself. npm is a huge public store of ready-made code, and npm install fetches what you asked for. package.json is the list of what your project needs, along with its name and its commands. node_modules is the folder where the downloaded code physically sits — it is often enormous, and it is never committed to git, because anyone can rebuild it from package.json. That is the whole point of the list: share the list, not the cupboard.',
    detailedAnswerHi: 'Aap sab kuch khud nahi likhte. npm ready-made code ki ek badi public dukaan hai, aur npm install wo le aata hai jo aapne maanga. package.json us list ka naam hai jo batati hai project ko kya chahiye, saath mein naam aur commands. node_modules wo folder hai jahan download hua code sach mein padta hai — wo aksar bahut bada hota hai, aur use kabhi git mein commit nahi karte, kyunki koi bhi use package.json se dobara bana sakta hai. List ka poora maksad yahi hai: list share karo, almari nahi.',
    codeExample: `npm install express     # adds it to package.json AND node_modules
npm install            # rebuild node_modules from package.json
npm run dev            # run a command defined in package.json`,
    followUps: ['Why is node_modules in .gitignore?', 'What is package-lock.json?', 'dependencies vs devDependencies?'],
    difficulty: 'EASY',
    tags: ['basics', 'nodejs', 'npm', 'beginner'],
  },
  {
    slug: 'basic-env-file',
    category: 'Node.js',
    question: 'What is a .env file and why is it not committed?',
    shortAnswer: 'It holds secrets and settings — passwords, API keys, the database address. It stays out of git so secrets are never published.',
    shortAnswerHi: 'Ismein secrets aur settings hote hain — passwords, API keys, database ka address. Ye git se bahar rehti hai taaki secrets kabhi public na hon.',
    detailedAnswer: 'Your code needs values that differ between your laptop and the real server, and some of them are secret. Putting them straight in the code means two problems: you would have to edit code to deploy, and anyone who sees the code sees your database password. A .env file keeps them separate, and .gitignore keeps that file off GitHub. Teams commit a .env.example instead, listing the names with fake values so a new person knows what to fill in. If a secret is ever pushed by accident, deleting it is not enough — git remembers history, so it must be rotated.',
    detailedAnswerHi: 'Aapke code ko aisi values chahiye jo laptop aur asli server par alag hoti hain, aur kuch secret hoti hain. Unhe seedha code mein rakhne se do problem: deploy karne ke liye code badalna padega, aur jo code dekhega use aapka database password dikh jayega. .env file unhe alag rakhti hai, aur .gitignore us file ko GitHub se door rakhti hai. Teams uski jagah .env.example commit karti hain, jisme naam aur nakli values hoti hain taaki naye bande ko pata chale kya bharna hai. Galti se secret push ho jaye to use delete karna kaafi nahi — git history yaad rakhta hai, isliye use badalna zaroori hai.',
    followUps: ['What goes in .env.example?', 'What do you do if a key gets pushed?'],
    difficulty: 'EASY',
    tags: ['basics', 'nodejs', 'security', 'beginner'],
  },
  {
    slug: 'basic-sync-async',
    category: 'JavaScript',
    question: 'What does asynchronous mean?',
    shortAnswer: 'Starting something slow and carrying on with other work instead of standing still until it finishes.',
    shortAnswerHi: 'Koi dheemi cheez shuru karke doosra kaam karte rehna, uske khatam hone tak khade rehne ki jagah.',
    detailedAnswer: 'Some things take time — fetching data over the internet, reading a big file, querying a database. Synchronous means everything stops until that finishes. Asynchronous means the program says "start it, tell me when it is done" and keeps going. Put the tea on the stove and do your homework; do not stare at the kettle. This matters enormously on a server: if one slow database query froze everything, one user would block everyone else. Async is why one Node process can serve thousands of people.',
    detailedAnswerHi: 'Kuch cheezein waqt leti hain — internet se data laana, badi file padhna, database se poochhna. Synchronous ka matlab hai us cheez ke khatam hone tak sab kuch ruka rahega. Asynchronous ka matlab hai program kehta hai "shuru karo, khatam ho to bata dena" aur aage badh jata hai. Chai gas par rakho aur homework karo; kettle ko ghoorte mat raho. Server par ye bahut matter karta hai: ek dheemi database query sab kuch roke to ek user baaki sabko block kar dega. Isi wajah se ek Node process hazaron logon ko sambhal leta hai.',
    followUps: ['What is a promise?', 'What does await do?', 'What is a callback?'],
    difficulty: 'EASY',
    tags: ['basics', 'async', 'beginner'],
  },

  /* ───────────────────────── Databases, from zero ──────────────────────── */
  {
    slug: 'basic-what-is-database',
    category: 'Database',
    question: 'What is a database and why not just use files?',
    shortAnswer: 'A program built to store and find data fast, safely, with many people using it at once. Files give you none of that.',
    shortAnswerHi: 'Aisa program jo data tez aur safely store aur dhoondhta hai, aur kai log ek saath use kar sakte hain. Files ye kuch nahi deti.',
    detailedAnswer: 'You could save everything into a text file. It works for ten users and falls apart after that. Finding one user means reading the entire file. Two people saving at the same moment can corrupt it. A crash halfway through a save leaves it broken. A database solves exactly these: indexes so it can find one row without reading everything, locking so simultaneous writes do not clash, and transactions so a half-finished change is undone rather than left broken.',
    detailedAnswerHi: 'Aap sab kuch ek text file mein save kar sakte ho. Das users tak chalega, uske baad bikhar jayega. Ek user dhoondhne ke liye poori file padhni padegi. Do log ek hi waqt par save karein to file kharab ho sakti hai. Save ke beech mein crash ho jaye to toot jaati hai. Database bilkul yahi solve karta hai: indexes taaki ek row bina sab padhe mil jaye, locking taaki ek saath ki writes takrayein nahi, aur transactions taaki aadha hua badlav undo ho jaye, toota hua na chhoote.',
    followUps: ['What is a table?', 'What is an index?', 'SQL vs NoSQL?'],
    difficulty: 'EASY',
    tags: ['basics', 'database', 'beginner'],
  },
  {
    slug: 'basic-table-row-column',
    category: 'Database',
    question: 'What are tables, rows and columns?',
    shortAnswer: 'A table is a sheet. Columns are its headings. Each row is one record.',
    shortAnswerHi: 'Table ek sheet hai. Columns uski headings. Har row ek record.',
    detailedAnswer: 'Picture an Excel sheet. The sheet is a table — you would have one for users, one for products, one for orders. The headings across the top are columns: id, name, email. Each line underneath is a row: one actual user. The difference from Excel is that the database enforces the rules — if a column is set to hold numbers, it will refuse text, and refuse a row missing a required value. Excel would happily let you make a mess.',
    detailedAnswerHi: 'Excel sheet socho. Sheet ek table hai — ek users ke liye, ek products ke liye, ek orders ke liye. Upar wali headings columns hain: id, name, email. Neeche har line ek row hai: ek asli user. Excel se farq ye hai ki database rules lagata hai — column numbers ka hai to wo text mana kar dega, aur aisi row bhi mana karega jisme zaroori value nahi hai. Excel to aaram se gadbad karne deta.',
    followUps: ['What is a primary key?', 'What is a foreign key?'],
    difficulty: 'EASY',
    tags: ['basics', 'database', 'sql', 'beginner'],
  },
  {
    slug: 'basic-primary-key',
    category: 'SQL',
    question: 'What is a primary key?',
    shortAnswer: 'The column that uniquely identifies each row — like a roll number. Never repeats, never empty.',
    shortAnswerHi: 'Wo column jo har row ko unique pehchaan deta hai — roll number jaisa. Na repeat hota hai, na khaali.',
    detailedAnswer: 'Two students can share a name, so a name cannot identify them. A roll number can, because no two students have the same one. A primary key is that roll number for a table. Almost always it is an id column the database fills in for you. A common beginner instinct is to use email as the key, which seems reasonable — until someone changes their email. A primary key should never change, because other tables point at it. Give every table a plain id and keep email as an ordinary unique column.',
    detailedAnswerHi: 'Do students ka naam same ho sakta hai, isliye naam se pehchaan nahi hoti. Roll number se hoti hai, kyunki wo kisi do ka same nahi hota. Primary key table ka wahi roll number hai. Lagbhag hamesha ye ek id column hota hai jo database khud bhar deta hai. Beginners ko lagta hai email ko key bana do — theek lagta hai, jab tak koi apna email na badle. Primary key kabhi badalni nahi chahiye, kyunki doosri tables usi par ishara karti hain. Har table ko ek simple id do aur email ko normal unique column rehne do.',
    followUps: ['Why not use email?', 'What is a foreign key?', 'Can a table have two primary keys?'],
    difficulty: 'EASY',
    tags: ['basics', 'sql', 'beginner'],
  },
  {
    slug: 'basic-crud',
    category: 'SQL',
    question: 'What is CRUD?',
    shortAnswer: 'Create, Read, Update, Delete — the four things you do to data. In SQL: INSERT, SELECT, UPDATE, DELETE.',
    shortAnswerHi: 'Create, Read, Update, Delete — data ke saath hone wale chaar kaam. SQL mein: INSERT, SELECT, UPDATE, DELETE.',
    detailedAnswer: 'Almost every app is these four operations over and over. Add a user, show the users, change a user, remove a user. Once you see it, most backend work is recognisably CRUD with rules layered on top. In SQL they are INSERT, SELECT, UPDATE, DELETE. Over HTTP they are POST, GET, PUT/PATCH, DELETE. Two of them are dangerous: UPDATE and DELETE without a WHERE clause will change or erase every row in the table. Run the SELECT with the same WHERE first, see what comes back, then run the real one.',
    detailedAnswerHi: 'Lagbhag har app yahi chaar kaam baar-baar karti hai. User jodo, users dikhao, user badlo, user hatao. Ek baar dikhne lage to zyadatar backend kaam CRUD hi lagta hai, upar kuch rules ke saath. SQL mein ye INSERT, SELECT, UPDATE, DELETE hain. HTTP par POST, GET, PUT/PATCH, DELETE. Inme se do khatarnak hain: WHERE ke bina UPDATE aur DELETE table ki har row badal ya mita denge. Pehle usi WHERE ke saath SELECT chalao, dekho kya aata hai, phir asli chalao.',
    codeExample: `INSERT INTO users (name) VALUES ('Jay');   -- Create
SELECT * FROM users WHERE id = 1;          -- Read
UPDATE users SET name='Riya' WHERE id = 1; -- Update  ⚠️ never without WHERE
DELETE FROM users WHERE id = 1;            -- Delete  ⚠️ never without WHERE`,
    followUps: ['What happens if you forget WHERE?', 'How does CRUD map to HTTP methods?'],
    difficulty: 'EASY',
    tags: ['basics', 'sql', 'crud', 'beginner'],
  },
  {
    slug: 'basic-what-is-index-simple',
    category: 'SQL',
    question: 'What is a database index, in plain terms?',
    shortAnswer: 'The index page at the back of a book. Without it the database reads every row to find one.',
    shortAnswerHi: 'Kitaab ke peeche ka index page. Uske bina database ek row dhoondhne ke liye saari rows padhta hai.',
    detailedAnswer: 'To find one word in a 900-page book you could read every page, or you could look at the index and jump straight to page 412. A database index is that index page. Without one, finding a single user in a million rows means reading all million. But an index is not free: every time you add a row, the index must be updated too. So indexes make reading fast and writing slightly slower — which is why you index the columns you search by, not every column.',
    detailedAnswerHi: '900 page ki kitaab mein ek shabd dhoondhne ke liye ya to har page padho, ya index dekho aur seedha page 412 par jao. Database ka index wahi index page hai. Uske bina das lakh rows mein ek user dhoondhna matlab saari das lakh padhna. Par index muft nahi hai: har nayi row par index bhi update karna padta hai. Isliye indexes reading tez aur writing thodi dheemi karte hain — yahi wajah hai ki index un columns par lagate hain jinpar search karte ho, har column par nahi.',
    followUps: ['When does an index hurt?', 'How do you know if a query used one?'],
    difficulty: 'EASY',
    tags: ['basics', 'sql', 'indexes', 'beginner'],
  },

  /* ────────────────────────── REST & HTTP basics ───────────────────────── */
  {
    slug: 'basic-get-vs-post',
    category: 'REST API',
    question: 'What is the difference between GET and POST?',
    shortAnswer: 'GET asks for something and changes nothing. POST sends data to create or change something.',
    shortAnswerHi: 'GET kuch maangta hai aur kuch badalta nahi. POST data bhejta hai kuch banane ya badalne ke liye.',
    detailedAnswer: 'GET is reading: opening a page, fetching a list. It should never change anything on the server, which is why refreshing a GET is always safe and browsers may cache it. Its data rides in the URL, so it is visible in history and server logs — never put a password there. POST is writing: submitting a form, creating an order. Its data goes in the body, not the URL. And POST is not safe to repeat — that is exactly why browsers warn you before resubmitting a form, and why pressing "Pay" twice can charge you twice.',
    detailedAnswerHi: 'GET padhna hai: page kholna, list laana. Ise server par kuch badalna nahi chahiye, isiliye GET refresh karna hamesha safe hai aur browsers use cache kar sakte hain. Iska data URL mein jata hai, isliye history aur server logs mein dikhta hai — password wahan kabhi mat daalo. POST likhna hai: form bhejna, order banana. Iska data body mein jata hai, URL mein nahi. Aur POST dohraana safe nahi hai — isiliye browser form dobara bhejne se pehle warning deta hai, aur "Pay" do baar dabane se do baar paise kat sakte hain.',
    followUps: ['PUT vs PATCH?', 'Why is POST not idempotent?', 'Why should passwords never be in a URL?'],
    difficulty: 'EASY',
    tags: ['basics', 'rest', 'http', 'beginner'],
  },
  {
    slug: 'basic-status-codes',
    category: 'REST API',
    question: 'What do status codes like 200, 404 and 500 mean?',
    shortAnswer: '2xx worked, 4xx you made a mistake, 5xx the server made a mistake.',
    shortAnswerHi: '2xx ho gaya, 4xx aapki galti, 5xx server ki galti.',
    detailedAnswer: 'The first digit tells you almost everything. 2xx means success — 200 is a normal OK, 201 means something was created. 4xx means the request was wrong: 400 the server could not understand it, 401 you are not logged in, 403 you are logged in but not allowed, 404 no such thing exists. 5xx means the server broke while handling a perfectly valid request — that is a bug on the backend, not the caller\'s fault. The 401-versus-403 distinction gets asked constantly: 401 is "who are you?", 403 is "I know who you are, and no".',
    detailedAnswerHi: 'Pehla digit lagbhag sab bata deta hai. 2xx matlab success — 200 normal OK, 201 matlab kuch bana. 4xx matlab request galat thi: 400 server samajh nahi paya, 401 aap logged in nahi ho, 403 logged in ho par ijazat nahi, 404 aisi cheez hai hi nahi. 5xx matlab bilkul sahi request handle karte hue server toot gaya — ye backend ka bug hai, bhejne wale ki galti nahi. 401 vs 403 baar-baar poocha jata hai: 401 "aap kaun ho?", 403 "pata hai aap kaun ho, aur nahi".',
    followUps: ['401 vs 403?', 'When do you use 201?', 'What is 429?'],
    difficulty: 'EASY',
    tags: ['basics', 'rest', 'http', 'beginner'],
  },
  {
    slug: 'basic-query-vs-path-param',
    category: 'REST API',
    question: 'What is the difference between a path parameter and a query parameter?',
    shortAnswer: 'A path parameter identifies which thing. A query parameter adjusts how you want it — filtering, sorting, paging.',
    shortAnswerHi: 'Path parameter batata hai kaun si cheez. Query parameter batata hai kaise chahiye — filter, sort, page.',
    detailedAnswer: 'In /users/5 the 5 is a path parameter — it points at one specific user, and without it the address means something different. In /users?city=Delhi&page=2 the parts after the ? are query parameters — they refine a search but the address still means "users" without them. The simple test: if removing it changes which resource you are talking about, it belongs in the path; if it only changes how the list is filtered or shown, it belongs in the query.',
    detailedAnswerHi: '/users/5 mein 5 path parameter hai — ye ek khaas user par ishara karta hai, aur uske bina address ka matlab hi badal jata hai. /users?city=Delhi&page=2 mein ? ke baad wale hisse query parameters hain — ye search ko refine karte hain par unke bina bhi address ka matlab "users" hi rehta hai. Simple test: hataane se agar ye badal jaye ki aap kis cheez ki baat kar rahe ho, to wo path mein jayega; agar sirf list ka filter ya dikhne ka tareeka badle, to query mein.',
    codeExample: `GET /users/5                    // path param — WHICH user
GET /users?city=Delhi&page=2    // query params — how to filter`,
    followUps: ['Where does the request body fit in?', 'Why not put a password in a query param?'],
    difficulty: 'EASY',
    tags: ['basics', 'rest', 'beginner'],
  },

  /* ────────────────────────────── Git basics ───────────────────────────── */
  {
    slug: 'basic-what-is-git',
    category: 'Git',
    question: 'What is Git, and how is GitHub different?',
    shortAnswer: 'Git saves versions of your work on your computer. GitHub is a website that hosts those saved versions online.',
    shortAnswerHi: 'Git aapke computer par kaam ke versions save karta hai. GitHub ek website hai jo un versions ko online rakhti hai.',
    detailedAnswer: 'Git is the tool. It remembers every version of your project, so you can see what changed, who changed it, and go back if something breaks — no more "final_v2_FINAL_really.zip". It works completely offline, on your own machine. GitHub is a website that stores a copy of your Git history online, so others can see it and collaborate. Git works fine without GitHub; GitHub is meaningless without Git. Alternatives like GitLab and Bitbucket do the same job.',
    detailedAnswerHi: 'Git ek tool hai. Wo aapke project ka har version yaad rakhta hai, taaki aap dekh sako kya badla, kisne badla, aur kuch toot jaye to wapas ja sako — ab "final_v2_FINAL_really.zip" ki zarurat nahi. Ye poori tarah offline, aapki apni machine par chalta hai. GitHub ek website hai jo aapki Git history ki copy online rakhti hai, taaki doosre dekh sakein aur saath kaam kar sakein. Git GitHub ke bina bhi chalta hai; GitHub Git ke bina bekaar hai. GitLab aur Bitbucket wahi kaam karte hain.',
    followUps: ['What is a commit?', 'What is a branch?', 'What is a remote?'],
    difficulty: 'EASY',
    tags: ['basics', 'git', 'beginner'],
  },
  {
    slug: 'basic-git-commit-push',
    category: 'Git',
    question: 'What do add, commit, push and pull actually do?',
    shortAnswer: 'add chooses what to save, commit saves it locally, push uploads it, pull downloads what others pushed.',
    shortAnswerHi: 'add chunta hai kya save karna hai, commit use locally save karta hai, push upload karta hai, pull doosron ka kiya hua download karta hai.',
    detailedAnswer: 'These four cover almost everything you do daily. git add is packing a box — you choose which changed files go in. git commit seals the box with a label describing what changed; it is now saved on your computer, permanently, and you can always come back to it. git push sends your sealed boxes to GitHub so others can see them. git pull brings down boxes other people pushed. The most common beginner surprise is that commit does not upload anything — it is local until you push.',
    detailedAnswerHi: 'Ye chaar lagbhag rozana ka poora kaam hain. git add dabba pack karna hai — aap chunte ho kaun si badli hui files jayengi. git commit dabbe ko seal karke label lagata hai jisme likha hai kya badla; ab wo aapke computer par pakka save hai aur aap kabhi bhi wapas aa sakte ho. git push aapke seal kiye dabbe GitHub par bhejta hai taaki doosre dekh sakein. git pull wo dabbe le aata hai jo doosron ne push kiye. Beginners ko sabse zyada ye chaunkata hai ki commit kuch upload nahi karta — push tak wo sirf local hota hai.',
    codeExample: `git status              # what changed?
git add .               # pack everything
git commit -m "Add login page"
git push                # upload
git pull                # download what others did`,
    followUps: ['What makes a good commit message?', 'What is the staging area?', 'What if push is rejected?'],
    difficulty: 'EASY',
    tags: ['basics', 'git', 'beginner'],
  },
  {
    slug: 'basic-git-branch',
    category: 'Git',
    question: 'What is a branch and why use one?',
    shortAnswer: 'A separate copy of your work where you can experiment without breaking the version that works.',
    shortAnswerHi: 'Aapke kaam ki alag copy jahan aap experiment kar sakte ho, bina chalte hue version ko tode.',
    detailedAnswer: 'Your main branch should always work. If you build a new feature directly on it and get halfway, main is now broken — and if you need to fix an urgent bug, there is nowhere clean to do it from. A branch is your own copy: experiment freely, and if it goes wrong, delete the branch and nothing is lost. When it works, merge it back into main. This is also how teams avoid stepping on each other — everyone works on their own branch and merges when ready.',
    detailedAnswerHi: 'Aapki main branch hamesha chalni chahiye. Agar aap naya feature seedha usi par banao aur aadha kar do, to main ab tooti hui hai — aur koi urgent bug theek karna ho to saaf jagah bachi hi nahi. Branch aapki apni copy hai: aaram se experiment karo, galat ho jaye to branch delete kar do, kuch nahi gaya. Sahi ho jaye to use main mein merge kar do. Teams isi tareeke se ek doosre ke raste mein nahi aati — har koi apni branch par kaam karta hai aur taiyaar hone par merge karta hai.',
    codeExample: `git switch -c feature/login   # new branch, and go to it
# ...work, commit...
git switch main
git merge feature/login`,
    followUps: ['What is a merge conflict?', 'What is a pull request?', 'merge vs rebase?'],
    difficulty: 'EASY',
    tags: ['basics', 'git', 'beginner'],
  },
  {
    slug: 'basic-merge-conflict',
    category: 'Git',
    question: 'What is a merge conflict and how do you fix it?',
    shortAnswer: 'Two people changed the same lines, so Git cannot decide which to keep. You choose, remove the markers, and commit.',
    shortAnswerHi: 'Do logon ne wahi lines badli, isliye Git tay nahi kar pata kaun si rakhe. Aap chunte ho, markers hataate ho, aur commit karte ho.',
    detailedAnswer: 'Git merges automatically when changes touch different places. When two people edited the same lines, it refuses to guess and marks the spot with <<<<<<< and >>>>>>> showing both versions. Nothing is broken and nothing is lost — Git is asking a question. Open the file, decide what the final code should be (sometimes one side, sometimes a combination), delete the marker lines, then add and commit. The fear beginners have is that a conflict means damage; it does not. It means Git was careful enough not to choose for you.',
    detailedAnswerHi: 'Jab badlav alag-alag jagah hote hain Git khud merge kar leta hai. Jab do logon ne wahi lines badli hon, wo andaza lagane se mana kar deta hai aur us jagah <<<<<<< aur >>>>>>> laga kar dono versions dikha deta hai. Kuch toota nahi, kuch khoya nahi — Git sawaal poochh raha hai. File kholo, tay karo final code kya hona chahiye (kabhi ek taraf, kabhi dono ka mel), marker wali lines hatao, phir add aur commit karo. Beginners ko darr hota hai ki conflict matlab nuksaan; nahi hai. Matlab Git itna dhyan rakhta hai ki aapke liye khud faisla nahi karta.',
    followUps: ['How do you avoid conflicts?', 'What is git merge --abort?'],
    difficulty: 'EASY',
    tags: ['basics', 'git', 'beginner'],
  },

  /* ─────────────────────── Auth & security, from zero ───────────────────── */
  {
    slug: 'basic-authentication-authorization',
    category: 'Authentication',
    question: 'What is the difference between authentication and authorisation?',
    shortAnswer: 'Authentication is proving who you are. Authorisation is what you are allowed to do once you are in.',
    shortAnswerHi: 'Authentication matlab aap kaun ho ye sabit karna. Authorisation matlab andar aane ke baad aap kya kar sakte ho.',
    detailedAnswer: 'Showing your ID at an office entrance is authentication — the guard confirms you are you. But your ID does not open every door inside: the server room may still be off limits. That is authorisation. In an app, logging in authenticates you. Whether you can delete someone else\'s post is authorisation. The mistake that shows up in real security reviews is checking only the first one: the code confirms you are logged in, then loads record 42 without checking it belongs to you — so anyone can read anyone\'s data by changing the number in the URL.',
    detailedAnswerHi: 'Office ke gate par ID dikhana authentication hai — guard confirm karta hai ki aap aap hi ho. Par aapki ID andar ka har darwaza nahi kholti: server room shayad phir bhi band hai. Wahi authorisation hai. App mein login karna aapko authenticate karta hai. Aap kisi aur ki post delete kar sakte ho ya nahi — wo authorisation hai. Asli security reviews mein jo galti milti hai wo yahi hai ki sirf pehla check hota hai: code confirm karta hai ki aap logged in ho, phir record 42 load kar deta hai bina dekhe ki wo aapka hai — isliye koi bhi URL ka number badal kar doosre ka data padh leta hai.',
    followUps: ['Which status code for each?', 'Where should ownership checks live?'],
    difficulty: 'EASY',
    tags: ['basics', 'auth', 'security', 'beginner'],
  },
  {
    slug: 'basic-password-storage',
    category: 'Authentication',
    question: 'How should passwords be stored?',
    shortAnswer: 'Never as-is. Store a scrambled version made by bcrypt or argon2 that cannot be turned back.',
    shortAnswerHi: 'Kabhi jaise ke taise nahi. bcrypt ya argon2 se bana scramble version store karo jo wapas nahi ho sakta.',
    detailedAnswer: 'Assume your database will one day be stolen. If it holds real passwords, everyone who reused that password elsewhere is now in trouble too. So you never store the password. You store a hash — a scrambled output that cannot be reversed. When someone logs in, you scramble what they typed and compare the two scrambles. Use bcrypt or argon2 specifically, because they are deliberately slow: a thief with your database can try only a few guesses per second instead of billions. That slowness is the entire feature, which is why fast hashes like MD5 or SHA-256 are the wrong tool here.',
    detailedAnswerHi: 'Maan kar chalo ki ek din aapka database chori hoga. Usme asli passwords hue to jinhone wahi password kahin aur use kiya hai wo bhi phas gaye. Isliye password kabhi store nahi karte. Aap hash store karte ho — scramble kiya hua output jo wapas nahi ho sakta. Koi login kare to jo usne type kiya use scramble karke dono compare karte ho. bcrypt ya argon2 hi use karo, kyunki wo jaan-boojh kar dheeme hain: chor arbon ki jagah kuch hi guesses per second kar paata hai. Wahi dheemapan poora feature hai, isiliye MD5 ya SHA-256 jaise tez hashes yahan galat tool hain.',
    followUps: ['Why not encrypt instead of hash?', 'What is a salt?', 'Why is bcrypt slow on purpose?'],
    difficulty: 'EASY',
    tags: ['basics', 'auth', 'security', 'beginner'],
  },
  {
    slug: 'basic-what-is-token',
    category: 'Authentication',
    question: 'What is a token, and why do I need one after logging in?',
    shortAnswer: 'HTTP forgets you between requests. A token is the wristband proving you already logged in.',
    shortAnswerHi: 'HTTP har request ke beech aapko bhool jata hai. Token wahi wristband hai jo sabit karta hai ki aap login kar chuke ho.',
    detailedAnswer: 'Each HTTP request is independent — the server has no memory of the last one. Without something extra, you would have to send your password with every single click. Instead, you log in once and the server hands back a token: a signed string meaning "this person already proved who they are". Your app sends it with each request, and the server verifies the signature. It is a wristband at an event — checked once at the entrance, shown at every stall afterwards. Because a token grants access, it must be treated like a password: sent over HTTPS, stored where scripts cannot read it, and given a short expiry.',
    detailedAnswerHi: 'Har HTTP request alag hoti hai — server ko pichhli yaad nahi rehti. Kuch extra na ho to har click ke saath password bhejna padta. Iski jagah aap ek baar login karte ho aur server ek token deta hai: signed string jiska matlab hai "is bande ne pehle hi sabit kar diya ki wo kaun hai". Aapki app har request ke saath use bhejti hai, aur server signature verify karta hai. Ye event ka wristband hai — gate par ek baar check hua, phir har stall par bas dikhana hai. Token access deta hai, isliye use password jaisa hi samjho: HTTPS par bhejo, aisi jagah rakho jahan scripts na padh sakein, aur expiry chhoti rakho.',
    followUps: ['What is a JWT?', 'Where should a token be stored?', 'What is a refresh token?'],
    difficulty: 'EASY',
    tags: ['basics', 'auth', 'jwt', 'beginner'],
  },

  /* ──────────────────────── Everyday practicalities ─────────────────────── */
  {
    slug: 'basic-cors-error',
    category: 'Web Basics',
    question: 'Why do I keep getting a CORS error?',
    shortAnswer: 'Your frontend and backend are on different addresses, and the backend has not said it allows requests from that frontend.',
    shortAnswerHi: 'Aapka frontend aur backend alag addresses par hain, aur backend ne nahi bola ki wo us frontend se requests allow karta hai.',
    detailedAnswer: 'Browsers block a page on one address from reading a response from another address, unless that other server explicitly permits it. This protects users: without it, a malicious site could quietly read your email in the background. So when your React app on port 5173 calls your API on port 4000, the API must reply with a header saying "5173 is allowed". Two things worth knowing: this is a browser rule only — a script or curl ignores it entirely — and it is never fixed on the frontend. The change always goes in the backend\'s CORS settings.',
    detailedAnswerHi: 'Browser ek address ke page ko doosre address ka jawab padhne se rokta hai, jab tak wo doosra server saaf-saaf ijazat na de. Ye users ko bachata hai: iske bina koi buri site background mein chupchaap aapka email padh leti. Isliye jab aapka React app port 5173 par API ko port 4000 par call karta hai, API ko ek header bhejna hota hai jisme likha ho "5173 allowed hai". Do baatein jaanne layak: ye sirf browser ka rule hai — script ya curl ise poori tarah ignore karte hain — aur ye kabhi frontend par theek nahi hota. Badlav hamesha backend ki CORS settings mein jata hai.',
    followUps: ['Does CORS protect the server?', 'What is a preflight request?'],
    difficulty: 'EASY',
    tags: ['basics', 'cors', 'beginner'],
  },
  {
    slug: 'basic-debugging',
    category: 'Web Basics',
    question: 'My code is not working. How do I debug it?',
    shortAnswer: 'Read the actual error, find the exact line that fails, then check what the values really are — do not guess.',
    shortAnswerHi: 'Asli error padho, wo exact line dhoondho jahan fail ho raha hai, phir dekho values sach mein kya hain — andaza mat lagao.',
    detailedAnswer: 'Most time lost to bugs is lost to guessing. A method that works: read the error message properly — it usually names the file and line. Then narrow down where it breaks by printing values just before that point, and check whether they are what you assumed. Very often the bug is that something is undefined, or a string where you expected a number. Check both sides: the browser console for frontend errors, the terminal for backend errors. And change one thing at a time — changing three things and seeing it work teaches you nothing about which one mattered.',
    detailedAnswerHi: 'Bugs mein sabse zyada waqt andaza lagane mein jata hai. Ek tareeka jo chalta hai: error message dhyan se padho — usme aksar file aur line likhi hoti hai. Phir us jagah se thoda pehle values print karke dekho ki wo wahi hain jo aap maan rahe the. Bahut baar bug bas itna hota hai ki koi cheez undefined hai, ya number ki jagah string hai. Dono taraf dekho: frontend errors ke liye browser console, backend errors ke liye terminal. Aur ek baar mein ek cheez badlo — teen cheezein badal kar chal jaye to pata hi nahi chalta kaun si matter kar rahi thi.',
    followUps: ['Where do backend errors appear?', 'What is a stack trace?'],
    difficulty: 'EASY',
    tags: ['basics', 'debugging', 'beginner'],
  },
  {
    slug: 'basic-what-is-orm',
    category: 'Database',
    question: 'What is an ORM?',
    shortAnswer: 'A translator that lets you work with database rows as normal objects instead of writing SQL by hand.',
    shortAnswerHi: 'Ek translator jo database ki rows ko normal objects ki tarah use karne deta hai, haath se SQL likhne ki jagah.',
    detailedAnswer: 'Your database speaks SQL; your code speaks JavaScript or Python. An ORM sits between them so you can write user.findMany() instead of SELECT * FROM users, and get objects back. The benefits are real — less boilerplate, protection from SQL injection by default, and types that match your schema. The cost is also real: it hides what SQL is actually being run, which is how N+1 query problems slip in unnoticed. The practical stance is to use the ORM for normal work, and know enough SQL to read what it generates when something is slow.',
    detailedAnswerHi: 'Aapka database SQL bolta hai; aapka code JavaScript ya Python. ORM dono ke beech baithta hai taaki aap SELECT * FROM users ki jagah user.findMany() likh sako aur objects wapas mile. Fayde asli hain — kam boilerplate, by default SQL injection se bachav, aur schema se milte hue types. Keemat bhi asli hai: ye chhupa deta hai ki asal mein kaun si SQL chal rahi hai, aur isi wajah se N+1 query problem chupchaap ghus jati hai. Practical soch ye hai ki normal kaam ORM se karo, aur itni SQL jaano ki kuch dheema ho to uski generate ki hui query padh sako.',
    followUps: ['What is N+1?', 'When would you write raw SQL?', 'Prisma vs Sequelize?'],
    difficulty: 'EASY',
    tags: ['basics', 'database', 'orm', 'beginner'],
  },
  {
    slug: 'basic-middleware-simple',
    category: 'Node.js',
    question: 'What is middleware, in simple terms?',
    shortAnswer: 'Code that runs between the request arriving and your route handling it — like security checks before you board a plane.',
    shortAnswerHi: 'Aisa code jo request aane aur aapke route ke sambhalne ke beech chalta hai — plane mein chadhne se pehle ki security checks jaisa.',
    detailedAnswer: 'At an airport you pass through gates in order: ID check, bag scan, boarding pass. Each can let you through or stop you. Middleware is those gates for a request. Common ones read the JSON body, check you are logged in, log the request, or apply a rate limit. Each either calls next() to pass you along or sends a response and stops you there. Order is not cosmetic — it is behaviour. Register the "page not found" handler before your routes and every single request will get a 404.',
    detailedAnswerHi: 'Airport par aap order mein gates se guzarte ho: ID check, bag scan, boarding pass. Har ek aage jaane de sakta hai ya rok sakta hai. Middleware request ke liye wahi gates hain. Aam middleware JSON body padhte hain, check karte hain ki aap logged in ho, request log karte hain, ya rate limit lagate hain. Har ek ya to next() call karke aage bhejta hai ya response bhej kar wahin rok deta hai. Order dikhawa nahi hai — wahi behaviour hai. "Page not found" handler routes se pehle laga do to har request ko 404 milega.',
    followUps: ['What happens if you forget next()?', 'How does an error handler differ?'],
    difficulty: 'EASY',
    tags: ['basics', 'express', 'nodejs', 'beginner'],
  },
];
