import type { TopicTricks } from './topics-tricks';

/**
 * Memory hooks — MongoDB, REST, real-time, auth, system design and tooling.
 *
 * The security hooks lean hardest on narrative, because security rules are the
 * ones people "know" and still get wrong. A rule you can recite is not the same
 * as a rule you act on; a story about how you got robbed changes behaviour, and
 * behaviour is what security depends on.
 */
export const TRICKS_DATA: Record<string, TopicTricks> = {
  /* ═══════════════════════════════ MongoDB ══════════════════════════════════ */

  'mongo-documents': {
    tricks: `### 📄 "A row becomes a document, a table becomes a collection"

The translation table is short enough to learn in one sitting:

| SQL | Mongo |
|---|---|
| table | collection |
| row | document |
| column | field |
| JOIN | \`$lookup\` (or embed instead) |

### 🎭 "Schemaless" is marketing

Mongo does not enforce a schema. **Your application still has one** — it is just written in your code and your head instead of the database.

**Say it:** *"No schema in the database means the schema lives in your bugs."*

That is why Mongoose exists: to put the schema back.

### 🆔 \`_id\` is not a number

It is an **ObjectId** — 12 bytes containing a timestamp, a machine id and a counter.

Two useful consequences: sorting by \`_id\` sorts roughly by **creation time** for free, and ids can be generated by the client without asking the database.

**Why this sticks:** "the schema lives in your bugs" is a *pointed joke*. Humour is one of the most reliable retention aids there is, and it also happens to be true.`,
    tricksHi: `### 📄 "Row document ban jati hai, table collection"

Anuvaad ki table itni chhoti hai ki ek baithak mein seekhi ja sakti hai:

| SQL | Mongo |
|---|---|
| table | collection |
| row | document |
| column | field |
| JOIN | \`$lookup\` (ya embed kar lo) |

### 🎭 "Schemaless" marketing hai

Mongo schema lagu nahi karta. **Aapki application ka schema phir bhi hai** — bas wo database ki jagah aapke code aur dimaag mein likha hai.

**Bolo:** *"Database mein schema nahi hai matlab schema aapke bugs mein rehta hai."*

Isiliye Mongoose hai: schema wapas laane ke liye.

### 🆔 \`_id\` number nahi hai

Ye **ObjectId** hai — 12 bytes jisme timestamp, machine id aur counter hain.

Do kaam ke natije: \`_id\` se sort karo to lagbhag **banne ke waqt** se sort ho jata hai, muft; aur client bina database se poochhe id bana sakta hai.

**Ye kyun tikta hai:** "schema aapke bugs mein rehta hai" ek *chubhta mazaak* hai. Hasi yaad rakhne ke sabse bharosemand tareekon mein se ek hai, aur ye baat sach bhi hai.`,
  },

  'mongo-crud': {
    tricks: `### ✍️ "One or Many — the suffix tells you"

\`insertOne\` / \`insertMany\`, \`updateOne\` / \`updateMany\`, \`deleteOne\` / \`deleteMany\`.

**The dangerous default:** \`updateMany({}, ...)\` with an empty filter hits **every document in the collection**. There is no confirmation and no undo.

**Say it:** *"Empty filter means everything."*

### 💥 The mistake that destroys data

\`\`\`js
db.users.updateOne({ _id }, { name: 'Asha' })          // ❌ REPLACES the document
db.users.updateOne({ _id }, { $set: { name: 'Asha' } }) // ✅ updates one field
\`\`\`

Forget \`$set\` and every other field is **deleted**. The document becomes \`{ _id, name }\` and the email, the address and the order history are simply gone.

**Say it:** *"No \`$set\`, no document."*

### 🔁 upsert

\`{ upsert: true }\` = "update it, or create it if it is not there". Same idea as Postgres's \`ON CONFLICT\`, and it solves the same race.

**Why this sticks:** the missing \`$set\` is *irreversible data loss*, and the brain weights loss far more heavily than gain. This is one to encode with the consequence attached, not the syntax.`,
    tricksHi: `### ✍️ "One ya Many — suffix bata deta hai"

\`insertOne\` / \`insertMany\`, \`updateOne\` / \`updateMany\`, \`deleteOne\` / \`deleteMany\`.

**Khatarnaak default:** khaali filter ke saath \`updateMany({}, ...)\` **collection ke har document** par lagta hai. Na pushti, na undo.

**Bolo:** *"Khaali filter matlab sab kuch."*

### 💥 Wo galti jo data khatam kar deti hai

\`\`\`js
db.users.updateOne({ _id }, { name: 'Asha' })          // ❌ document BADAL deta hai
db.users.updateOne({ _id }, { $set: { name: 'Asha' } }) // ✅ ek field update karta hai
\`\`\`

\`$set\` bhoolo aur baaki har field **mit** jati hai. Document \`{ _id, name }\` ban jata hai aur email, pata, order history bas gayab.

**Bolo:** *"\`$set\` nahi, to document nahi."*

### 🔁 upsert

\`{ upsert: true }\` = "update karo, ya na ho to bana do". Postgres ke \`ON CONFLICT\` jaisa hi vichaar, aur wahi race hal karta hai.

**Ye kyun tikta hai:** \`$set\` ka chhootna *na palatne wala data loss* hai, aur dimaag nuksaan ko faayde se kahin bhaari maanta hai. Ise syntax ke saath nahi, natije ke saath jama karo.`,
  },

  'mongo-query-operators': {
    tricks: `### 💲 "Every operator starts with $"

Once you see that, the list stops looking like vocabulary and starts looking like a pattern.

**Comparison:** \`$eq $ne $gt $gte $lt $lte $in $nin\`

**Logic:** \`$and $or $not $nor\`

**Existence:** \`$exists $type\`

**Arrays:** \`$all $elemMatch $size\`

### 🎯 The one worth learning properly

\`$elemMatch\` — *"one **single** array element must match **all** these conditions."*

Without it, Mongo lets **different elements** satisfy different conditions:

\`\`\`js
{ 'scores.subject': 'math', 'scores.grade': 'A' }
// matches someone with math=C and history=A  ← almost never what you want
{ scores: { $elemMatch: { subject: 'math', grade: 'A' } } }  // correct
\`\`\`

**Say it:** *"Same element? \`$elemMatch\`."*

**Why this sticks:** the false-positive example is *concrete and wrong in a way you can see*. Showing the bug before the fix means the fix arrives as a solution to a problem you already felt.`,
    tricksHi: `### 💲 "Har operator $ se shuru hota hai"

Ye dikh jaye to list vocabulary lagni band ho jati hai aur pattern lagne lagti hai.

**Tulna:** \`$eq $ne $gt $gte $lt $lte $in $nin\`

**Logic:** \`$and $or $not $nor\`

**Hona:** \`$exists $type\`

**Arrays:** \`$all $elemMatch $size\`

### 🎯 Ek jo theek se seekhne layak hai

\`$elemMatch\` — *"array ka **ek hi** element in **saari** sharton par khara utre."*

Iske bina Mongo **alag-alag elements** ko alag shart poori karne deta hai:

\`\`\`js
{ 'scores.subject': 'math', 'scores.grade': 'A' }
// usse bhi match karta hai jiska math=C aur history=A ho  ← ye lagbhag kabhi nahi chahiye
{ scores: { $elemMatch: { subject: 'math', grade: 'A' } } }  // sahi
\`\`\`

**Bolo:** *"Wahi element chahiye? \`$elemMatch\`."*

**Ye kyun tikta hai:** galat match wala udaharan *thos hai aur uski galti dikhti hai*. Hal se pehle bug dikhana matlab hal us samasya ke jawab mein aata hai jo aap mehsoos kar chuke ho.`,
  },

  'mongo-aggregation': {
    tricks: `### 🏭 "A factory conveyor belt"

Documents go in one end. Each **stage** does one job and passes the result to the next.

\`\`\`
$match → $group → $sort → $limit → $project
\`\`\`

**Say it:** *"Filter, pile, sort, cut, choose."*

### ⚡ The single biggest performance rule

**Put \`$match\` first.** Filter before you do anything expensive, and \`$match\` at the start of a pipeline can use an **index**. Once you have \`$group\`ed, no index can help you.

**Say it:** *"\`$match\` first or the index is wasted."*

That one line is the difference between a pipeline that runs in 5 ms and the same pipeline running in 5 seconds.

### 🗺️ The SQL translation

| SQL | Aggregation |
|---|---|
| \`WHERE\` | \`$match\` |
| \`GROUP BY\` | \`$group\` |
| \`HAVING\` | \`$match\` **after** \`$group\` |
| \`SELECT cols\` | \`$project\` |
| \`JOIN\` | \`$lookup\` |

Notice \`$match\` appears twice — before grouping it is \`WHERE\`, after grouping it is \`HAVING\`. Same tool, different position, exactly like SQL.

**Why this sticks:** the conveyor belt is *sequential and physical*, which matches the thing it describes. And the WHERE/HAVING parallel reuses knowledge you already have rather than building new storage.`,
    tricksHi: `### 🏭 "Factory ka conveyor belt"

Documents ek sire se andar jate hain. Har **stage** ek kaam karta hai aur natija agle ko de deta hai.

\`\`\`
$match → $group → $sort → $limit → $project
\`\`\`

**Bolo:** *"Chhaano, dher banao, sort karo, kaato, chuno."*

### ⚡ Sabse bada performance niyam

**\`$match\` sabse pehle rakho.** Mehnga kaam karne se pehle chhaano, aur pipeline ke shuru mein \`$match\` **index** use kar sakta hai. Ek baar \`$group\` ho gaya to koi index madad nahi kar sakta.

**Bolo:** *"\`$match\` pehle, warna index bekaar."*

Yahi ek line 5 ms mein chalne wali pipeline aur wahi pipeline 5 second mein chalne ka farq hai.

### 🗺️ SQL ka anuvaad

| SQL | Aggregation |
|---|---|
| \`WHERE\` | \`$match\` |
| \`GROUP BY\` | \`$group\` |
| \`HAVING\` | \`$group\` ke **baad** \`$match\` |
| \`SELECT cols\` | \`$project\` |
| \`JOIN\` | \`$lookup\` |

Dhyan do \`$match\` do baar aata hai — group se pehle wo \`WHERE\` hai, baad mein \`HAVING\`. Wahi tool, alag jagah, bilkul SQL jaisa.

**Ye kyun tikta hai:** conveyor belt *kramik aur sharirik* hai, jo isi cheez se milta hai. Aur WHERE/HAVING ki samaanta pehle se maujood jaankari dobara use karti hai, nayi jagah nahi banati.`,
  },

  'mongo-indexes': {
    tricks: `### 📕 "Same book index as SQL"

Without one, Mongo reads **every document**. The concept transfers exactly.

### 🔍 How to actually check

\`\`\`js
db.orders.find({ status: 'PAID' }).explain('executionStats')
\`\`\`

Look for **COLLSCAN** — that means it read everything. **IXSCAN** means it used an index.

**Say it:** *"COLLSCAN bad, IXSCAN good."*

Four syllables, rhymes, and it is the one thing to look for in a wall of output.

### 🔑 The ESR rule — worth memorising by name

For compound indexes, order the fields:

**E**quality → **S**ort → **R**ange

\`\`\`js
// find({ status: 'PAID', date: { $gt: x } }).sort({ total: -1 })
db.orders.createIndex({ status: 1, total: -1, date: 1 })
//                      equality   sort     range
\`\`\`

Get that order wrong and Mongo can use part of the index but has to sort in memory — which fails outright past 32 MB.

**Say it:** *"Equality, Sort, Range."* Three words, and it is a genuine interview answer.

**Why this sticks:** ESR is a real named rule with an official acronym. Named things are easier to retrieve than described things, because the name is a single handle for the whole idea.`,
    tricksHi: `### 📕 "Wahi kitaab wala index jo SQL mein tha"

Uske bina Mongo **har document** padhta hai. Vichaar bilkul waisa hi hai.

### 🔍 Sach mein kaise jaanchein

\`\`\`js
db.orders.find({ status: 'PAID' }).explain('executionStats')
\`\`\`

**COLLSCAN** dhoondho — matlab usne sab padha. **IXSCAN** matlab index use hua.

**Bolo:** *"COLLSCAN bura, IXSCAN achha."*

Chhota, tuk milta hai, aur output ki deewar mein yahi ek cheez dekhni hai.

### 🔑 ESR niyam — naam se yaad karne layak

Compound index mein fields ka kram:

**E**quality → **S**ort → **R**ange

\`\`\`js
// find({ status: 'PAID', date: { $gt: x } }).sort({ total: -1 })
db.orders.createIndex({ status: 1, total: -1, date: 1 })
//                      equality   sort     range
\`\`\`

Kram galat hua to Mongo index ka hissa to use kar lega par sort memory mein karna padega — jo 32 MB ke baad seedha fail ho jata hai.

**Bolo:** *"Equality, Sort, Range."* Teen shabd, aur ye asli interview jawab hai.

**Ye kyun tikta hai:** ESR asli naam wala niyam hai jiska official acronym hai. Naam wali cheezein hulie wali cheezon se aasani se yaad aati hain, kyunki naam poore vichaar ka ek handle hai.`,
  },

  'mongo-schema-design': {
    tricks: `### 🤔 "Embed or reference? Ask how it is read."

**Embed** when the child is always read **with** the parent and does not grow without limit — an address inside a user, order line items inside an order.

**Reference** when the child is large, shared, or unbounded — a user's posts, a product referenced by ten thousand orders.

**Say it:** *"Read together, store together."*

### 📈 The rule that catches people

**Never embed an unbounded array.** Comments inside a post looks fine with 5 comments and dies at 50,000, because a document is capped at **16 MB** and Mongo has to move the whole thing on every update.

**Say it:** *"Unbounded means referenced."*

### 🔄 Duplication is allowed here

Storing the product name on the order is **not** a mistake in Mongo. It is often correct — and correct in SQL too, because an invoice must record the name and price **at the time of sale**.

**Say it:** *"Design for the query, not for the diagram."*

That sentence is the entire philosophical difference from SQL. In SQL you model the data and then query it; in Mongo you look at your queries and then model the data.

**Why this sticks:** "read together, store together" is *rhythmic and parallel*. And the 16 MB cap is a hard number — hard numbers act as anchors that vague warnings never do.`,
    tricksHi: `### 🤔 "Embed karein ya reference? Poochho ki padha kaise jata hai."

**Embed** tab jab bachcha hamesha parent ke **saath** padha jaye aur bina had ke na badhe — user ke andar pata, order ke andar line items.

**Reference** tab jab bachcha bada ho, saanjha ho, ya uski koi seema na ho — user ke posts, wo product jise das hazaar orders reference karte hain.

**Bolo:** *"Saath padhte ho, to saath rakho."*

### 📈 Wo niyam jo logon ko pakadta hai

**Bina seema wali array kabhi embed mat karo.** Post ke andar comments 5 comments par theek lagte hain aur 50,000 par mar jate hain, kyunki document ki had **16 MB** hai aur har update par Mongo ko poori cheez hilani padti hai.

**Bolo:** *"Bina seema ke matlab reference."*

### 🔄 Yahan duplication chalta hai

Order par product ka naam rakhna Mongo mein galti **nahi** hai. Wo aksar sahi hai — aur SQL mein bhi sahi hai, kyunki invoice mein **bikri ke waqt ka** naam aur daam hona chahiye.

**Bolo:** *"Query ke liye design karo, diagram ke liye nahi."*

Ye vaakya SQL se poora darshanik farq hai. SQL mein aap data model karte ho phir query; Mongo mein aap apni queries dekhte ho phir data model karte ho.

**Ye kyun tikta hai:** "saath padhte ho to saath rakho" *laydaar aur samaanaantar* hai. Aur 16 MB ek pakka number hai — pakke number aise langar hote hain jo dhundhli chetavniyan kabhi nahi banti.`,
  },

  'mongo-mongoose': {
    tricks: `### 🧷 "Mongoose puts the schema back"

Mongo does not enforce structure. Mongoose does — in your application, before the write reaches the database.

You get validation, defaults, types, hooks and population. You pay with a layer of abstraction and some magic.

**Say it:** *"Mongo forgets, Mongoose insists."*

### 🪤 Two traps worth knowing

**\`findByIdAndUpdate\` does not run validators by default.** You must pass \`{ runValidators: true }\`. Silently skipping validation on updates is exactly the bug Mongoose was supposed to prevent.

**\`populate\` is a second query, not a JOIN.** Populating three fields in a list of 100 documents can quietly become hundreds of round trips.

**Say it:** *"Populate is convenience, not a join."*

### 🎯 The lean() trick

\`.lean()\` returns plain objects instead of full Mongoose documents. Much faster, and correct whenever you are only reading and rendering — you do not need \`.save()\` on something you are about to serialise to JSON.

**Why this sticks:** each hook here is a *disappointed expectation* — the tool did less than you assumed. Those are the memories that actually change how you write code.`,
    tricksHi: `### 🧷 "Mongoose schema wapas laata hai"

Mongo dhaancha lagu nahi karta. Mongoose karta hai — aapki application mein, write database tak pahunchne se pehle.

Aapko validation, defaults, types, hooks aur population milte hain. Keemat: ek aur parat aur thoda jaadu.

**Bolo:** *"Mongo bhool jata hai, Mongoose zid karta hai."*

### 🪤 Do jaanne layak trap

**\`findByIdAndUpdate\` default mein validators nahi chalata.** Aapko \`{ runValidators: true }\` bhejna padta hai. Update par chupchaap validation chhod dena theek wahi bug hai jise Mongoose rokne ke liye tha.

**\`populate\` doosri query hai, JOIN nahi.** 100 documents ki list mein teen fields populate karna chupchaap sau se zyada chakkar ban sakta hai.

**Bolo:** *"Populate suvidha hai, join nahi."*

### 🎯 lean() wala tareeka

\`.lean()\` poore Mongoose documents ki jagah simple objects deta hai. Kaafi tez, aur jab aap sirf padh kar dikha rahe ho tab sahi bhi — jise JSON banana hai us par \`.save()\` ki zaroorat hai hi nahi.

**Ye kyun tikta hai:** yahan har hook ek *toothi hui ummeed* hai — tool ne utna nahi kiya jitna aapne maan liya tha. Yahi yaadein sach mein code likhne ka tareeka badalti hain.`,
  },

  'mongo-transactions': {
    tricks: `### 🔒 "Single document = already atomic. Multiple = you need a transaction."

An update to **one** document is atomic in Mongo with no extra work. That covers more cases than people expect, and it is why embedding related data has a correctness benefit as well as a speed one.

Across **several** documents or collections, you need an explicit transaction.

**Say it:** *"One document is safe for free."*

### ⚠️ The requirement people miss

Transactions need a **replica set**. A bare standalone \`mongod\` cannot do them — which is why the code works on Atlas and fails on a colleague's local install with a confusing error.

### ⚖️ The honest advice

If you find yourself needing multi-document transactions constantly, that is a **schema smell**, not a Mongo limitation. It usually means data that belongs together has been split apart — or that the workload genuinely wanted a relational database.

**Say it:** *"Lots of transactions? Wrong schema, or wrong database."*

**Why this sticks:** the last line reframes a technical fact as a *design signal*. Facts that tell you something about your own work are recalled more readily than facts that only describe a tool.`,
    tricksHi: `### 🔒 "Ek document = pehle se atomic. Kai = transaction chahiye."

Mongo mein **ek** document ka update bina kuch kiye atomic hai. Ye logon ke andaze se zyada case dhak leta hai, aur isiliye judi hui cheezein embed karne ka faayda sirf raftaar nahi, sahi hone ka bhi hai.

**Kai** documents ya collections par saaf transaction chahiye.

**Bolo:** *"Ek document muft mein surakshit hai."*

### ⚠️ Wo shart jo log bhool jate hain

Transactions ko **replica set** chahiye. Akela standalone \`mongod\` ye kar hi nahi sakta — isiliye code Atlas par chalta hai aur kisi sahyogi ke local install par ajeeb error deta hai.

### ⚖️ Imaandar salah

Agar aapko baar-baar multi-document transactions chahiye, to ye **schema ki badboo** hai, Mongo ki kami nahi. Aksar iska matlab hai ki jo data saath hona chahiye tha wo alag kar diya gaya — ya kaam ko sach mein relational database chahiye tha.

**Bolo:** *"Bahut saare transactions? Ya schema galat, ya database galat."*

**Ye kyun tikta hai:** aakhri line ek technical baat ko *design ke ishare* mein badal deti hai. Jo baatein aapke apne kaam ke baare mein kuch batati hain wo un baaton se jaldi yaad aati hain jo sirf tool ka hulia batati hain.`,
  },

  'mongo-vs-sql': {
    tricks: `### ⚖️ "Shape of data, or shape of queries?"

- **SQL** — relationships matter, you need joins, the data has a stable shape, and you want the database to **refuse** bad data.
- **Mongo** — the shape genuinely varies, you read whole objects at once, and you want to iterate fast early on.

**Say it:** *"SQL protects, Mongo bends."*

### 🎯 The honest interview answer

*"Most applications are relational. Users have orders, orders have products — that is a graph of relationships, and SQL was built for it. I would pick Mongo when documents genuinely vary in shape, or when I am reading whole objects and never joining."*

That answer works because it **starts with the default and justifies the exception**, which is what a senior engineer does.

### 🚩 The trap answer

*"Mongo scales better."* Modern Postgres scales to enormous workloads, and the honest difference is about **horizontal sharding ergonomics**, not raw capability. Saying "it scales better" without qualification signals you have read marketing rather than run either one.

**Why this sticks:** knowing the *wrong* answer and why it is wrong is stronger than knowing the right one alone. Contrast creates a boundary, and boundaries are what make a memory retrievable rather than vague.`,
    tricksHi: `### ⚖️ "Data ki shakal, ya queries ki shakal?"

- **SQL** — rishte matter karte hain, joins chahiye, data ki shakal tay hai, aur aap chahte ho ki database kharab data **mana kar de**.
- **Mongo** — shakal sach mein badalti hai, aap poore objects ek saath padhte ho, aur shuru mein tez chalna hai.

**Bolo:** *"SQL bachata hai, Mongo jhukta hai."*

### 🎯 Imaandar interview jawab

*"Zyadatar applications relational hoti hain. Users ke orders hote hain, orders mein products — ye rishton ka jaal hai, aur SQL isi ke liye bana tha. Mongo main tab chunta jab documents ki shakal sach mein alag-alag ho, ya jab main poore objects padh raha hoon aur join kabhi nahi karta."*

Ye jawab isliye chalta hai kyunki ye **default se shuru hota hai aur apwaad ki wajah deta hai**, aur senior engineer yahi karta hai.

### 🚩 Phansane wala jawab

*"Mongo behtar scale karta hai."* Aaj ka Postgres bahut bade workloads tak scale karta hai, aur imaandar farq **horizontal sharding kitni aasan hai** iska hai, kaabiliyat ka nahi. Bina shart ke "ye behtar scale karta hai" kehna batata hai ki aapne marketing padhi hai, dono chalaye nahi.

**Ye kyun tikta hai:** *galat* jawab aur wo galat kyun hai, ye jaanna akele sahi jawab se zyada mazboot hai. Farq ek seema banata hai, aur seemayein hi yaad ko dhundhla hone se bachati hain.`,
  },

  /* ══════════════════════════════════ REST ══════════════════════════════════ */

  'rest-design-principles': {
    tricks: `### 🔤 "Nouns for URLs, verbs for methods"

\`GET /getUsers\` is wrong twice — the URL contains a verb and the method already said "get".

\`GET /users\` says everything.

**Say it:** *"The URL is a place. The method is the action."*

### 🔢 Status codes, chunked by the first digit

- **2xx** — it worked
- **3xx** — look somewhere else
- **4xx** — **you** made a mistake
- **5xx** — **I** made a mistake

**Say it:** *"4 is your fault, 5 is mine."*

That one line is worth more than memorising forty codes, because it is what you actually need when deciding what to return.

The five that cover most real work: **200** ok · **201** created · **400** bad input · **401** not logged in · **403** logged in but not allowed · **404** not found.

### 🚪 401 vs 403 — the one people mix up

- **401** — *"who are you?"* (no or bad credentials)
- **403** — *"I know who you are, and no."*

**Say it:** *"401 is the door, 403 is the bouncer."*

**Why this sticks:** "4 is your fault, 5 is mine" is short, rhythmic and slightly confrontational. And door/bouncer is a *spatial pair* — you can picture both positions at once, which is what stops the two codes swapping.`,
    tricksHi: `### 🔤 "URL mein sangya, method mein kriya"

\`GET /getUsers\` do baar galat hai — URL mein kriya hai aur method pehle hi "get" keh chuka.

\`GET /users\` sab keh deta hai.

**Bolo:** *"URL ek jagah hai. Method ek kaam hai."*

### 🔢 Status codes, pehle ank se chunk karke

- **2xx** — chal gaya
- **3xx** — kahin aur dekho
- **4xx** — galti **aapki**
- **5xx** — galti **meri**

**Bolo:** *"4 aapki galti, 5 meri."*

Yahi ek line chalis codes ratne se zyada keemti hai, kyunki kya lautana hai ye tay karte waqt asal mein yahi chahiye.

Paanch jo zyadatar kaam dhak lete hain: **200** theek · **201** ban gaya · **400** kharab input · **401** login nahi · **403** login hai par ijazat nahi · **404** mila nahi.

### 🚪 401 aur 403 — jinhe log ghulaate hain

- **401** — *"aap kaun ho?"* (credentials nahi ya galat)
- **403** — *"mujhe pata hai aap kaun ho, aur nahi."*

**Bolo:** *"401 darwaza hai, 403 bouncer."*

**Ye kyun tikta hai:** "4 aapki galti, 5 meri" chhota, laydaar aur thoda ladaaka hai. Aur darwaza/bouncer ek *jagah wali jodi* hai — dono ki position ek saath dikhti hai, aur isi se ye do code aapas mein nahi badalte.`,
  },

  'rest-idempotency-versioning': {
    tricks: `### 🔁 "Idempotent = pressing the lift button twice changes nothing"

The lift still comes once. That is idempotency in one image.

- **GET, PUT, DELETE** — idempotent. Call them five times, same end state.
- **POST** — **not**. Five calls, five orders, five charges.

**Say it:** *"POST is the only one that multiplies."*

### 💳 Why this matters in real money

A user's connection drops mid-payment. Did it go through? Their phone retries. Without an **idempotency key**, they are charged twice — and that is a support ticket, a refund and a lost customer.

The fix: the client sends a unique key with the request, and the server remembers *"I have already done that one"*.

**Say it:** *"Retries are certain. Design for the second attempt."*

### 🔢 Versioning

\`/v1/users\` in the URL is the simplest and most common. Header-based versioning is purer and harder to debug — you cannot paste a header into a browser.

**The real rule:** you version when you make a **breaking** change. Adding a field is not breaking; removing or renaming one is.

**Why this sticks:** the lift button is universal, and the double-charge is a *scenario with a victim*. Consequences involving a real person are stored more strongly than abstract properties like "idempotent".`,
    tricksHi: `### 🔁 "Idempotent = lift ka button do baar dabane se kuch nahi badalta"

Lift phir bhi ek hi baar aati hai. Ek tasveer mein idempotency yahi hai.

- **GET, PUT, DELETE** — idempotent. Paanch baar bulao, aakhri haalat wahi.
- **POST** — **nahi**. Paanch call, paanch order, paanch charge.

**Bolo:** *"POST akela hai jo gunna hota hai."*

### 💳 Ye asli paise mein kyun matter karta hai

Payment ke beech user ka connection toot ta hai. Hua ya nahi? Uska phone dobara koshish karta hai. **Idempotency key** ke bina us par do baar charge lagta hai — aur wo ek support ticket, ek refund aur ek gaya hua customer hai.

Hal: client request ke saath ek unique key bhejta hai, aur server yaad rakhta hai *"ye to main kar chuka"*.

**Bolo:** *"Retry pakka hoga. Doosri koshish ke liye design karo."*

### 🔢 Versioning

URL mein \`/v1/users\` sabse simple aur sabse aam hai. Header wali versioning zyada shuddh hai aur debug karna mushkil — header ko browser mein paste nahi kar sakte.

**Asli niyam:** version tab badalte ho jab **breaking** badlav karo. Field jodna breaking nahi hai; hatana ya naam badalna hai.

**Ye kyun tikta hai:** lift ka button sabko pata hai, aur do baar charge lagna *ek shikaar wali kahani* hai. Jis natije mein asli insaan ho wo "idempotent" jaisi abstract khoobi se kahin mazbooti se jama hota hai.`,
  },

  /* ═══════════════════════════════ WebSockets ═══════════════════════════════ */

  'ws-why-not-http': {
    tricks: `### 📞 "HTTP is a letter. WebSocket is a phone call."

With letters, only **you** can start the conversation. The server can never write first — that is the entire limitation, and everything else follows.

**Say it:** *"HTTP: the server cannot speak first."*

### 🪜 The four options, cheapest first

1. **Polling** — "anything new?" every 3 seconds. Wasteful, works everywhere.
2. **Long polling** — ask, and the server holds the line until it has something.
3. **SSE** — one open line, **server talks only**. Auto-reconnects, plain HTTP.
4. **WebSocket** — one open line, **both talk**.

**Say it:** *"Ask, wait, listen, talk."* Four words in increasing capability.

### 🎯 The answer that impresses

*"If only the server sends, SSE is lighter and needs no library. If updates are every thirty seconds, polling is genuinely fine. WebSockets are for when both sides send frequently."*

Knowing when **not** to use the fancy option is the senior signal. Reaching for WebSockets when polling would do means owning connection state forever.

**Why this sticks:** letter/phone call is a *communication metaphor for a communication problem* — the structures match, so the fact is re-derivable rather than memorised.`,
    tricksHi: `### 📞 "HTTP chitthi hai. WebSocket phone call."

Chitthi mein baat sirf **aap** shuru kar sakte ho. Server kabhi pehle nahi likh sakta — poori seema yahi hai, aur baaki sab isi se nikalta hai.

**Bolo:** *"HTTP: server pehle bol hi nahi sakta."*

### 🪜 Chaar raste, sabse saste se

1. **Polling** — har 3 second "kuch naya?". Fizool, har jagah chalta hai.
2. **Long polling** — poochho, aur server line pakde rakhta hai jab tak kuch na ho.
3. **SSE** — ek khuli line, **sirf server bolta hai**. Khud reconnect, plain HTTP.
4. **WebSocket** — ek khuli line, **dono bolte hain**.

**Bolo:** *"Poochho, ruko, suno, bolo."* Chaar shabd, badhti taakat ke kram mein.

### 🎯 Wo jawab jo prabhavit karta hai

*"Agar sirf server bhejta hai to SSE halka hai aur library nahi chahiye. Agar update har tees second par hai to polling sach mein theek hai. WebSockets tab jab dono taraf se baar-baar bheja jaye."*

Chamakdaar option kab **nahi** lena, yahi senior wala ishara hai. Jahan polling kaafi thi wahan WebSockets lena matlab hamesha ke liye connection state sambhalna.

**Ye kyun tikta hai:** chitthi/phone call ek *baat-cheet ki samasya ke liye baat-cheet ki upma* hai — dhaanche milte hain, isliye baat rat ne ki jagah dobara nikaali ja sakti hai.`,
  },

  'ws-how-it-works': {
    tricks: `### 🤝 "It starts as HTTP, then changes clothes"

The client sends a normal HTTP request with \`Upgrade: websocket\`. The server replies **101 Switching Protocols**, and the same TCP connection stops speaking HTTP and starts speaking WebSocket.

**Say it:** *"101 is the handshake."*

That is why WebSockets work through firewalls and proxies that only expect HTTP — they start out looking exactly like it.

### 💓 Why heartbeats exist

A TCP connection can die **silently**. Nobody sends a "goodbye" — the wifi just drops. Both sides sit there believing they are connected, and neither finds out until they try to send something.

So both ends send **ping/pong** frames. No pong in time → assume dead → reconnect.

**Say it:** *"No news is not good news."*

### 🔢 The four ready states

CONNECTING → OPEN → CLOSING → CLOSED. Only send in **OPEN**.

**Why this sticks:** "no news is not good news" *inverts a proverb you already know*. Inverted familiar phrases are unusually sticky, because the brain notices the mismatch with the stored original.`,
    tricksHi: `### 🤝 "Shuruaat HTTP se hoti hai, phir kapde badal leta hai"

Client \`Upgrade: websocket\` ke saath aam HTTP request bhejta hai. Server **101 Switching Protocols** se jawab deta hai, aur wahi TCP connection HTTP bolna band karke WebSocket bolne lagta hai.

**Bolo:** *"101 hi handshake hai."*

Isiliye WebSockets un firewalls aur proxies se guzar jate hain jo sirf HTTP ki ummeed rakhte hain — shuruaat mein wo bilkul HTTP hi dikhte hain.

### 💓 Heartbeat kyun hote hain

TCP connection **chupchaap** mar sakta hai. Koi "alvida" nahi bhejta — wifi bas chala jata hai. Dono taraf log baithe rehte hain ye maan kar ki jude hain, aur kisi ko tab tak pata nahi chalta jab tak kuch bhejne ki koshish na karein.

Isliye dono sire **ping/pong** frames bhejte hain. Waqt par pong nahi → mara hua maano → dobara jodo.

**Bolo:** *"Khabar na aana achhi khabar nahi hai."*

### 🔢 Chaar ready states

CONNECTING → OPEN → CLOSING → CLOSED. Bhejo sirf **OPEN** mein.

**Ye kyun tikta hai:** "khabar na aana achhi khabar nahi" *ek jaani-pehchani kahawat ko ulta karta hai*. Ulti hui jaani-pehchani baatein ajeeb tareeke se chipakti hain, kyunki dimaag jama kiye asli se farq turant pakad leta hai.`,
  },

  'ws-socketio': {
    tricks: `### 🎁 "Socket.IO is WebSocket plus the things you would have written anyway"

Raw WebSockets give you a byte pipe. You then write reconnection with backoff, grouping, message routing and delivery confirmation yourself.

Socket.IO ships all of that, plus an HTTP long-polling fallback and an adapter for multiple servers.

**Say it:** *"Raw is a pipe. Socket.IO is plumbing."*

### 🚪 Rooms — the concept to actually learn

A room is just a **named group of sockets**.

\`\`\`js
socket.join('order:5');
io.to('order:5').emit('order:updated', { status: 'shipped' });
\`\`\`

Two lines, no bookkeeping. Joining and broadcasting to a subset are one line each.

### ⚠️ The day-one gotcha

**A plain \`new WebSocket()\` cannot connect to a Socket.IO server.** Socket.IO layers its own handshake and message format on top of the protocol, so both ends must use it — and mismatched major versions refuse each other with an unhelpful error.

**Say it:** *"Socket.IO on one end means Socket.IO on both."*

**Why this sticks:** "raw is a pipe, Socket.IO is plumbing" is a *contrast pair built from one material*. Same domain, different level of finish — which is exactly the real relationship.`,
    tricksHi: `### 🎁 "Socket.IO = WebSocket + wo cheezein jo aap waise bhi likhte"

Raw WebSockets sirf ek byte pipe dete hain. Phir aap khud likhte ho: backoff ke saath reconnection, grouping, message routing aur delivery ki pushti.

Socket.IO ye sab deta hai, saath mein HTTP long-polling fallback aur kai servers ke liye adapter.

**Bolo:** *"Raw ek pipe hai. Socket.IO poori plumbing."*

### 🚪 Rooms — jo sach mein seekhna chahiye

Room bas sockets ka ek **naam wala group** hai.

\`\`\`js
socket.join('order:5');
io.to('order:5').emit('order:updated', { status: 'shipped' });
\`\`\`

Do line, koi hisaab-kitaab nahi. Join karna aur kisi hisse ko broadcast karna dono ek-ek line hain.

### ⚠️ Pehle din wala pech

**Simple \`new WebSocket()\` Socket.IO server se connect nahi ho sakta.** Socket.IO protocol ke upar apna handshake aur message format rakhta hai, isliye dono sire par wahi chahiye — aur alag major versions ek doosre ko bekaar se error ke saath mana kar dete hain.

**Bolo:** *"Ek sire par Socket.IO matlab dono sire par."*

**Ye kyun tikta hai:** "raw ek pipe, Socket.IO plumbing" *ek hi cheez se bana contrast pair* hai. Wahi kshetra, alag darja — aur asli rishta bilkul yahi hai.`,
  },

  'ws-auth-and-security': {
    tricks: `### 🎟️ "Check the ticket at the door, then again at every ride"

A socket authenticates **once** and stays open for hours. That changes the threat model completely.

- **At connect** — verify the token in middleware, and send it in the **auth payload**, not the query string. Query strings land in server and proxy logs.
- **At every event** — re-check permission. Being connected proved *who* they are once. It did not prove they may join order 99.

**Say it:** *"Connected is not authorised."*

### 💀 The room-name trap

\`\`\`js
socket.join(clientProvidedRoomName);   // 🚨 anyone can join anyone's room
\`\`\`

Taking a room name straight from the client lets any user receive someone else's private data. This is the single most common WebSocket vulnerability.

**Say it:** *"Never join a room the client named."*

### 🛡️ Two more people miss

- **CORS does not protect WebSockets** the way it protects fetch. You must verify the \`Origin\` header **yourself**, or any website can open a socket with your user's cookies.
- **HTTP rate limiters never see socket events.** A client can emit in a loop unless you limit them separately.

**Why this sticks:** these are *heist details*. Security facts framed as "here is how someone robs you" are acted on; the same facts framed as best practices are nodded at and ignored.`,
    tricksHi: `### 🎟️ "Ticket darwaze par jaancho, phir har jhoole par dobara"

Socket **ek baar** authenticate hota hai aur ghanton khula rehta hai. Isse khatra poori tarah badal jata hai.

- **Connect par** — token middleware mein verify karo, aur use **auth payload** mein bhejo, query string mein nahi. Query strings server aur proxy logs mein pahunchti hain.
- **Har event par** — ijazat dobara jaancho. Connected hona ek baar ye sabit karta hai ki wo *kaun* hai. Ye nahi ki wo order 99 join kar sakta hai.

**Bolo:** *"Connected hona ijazat nahi hai."*

### 💀 Room ke naam wala trap

\`\`\`js
socket.join(clientProvidedRoomName);   // 🚨 koi bhi kisi ke room mein ghus sakta hai
\`\`\`

Room ka naam seedhe client se lene par koi bhi user doosre ka nijee data le sakta hai. WebSocket ki sabse aam kamzori yahi hai.

**Bolo:** *"Client ke bataye room mein kabhi join mat karao."*

### 🛡️ Do aur jo log chhod dete hain

- **CORS WebSockets ko waise nahi bachata** jaise fetch ko bachata hai. \`Origin\` header aapko **khud** verify karna hoga, warna koi bhi website aapke user ki cookies ke saath socket khol legi.
- **HTTP rate limiters ko socket events dikhte hi nahi.** Client loop mein emit kar sakta hai jab tak aap alag se limit na lagao.

**Ye kyun tikta hai:** ye *chori ki tafseelein* hain. "Aapko loota kaise jayega" ki tarah batayi gayi security baaton par log amal karte hain; wahi baatein best practice ki tarah batao to sar hila kar chhod di jati hain.`,
  },

  'ws-scaling': {
    tricks: `### 🏝️ "Two servers, two islands"

Alice connects to server A. Bob connects to server B. Server A broadcasts — and Bob hears **nothing**.

**Say it:** *"A broadcast only reaches its own island."*

The cruel part: everything works **perfectly** on one process locally. This bug appears the moment you scale, which is usually the moment you are least able to debug calmly.

### 🌉 The fix: a bridge

The **Redis adapter**. Each server publishes its emits to Redis and subscribes to the others, so a broadcast crosses instances.

**Say it:** *"Redis is the ferry between islands."*

### 📌 Sticky sessions

Socket.IO's HTTP long-polling fallback sends **several** handshake requests that must all reach the **same** server. Without stickiness you get intermittent failures that look exactly like a flaky network — and you will spend a day blaming the wifi.

### 📊 Three more that change how you plan

- Capacity is measured in **concurrent connections**, not requests per second
- Presence ("who is online") must live in **shared** storage, not process memory
- A deploy **disconnects everyone at once** — reconnection needs backoff *and* jitter, or all of them stampede back simultaneously

**Why this sticks:** the islands image makes the failure *geographic*, and spatial reasoning is one of the oldest and most reliable memory systems humans have.`,
    tricksHi: `### 🏝️ "Do server, do dweep"

Alice server A se judti hai. Bob server B se. Server A broadcast karta hai — aur Bob ko **kuch** nahi sunai deta.

**Bolo:** *"Broadcast sirf apne dweep tak pahunchta hai."*

Kroor hissa: local par ek process mein sab **perfect** chalta hai. Ye bug tab aata hai jab aap scale karte ho, aur aksar wahi waqt hota hai jab aaram se debug karna sabse mushkil hai.

### 🌉 Hal: ek pul

**Redis adapter**. Har server apne emits Redis par publish karta hai aur doosron ko subscribe karta hai, isliye broadcast instances ke paar chala jata hai.

**Bolo:** *"Redis dweepon ke beech ki ferry hai."*

### 📌 Sticky sessions

Socket.IO ka HTTP long-polling fallback **kai** handshake requests bhejta hai jinhe **usi** server par pahunchna hota hai. Stickiness ke bina beech-beech mein failures aate hain jo bilkul kharab network jaise lagte hain — aur aap ek din wifi ko kosne mein bita denge.

### 📊 Teen aur jo planning badal dete hain

- Kshamta **ek saath judi connections** se naapi jati hai, requests per second se nahi
- Presence ("kaun online hai") **saanjhe** storage mein hona chahiye, process memory mein nahi
- Deploy **sabko ek saath disconnect** karta hai — reconnection mein backoff *aur* jitter dono chahiye, warna sab ek saath toot padte hain

**Ye kyun tikta hai:** dweep wali tasveer nakaami ko *bhaugolik* bana deti hai, aur jagah ki samajh insaan ki sabse purani aur bharosemand memory systems mein se ek hai.`,
  },

  /* ══════════════════════════════ Authentication ════════════════════════════ */

  'auth-jwt-vs-sessions': {
    tricks: `### 🎫 "A session is a cloakroom ticket. A JWT is a signed permission slip."

- **Session** — the server keeps the coat. Your ticket is a meaningless number. To revoke you, the server throws the coat out. **Instant.**
- **JWT** — you carry the whole note, signed so it cannot be forged. The server checks the signature and does not look anything up. **Fast, but cannot be un-issued.**

**Say it:** *"Sessions can be cancelled. JWTs cannot."*

### ⚖️ The trade-off, honestly

JWTs are **stateless** — great for scaling, terrible for "log this user out **now**". Once issued, that token is valid until it expires, full stop.

So the usual real-world answer is **both**: a short-lived access token (15 min) plus a **stored, revocable** refresh token. You get speed and control.

**Say it:** *"Short access, revocable refresh."*

### 🚫 Never put secrets in a JWT

It is **signed, not encrypted**. Anyone can paste it into jwt.io and read every field. Signing proves nobody *changed* it — it does nothing to hide it.

**Say it:** *"Signed means tamper-proof, not secret."*

**Why this sticks:** cloakroom vs permission slip encodes the *revocation difference*, which is the whole interview question. The images differ in exactly the way the technologies do.`,
    tricksHi: `### 🎫 "Session cloakroom ka token hai. JWT signed ijazat parchi."

- **Session** — coat server ke paas hai. Aapka token bemaani number hai. Aapko hataana ho to server coat bahar phenk deta hai. **Turant.**
- **JWT** — poori parchi aap le kar chalte ho, sign ki hui taaki nakli na bane. Server signature jaanchta hai aur kuch dhoondhta hi nahi. **Tez, par wapas nahi liya ja sakta.**

**Bolo:** *"Session cancel ho sakta hai. JWT nahi."*

### ⚖️ Sauda, imaandari se

JWT **stateless** hai — scaling ke liye shandar, "is user ko **abhi** logout karo" ke liye bekaar. Ek baar jaari ho gaya to wo token expire hone tak sahi hai, bas.

Isliye asli duniya ka aam jawab hai **dono**: chhoti umar ka access token (15 min) aur ek **jama kiya, wapas liya ja sakne wala** refresh token. Raftaar bhi, kaabu bhi.

**Bolo:** *"Chhota access, wapas liya ja sakne wala refresh."*

### 🚫 JWT mein raaz kabhi mat rakho

Ye **sign ki hui hai, encrypt nahi**. Koi bhi ise jwt.io mein paste karke har field padh sakta hai. Sign karna sabit karta hai ki kisi ne use *badla* nahi — chhupane ka isse koi lena-dena nahi.

**Bolo:** *"Signed matlab chhed-chhaad se surakshit, gupt nahi."*

**Ye kyun tikta hai:** cloakroom aur ijazat parchi *wapas lene ka farq* jama karti hain, aur poora interview sawaal wahi hai. Tasveerein theek us tarah alag hain jis tarah ye technologies alag hain.`,
  },

  'auth-password-security': {
    tricks: `### 🐌 "For passwords, slow is the feature"

SHA-256 is **fast** — that is exactly why it is wrong here. A GPU tries **billions** of SHA-256 guesses per second.

bcrypt/argon2 are **deliberately slow and tunable**. You raise the cost factor as hardware improves.

**Say it:** *"Fast hash, fast crack."*

### 🧂 Salt = a different recipe per user

Without a salt, two users with the same password get the **same** hash — so cracking one cracks both, and precomputed rainbow tables work instantly.

bcrypt salts automatically and stores the salt **inside** the hash string. You do not manage it.

**Say it:** *"Same password, different hash. That is the salt."*

### ⏱️ Always compare in constant time

Comparing with \`===\` leaks information through **timing** — a wrong first character returns fractionally sooner than a wrong last character, and that difference is measurable over enough attempts.

Use \`bcrypt.compare\` or \`crypto.timingSafeEqual\`, never \`===\`.

### 📏 Length beats complexity

A 20-character passphrase beats \`P@ssw0rd!\` by an enormous margin. Forced symbol rules mostly produce predictable substitutions — everyone turns \`a\` into \`@\`, and the attackers know that.

**Why this sticks:** "fast hash, fast crack" is *four words with internal rhyme*, and it inverts the usual assumption that fast is good. Inverted assumptions get extra processing.`,
    tricksHi: `### 🐌 "Password ke liye dheema hona hi khoobi hai"

SHA-256 **tez** hai — aur theek isiliye yahan galat hai. GPU ek second mein **arbon** SHA-256 andaze aazma leta hai.

bcrypt/argon2 **jaan-boojh kar dheeme aur adjust hone wale** hain. Hardware behtar hone par aap cost factor badha dete ho.

**Bolo:** *"Tez hash, tez crack."*

### 🧂 Salt = har user ke liye alag recipe

Salt ke bina ek hi password wale do users ko **ek hi** hash milta hai — to ek crack karo aur dono crack, aur pehle se bani rainbow tables turant chal jati hain.

bcrypt khud salt lagata hai aur use hash ke **andar** rakh deta hai. Aapko sambhalna nahi padta.

**Bolo:** *"Wahi password, alag hash. Yahi salt hai."*

### ⏱️ Hamesha constant time mein compare karo

\`===\` se compare karna **waqt** ke zariye jaankari leak karta hai — galat pehla akshar galat aakhri akshar se zara pehle laut ta hai, aur kaafi koshishon mein wo farq naapa ja sakta hai.

\`bcrypt.compare\` ya \`crypto.timingSafeEqual\` use karo, \`===\` kabhi nahi.

### 📏 Lambai, complexity se behtar

20 akshar ka passphrase \`P@ssw0rd!\` se bahut bade faasle se jeet ta hai. Zabardasti ke symbol niyam zyadatar anuman lagane layak badlav hi dete hain — sab \`a\` ko \`@\` bana dete hain, aur hamlawaron ko ye pata hai.

**Ye kyun tikta hai:** "tez hash, tez crack" *chaar shabd hain jinme tuk hai*, aur ye us aam soch ko ulta deta hai ki tez hona achha hai. Ulti hui soch par dimaag zyada kaam karta hai.`,
  },

  'auth-xss-csrf-cors': {
    tricks: `### 🎭 "Three different attackers, three different doors"

This is the trio everyone confuses. Separate them by **who is doing what**:

- **XSS** — the attacker's **script** runs on **your** page. They stole your keys.
- **CSRF** — the attacker's **site** makes **your browser** send a request, using cookies it attaches automatically. They used your hand to sign.
- **CORS** — the browser's rule about **who may read a response**. Not a defence you control.

**Say it:** *"XSS steals, CSRF forges, CORS restricts."*

Three verbs. That single line separates the three forever.

### 🚨 The most important thing to understand about CORS

**CORS does not protect your API.**

It stops a *browser on another origin* from **reading** the response. The request often **still arrives and still executes**. And anything that is not a browser — curl, Postman, a script — ignores CORS entirely.

**Say it:** *"CORS is a browser rule, not a firewall."*

Volunteering that line in an interview is a strong signal, because most candidates believe the opposite.

### 🛡️ The defences, matched to the attack

- **XSS** → escape output, Content-Security-Policy, never \`innerHTML\` with user data
- **CSRF** → \`SameSite\` cookies, CSRF tokens
- Store tokens in \`httpOnly\` cookies so XSS cannot read them — **but** that reintroduces CSRF, which is why \`SameSite\` matters

**Why this sticks:** "steals, forges, restricts" is *three verbs in parallel*. Parallel structure makes a set behave like one item, so you recall all three or none — and "none" is unlikely once the phrase is in.`,
    tricksHi: `### 🎭 "Teen alag hamlawar, teen alag darwaze"

Ye teenon sabko ghulaate hain. Inhe **kaun kya kar raha hai** se alag karo:

- **XSS** — hamlawar ki **script** **aapke** page par chalti hai. Unhone aapki chaabiyan chura li.
- **CSRF** — hamlawar ki **site** **aapke browser** se request bhijwati hai, un cookies ke saath jo browser khud laga deta hai. Unhone aapke haath se dastakhat karwa liye.
- **CORS** — browser ka niyam ki **jawab kaun padh sakta hai**. Ye aapke kaabu wala bachaav nahi hai.

**Bolo:** *"XSS churata hai, CSRF nakli dastakhat karta hai, CORS rokta hai."*

Teen kriya. Yahi ek line teeno ko hamesha ke liye alag kar deti hai.

### 🚨 CORS ke baare mein sabse zaroori baat

**CORS aapki API ko nahi bachata.**

Wo *doosre origin ke browser* ko jawab **padhne** se rokta hai. Request aksar **phir bhi pahunchti hai aur chal jati hai**. Aur jo browser nahi hai — curl, Postman, koi script — wo CORS ko ginta hi nahi.

**Bolo:** *"CORS browser ka niyam hai, firewall nahi."*

Interview mein khud ye line bol dena mazboot ishara hai, kyunki zyadatar log iska ulta maante hain.

### 🛡️ Bachaav, hamle se milaye hue

- **XSS** → output escape karo, Content-Security-Policy, user data ke saath \`innerHTML\` kabhi nahi
- **CSRF** → \`SameSite\` cookies, CSRF tokens
- Tokens \`httpOnly\` cookies mein rakho taaki XSS unhe padh na sake — **par** isse CSRF wapas aa jata hai, aur isiliye \`SameSite\` matter karta hai

**Ye kyun tikta hai:** "churata, nakli banata, rokta" *teen samaanaantar kriya* hain. Samaanaantar dhaancha set ko ek cheez jaisa bana deta hai, isliye ya teeno yaad aate hain ya koi nahi — aur vaakya baith jane ke baad "koi nahi" mushkil hai.`,
  },

  /* ═════════════════════════════ System design ══════════════════════════════ */

  'sd-scaling-basics': {
    tricks: `### 🏗️ "Bigger box, or more boxes?"

- **Vertical** — a bigger machine. Simple, instant, and there is a ceiling (and the price curve is brutal near the top).
- **Horizontal** — more machines. No ceiling, but now you need a load balancer and your app must be **stateless**.

**Say it:** *"Up is easy, out is unlimited."*

### 🔑 The word that unlocks horizontal scaling

**Stateless.**

If a server remembers something about a user in its own memory, request two hits a different server and everything breaks. Sessions, uploads and caches must live in **shared** storage — Redis, S3, the database.

**Say it:** *"Servers should be interchangeable."*

### 🪜 The order to actually do things

1. **Measure** — find the real bottleneck, do not guess
2. **Add an index** — most "we need to scale" problems are one missing index
3. **Cache** the expensive reads
4. **Read replicas** — reads scale far more easily than writes
5. **Then** shard, and only then

Most scaling conversations should end at step 2 or 3. Jumping to sharding is how a two-person team acquires a distributed-systems problem it does not need.

**Why this sticks:** "up is easy, out is unlimited" is a *rhythmic pair with opposite directions*. And numbering the ladder makes it a sequence — sequences are recalled far better than sets.`,
    tricksHi: `### 🏗️ "Bada dibba, ya zyada dibbe?"

- **Vertical** — badi machine. Simple, turant, aur ek chhat hai (aur upar jaate hi daam bahut chubhta hai).
- **Horizontal** — zyada machines. Koi chhat nahi, par ab load balancer chahiye aur aapki app **stateless** honi chahiye.

**Bolo:** *"Upar jaana aasan, bahar jaana asimit."*

### 🔑 Wo shabd jo horizontal scaling kholta hai

**Stateless.**

Agar server user ke baare mein kuch apni memory mein rakhta hai, to doosri request doosre server par jati hai aur sab toot jata hai. Sessions, uploads aur caches **saanjhe** storage mein hone chahiye — Redis, S3, database.

**Bolo:** *"Server aapas mein badle ja sakne chahiye."*

### 🪜 Kaam karne ka asli kram

1. **Naapo** — asli rukavat dhoondho, andaza mat lagao
2. **Index lagao** — "hume scale karna hai" wali zyadatar samasyaayein ek chhoota hua index hoti hain
3. Mehngi reads ko **cache** karo
4. **Read replicas** — reads writes se kahin aasani se scale hoti hain
5. **Phir** shard karo, aur tabhi

Zyadatar scaling ki baat kadam 2 ya 3 par khatam honi chahiye. Seedha sharding par koodna hi wo tareeka hai jisse do logon ki team ko distributed-systems ki samasya mil jati hai jiski use zaroorat hi nahi thi.

**Ye kyun tikta hai:** "upar aasan, bahar asimit" *ulti dishaon wali laydaar jodi* hai. Aur seedhi ko number dena use kram bana deta hai — kram set se kahin behtar yaad rehta hai.`,
  },

  'sd-caching-strategies': {
    tricks: `### 🍱 "Cache what is read often and changes rarely"

That one sentence picks almost every cache correctly. If either half is false, do not cache it.

### 😅 The two hard problems

There is a famous line: *"There are only two hard things in computer science: cache invalidation and naming things."*

It is a joke, and it is also the real answer. Adding a cache takes five minutes. **Knowing when to remove the stale copy is the entire job.**

**Say it:** *"Adding is easy. Invalidating is the job."*

### 🗺️ The patterns, in one line each

- **Cache-aside** — check cache, miss → fetch → store. The default, and 90% of real usage.
- **Write-through** — write to cache and database together. Always fresh, slower writes.
- **Write-behind** — write to cache, flush to database later. Fast, and you can lose data.

### 💥 Three failures worth naming

- **Stampede** — the key expires and 1,000 requests all rebuild it at once
- **Stale data** — you cached it and forgot to invalidate
- **Cached a bad response** — you now serve an error to everyone, at speed

**Say it:** *"TTL is a promise about staleness."* Choosing 60 seconds means saying "I accept being up to a minute wrong."

**Why this sticks:** the naming-things joke is *already in your memory* from somewhere else. Attaching new material to something already stored is the cheapest encoding available.`,
    tricksHi: `### 🍱 "Jo baar-baar padha jaye aur kam badle, use cache karo"

Yahi ek vaakya lagbhag har cache theek se chun leta hai. Dono mein se ek bhi aadha sach na ho to cache mat karo.

### 😅 Do mushkil samasyaayein

Ek mashhoor line hai: *"Computer science mein sirf do mushkil cheezein hain: cache invalidation aur cheezon ke naam rakhna."*

Ye mazaak hai, aur asli jawab bhi. Cache jodna paanch minute ka kaam hai. **Purani copy kab hatani hai, yahi poora kaam hai.**

**Bolo:** *"Jodna aasan hai. Invalidate karna asli kaam hai."*

### 🗺️ Patterns, ek-ek line mein

- **Cache-aside** — cache dekho, na mile → laao → rakho. Default, aur 90% asli istemal.
- **Write-through** — cache aur database dono mein saath likho. Hamesha taaza, writes dheemi.
- **Write-behind** — cache mein likho, database mein baad mein. Tez, aur data ja sakta hai.

### 💥 Teen nakaamiyan ginane layak

- **Stampede** — key expire hui aur 1,000 requests ek saath use dobara banane lagi
- **Purana data** — cache kar diya aur invalidate karna bhool gaye
- **Kharab jawab cache ho gaya** — ab aap sabko error parosss rahe ho, wo bhi tezi se

**Bolo:** *"TTL puranepan ke baare mein ek vaada hai."* 60 second chunne ka matlab hai "mujhe ek minute tak galat hona manzoor hai."

**Ye kyun tikta hai:** naam rakhne wala mazaak *pehle se aapki yaad mein* kahin se maujood hai. Nayi baat ko pehle se jama kisi cheez se jod dena sabse sasti encoding hai.`,
  },

  'sd-queues-async': {
    tricks: `### 📮 "Do not make the user wait for the email"

They clicked **Sign Up**. Sending a welcome email takes 800 ms and might fail. Why should that be their problem?

Put it on a queue. Respond immediately. Send the email in the background.

**Say it:** *"Respond now, work later."*

### ✅ What belongs on a queue

Emails, PDF generation, image resizing, webhooks, reports, anything calling a slow third party.

**The test:** *"does the user need the result to continue?"* No → queue it.

### 🔁 The rule that catches everyone

**Jobs will run twice.** Networks retry, workers crash after doing the work but before acknowledging it. This is not an edge case — it is normal operation.

So **every job must be idempotent**. Running it twice must be harmless.

**Say it:** *"Assume it runs twice, because it will."*

### ☠️ The dead-letter queue

A job that fails forever must go somewhere, or it blocks the queue and retries until the heat death of the universe. That somewhere is the DLQ — and someone has to actually look at it.

**Why this sticks:** "assume it runs twice, because it will" is *a rule plus its justification in one breath*. Rules with their reason attached survive far longer than rules alone, because the reason lets you rebuild the rule if you forget it.`,
    tricksHi: `### 📮 "User ko email ke liye mat rulao"

Usne **Sign Up** dabaya. Welcome email bhejne mein 800 ms lagte hain aur wo fail bhi ho sakti hai. Ye uski samasya kyun ho?

Use queue par daal do. Turant jawab do. Email peeche bhejo.

**Bolo:** *"Jawab abhi, kaam baad mein."*

### ✅ Queue par kya jaana chahiye

Emails, PDF banana, image resize, webhooks, reports, koi bhi dheemi teesri party ko call karna.

**Jaanch:** *"kya user ko aage badhne ke liye natija chahiye?"* Nahi → queue par daalo.

### 🔁 Wo niyam jo sabko pakadta hai

**Jobs do baar chalengi.** Network retry karte hain, workers kaam karke acknowledge karne se pehle crash ho jate hain. Ye kinare ka case nahi — ye normal hai.

Isliye **har job idempotent honi chahiye**. Do baar chalne se kuch nahi bigadna chahiye.

**Bolo:** *"Maan lo do baar chalegi, kyunki chalegi."*

### ☠️ Dead-letter queue

Jo job hamesha fail hoti hai use kahin jaana hoga, warna wo queue rok degi aur srishti ke ant tak retry karti rahegi. Wo jagah DLQ hai — aur kisi ko use sach mein dekhna bhi hoga.

**Ye kyun tikta hai:** "maan lo do baar chalegi, kyunki chalegi" *ek saans mein niyam aur uski wajah* hai. Wajah ke saath jude niyam akele niyamon se kahin lambe jeete hain, kyunki wajah se niyam dobara bana liya jata hai.`,
  },

  /* ═══════════════════════════════ Tooling ══════════════════════════════════ */

  'git-branching-and-history': {
    tricks: `### 🌿 "A branch is a sticky note on a commit"

It is not a copy of your code. It is a **pointer**, which is why creating one is instant even in a huge repository.

**Say it:** *"Branches are labels, not folders."*

### 🔀 Merge vs rebase, in one image

- **Merge** — *"here is what happened, honestly"*, including the messy parallel work. History is true and forked.
- **Rebase** — *"let us pretend I started from the latest"*. History is a clean straight line, and it is a **rewritten** one.

**Say it:** *"Merge tells the truth, rebase tells a better story."*

### ☠️ The one rule that prevents disaster

**Never rebase a branch someone else has pulled.**

Rebasing rewrites commit hashes. Everyone else's history now disagrees with yours, and fixing it involves force pushes and pain.

**Say it:** *"Rebase local, merge shared."*

### 🧯 The three "undo" commands, sorted by danger

- **\`git revert\`** — makes a **new** commit that undoes an old one. **Safe on shared branches.**
- **\`git reset --soft\`** — moves the pointer, keeps your changes staged
- **\`git reset --hard\`** — moves the pointer and **deletes your work**. No confirmation.

**Say it:** *"Revert is public, reset is private."*

**Why this sticks:** "merge tells the truth, rebase tells a better story" carries the *trade-off*, not just the mechanism. It also happens to be a fair description of the actual debate, which is why it survives contact with real teams.`,
    tricksHi: `### 🌿 "Branch ek commit par chipka hua parcha hai"

Ye aapke code ki copy nahi hai. Ye ek **pointer** hai, aur isiliye badi se badi repo mein bhi branch banana turant hota hai.

**Bolo:** *"Branch label hain, folder nahi."*

### 🔀 Merge aur rebase, ek tasveer mein

- **Merge** — *"jo hua wo ye hai, imaandari se"*, us bikhre samanantar kaam samet. Itihaas sacha aur do-shakha wala.
- **Rebase** — *"maan lo maine sabse naye se shuru kiya tha"*. Itihaas saaf seedhi lakeer, aur wo **dobara likha hua** hai.

**Bolo:** *"Merge sach batata hai, rebase behtar kahani."*

### ☠️ Wo ek niyam jo tabaahi rokta hai

**Jis branch ko kisi aur ne pull kar liya ho use kabhi rebase mat karo.**

Rebase commit hashes dobara likh deta hai. Ab baaki sabka itihaas aapse alag hai, aur ise theek karne mein force push aur dard lagta hai.

**Bolo:** *"Local rebase, saanjha merge."*

### 🧯 Teen "undo" commands, khatre ke kram mein

- **\`git revert\`** — purane ko ulatne ke liye **naya** commit banata hai. **Saanjhi branch par surakshit.**
- **\`git reset --soft\`** — pointer hilata hai, badlav staged rakhta hai
- **\`git reset --hard\`** — pointer hilata hai aur **aapka kaam mita deta hai**. Koi pushti nahi.

**Bolo:** *"Revert sarvajanik hai, reset nijee."*

**Ye kyun tikta hai:** "merge sach batata hai, rebase behtar kahani" sirf tareeka nahi, *sauda* bhi le kar chalta hai. Aur ye asli bahes ka theek hulia bhi hai, isiliye ye asli teams ke saamne bhi tikta hai.`,
  },

  'docker-fundamentals': {
    tricks: `### 🍰 "Image is the recipe. Container is the cake."

One recipe, many cakes. Eat a cake and the recipe is untouched.

**Say it:** *"Image is a class, container is an instance."*

That second phrasing is the one to use in an interview if you have an OOP background — same idea, different audience.

### 📦 Why Docker exists at all

*"It works on my machine"* — and now the machine ships **with** the code.

That is the whole pitch in one line.

### 🧅 Layers, and why order matters enormously

Each Dockerfile instruction is a cached layer. Change one and **everything after it rebuilds**.

So copy \`package.json\` and install **before** copying your source:

\`\`\`dockerfile
COPY package*.json ./
RUN npm ci              # cached — only reruns when dependencies change
COPY . .                # your code changes constantly, and that is fine
\`\`\`

Reverse those and every one-character edit reinstalls every dependency.

**Say it:** *"Copy what changes least, first."*

### 🏋️ Multi-stage builds

Build in a **fat** image with all the compilers, copy only the output into a **thin** one. A Node image can go from 1.2 GB to 150 MB — and a smaller image is also a smaller attack surface.

**Why this sticks:** "copy what changes least, first" is *actionable phrasing* — it tells you what to do, not what is true. Instructions are recalled at the moment of action; facts often are not.`,
    tricksHi: `### 🍰 "Image recipe hai. Container cake."

Ek recipe, kai cake. Cake khao to recipe ko kuch nahi hota.

**Bolo:** *"Image class hai, container instance."*

Doosra vaakya interview mein bolne layak hai agar OOP ka background hai — wahi baat, alag sunne wale.

### 📦 Docker hai hi kyun

*"Mere computer par to chal raha hai"* — aur ab computer bhi code ke **saath** hi ja raha hai.

Poori baat ek line mein yahi hai.

### 🧅 Layers, aur kram itna kyun matter karta hai

Dockerfile ka har nirdesh ek cached layer hai. Ek badlo aur **uske baad ka sab dobara banta hai**.

Isliye source copy karne se **pehle** \`package.json\` copy karke install karo:

\`\`\`dockerfile
COPY package*.json ./
RUN npm ci              # cached — sirf dependencies badalne par chalta hai
COPY . .                # aapka code lagatar badalta hai, aur wo theek hai
\`\`\`

Inhe ulta karo aur ek akshar ka badlav bhi saari dependencies dobara install karega.

**Bolo:** *"Jo sabse kam badle, use pehle copy karo."*

### 🏋️ Multi-stage builds

**Moti** image mein saare compilers ke saath build karo, sirf natija **patli** image mein copy karo. Node image 1.2 GB se 150 MB tak aa sakti hai — aur chhoti image ka hamla-kshetra bhi chhota hota hai.

**Ye kyun tikta hai:** "jo sabse kam badle use pehle copy karo" *kaam bata ne wala vaakya* hai — ye batata hai karna kya hai, ye nahi ki sach kya hai. Nirdesh kaam ke waqt yaad aate hain; facts aksar nahi.`,
  },

  'testing-pyramid': {
    tricks: `### 🔺 "Many small, some medium, few large"

- **Unit** — fast, cheap, hundreds of them
- **Integration** — do the pieces work together? dozens
- **E2E** — a real browser doing a real journey. Slow, brittle, a handful

**Say it:** *"Wide at the bottom, narrow at the top."*

### 🍦 The anti-pattern with the best name

The **ice cream cone** — mostly E2E, almost no unit tests. The suite takes 40 minutes, fails randomly, and everyone learns to re-run it rather than read it.

At that point the tests have stopped providing information, which means they have stopped being tests.

**Say it:** *"A test that everyone re-runs is not a test."*

### 🎯 What to actually test

Test **behaviour**, not implementation. If a refactor that changes nothing about what the code *does* breaks your tests, the tests were coupled to the wrong thing.

**Say it:** *"Test what it does, not how."*

### 📈 On coverage

100% coverage proves every line **ran**. It does not prove any line was **checked**. A test with no assertions gives full coverage and zero value.

**Why this sticks:** "ice cream cone" is *funny, visual and inverts the pyramid you just learned*. Learning the correct shape and its comic opposite together means each one cues the other.`,
    tricksHi: `### 🔺 "Bahut saare chhote, kuch beech ke, thode bade"

- **Unit** — tez, saste, sau se zyada
- **Integration** — hisse saath mein chalte hain? darjanon
- **E2E** — asli browser, asli safar. Dheema, naazuk, ginti ke

**Bolo:** *"Neeche chauda, upar patla."*

### 🍦 Wo anti-pattern jiska naam sabse achha hai

**Ice cream cone** — zyadatar E2E, unit tests lagbhag nahi. Suite 40 minute leti hai, kabhi bhi fail hoti hai, aur sab use padhne ki jagah dobara chalana seekh jate hain.

Us mod par tests jaankari dena band kar dete hain, matlab wo tests rehte hi nahi.

**Bolo:** *"Jis test ko sab dobara chalate hain wo test nahi hai."*

### 🎯 Test sach mein kis ka karein

**Bartaav** ka test karo, implementation ka nahi. Agar aisa refactor jo code ke *kaam* mein kuch nahi badalta aapke tests todta hai, to tests galat cheez se jude the.

**Bolo:** *"Kya karta hai wo test karo, kaise karta hai wo nahi."*

### 📈 Coverage par

100% coverage sabit karta hai ki har line **chali**. Ye sabit nahi karta ki koi line **jaanchi** gayi. Bina assertion wala test poora coverage deta hai aur zero keemat.

**Ye kyun tikta hai:** "ice cream cone" *mazedaar hai, dikhta hai, aur abhi seekhe pyramid ko ulta kar deta hai*. Sahi shakal aur uska mazaakiya ulta saath seekhne se dono ek doosre ko yaad dilate hain.`,
  },
};
